Repository knative/eventing-contrib, pull requests merged in 2018-12, with the labels that each got.

#136 Add @Harwayne as reviewer
  OWNERS
Labels: approved, lgtm, size/S

#133 Make verify-codegen.sh also check /vendor
  hack/verify-codegen.sh
Labels: approved, lgtm, size/XS

#137 Use CR unstructured client for dynamic objects
  pkg/controller/containersource/reconcile.go
  pkg/controller/containersource/reconcile_test.go
  pkg/controller/gcppubsub/reconcile.go
  pkg/controller/gcppubsub/reconcile_test.go
  pkg/controller/githubsource/reconcile.go
  pkg/controller/githubsource/reconcile_test.go
  pkg/controller/kuberneteseventsource/provider.go
  pkg/controller/sdk/provider.go
  pkg/controller/sdk/reconciler.go
  pkg/controller/sinks/sinks.go
  pkg/controller/sinks/sinks_test.go
Labels: approved, lgtm, size/XL

#138 Add Websocket ContainerSource.
  Gopkg.lock
  Gopkg.toml
  README.md
  cmd/websocketsource/main.go
  pkg/sources/eventforwarder.go
  pkg/sources/eventforwarder_test.go
  samples/sources_v1alpha2_websocketsource.yaml
  vendor/github.com/gorilla/websocket/AUTHORS
  vendor/github.com/gorilla/websocket/LICENSE
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/client_clone.go
  vendor/github.com/gorilla/websocket/client_clone_legacy.go
  vendor/github.com/gorilla/websocket/compression.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/conn_write.go
  vendor/github.com/gorilla/websocket/conn_write_legacy.go
  vendor/github.com/gorilla/websocket/doc.go
  vendor/github.com/gorilla/websocket/json.go
  vendor/github.com/gorilla/websocket/mask.go
  vendor/github.com/gorilla/websocket/mask_safe.go
  vendor/github.com/gorilla/websocket/prepared.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/trace.go
  vendor/github.com/gorilla/websocket/trace_17.go
  vendor/github.com/gorilla/websocket/util.go
  vendor/github.com/gorilla/websocket/x_net_proxy.go
Labels: approved, lgtm, size/XXL

#143 Remove unnecessary Addressable scheme register
  pkg/controller/containersource/reconcile_test.go
  pkg/controller/gcppubsub/reconcile_test.go
  pkg/controller/githubsource/reconcile_test.go
Labels: approved, lgtm, size/M

#129 fix: propagate GH headers into cloud event
  .gitignore
  pkg/githubsource/receive_adapter.go
  pkg/githubsource/receive_adapter_test.go
Labels: approved, lgtm, size/M

#140 Update test-infra to include latest features of release.sh
  Gopkg.lock
  hack/release.md
  hack/release.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#146 Split GitHubSource finalizer into separate method
  pkg/controller/githubsource/reconcile.go
  pkg/controller/githubsource/reconcile_test.go
Labels: approved, lgtm, size/L

#150 Format markdown
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
  config/README.md
  hack/README.md
  hack/release.md
  samples/cronjob-source/README.md
  samples/gcp-pubsub-source/README.md
  samples/kubernetes-event-source/README.md
  test/README.md
Labels: approved, lgtm, size/XL

#153 Format markdown
  samples/gcp-pubsub-source/README.md
Labels: approved, lgtm, size/XS

#152 golang format tools
  cmd/githubsource/main.go
  pkg/controller/cronjobsource/provider.go
  pkg/controller/cronjobsource/reconcile.go
  pkg/controller/cronjobsource/reconcile_test.go
  pkg/controller/cronjobsource/resources/receive_adapter.go
  pkg/controller/cronjobsource/resources/receive_adapter_test.go
  pkg/controller/gcppubsub/provider.go
  pkg/controller/gcppubsub/reconcile.go
  pkg/controller/gcppubsub/reconcile_test.go
  pkg/controller/gcppubsub/resources/receive_adapter.go
  pkg/controller/gcppubsub/resources/receive_adapter_test.go
  pkg/controller/sdk/finalizers_accessor_test.go
Labels: approved, lgtm, size/S

#158 Format markdown
  samples/awssqs_source/README.md
Labels: approved, lgtm, needs-ok-to-test, size/L

#156 golang format tools
  cmd/awssqs_receive_adapter/main.go
  pkg/adapter/awssqs/adapter.go
  pkg/adapter/awssqs/adapter_test.go
  pkg/apis/sources/v1alpha1/aws_sqs_types_test.go
  pkg/controller/awssqs/provider.go
  pkg/controller/awssqs/reconcile.go
  pkg/controller/awssqs/resources/receive_adapter.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#155 Bump "safe" dependencies
  Gopkg.lock
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/googleapis/gax-go/gax.go
  vendor/github.com/googleapis/gax-go/invoke.go
  vendor/github.com/markbates/inflect/inflect.go
  vendor/github.com/markbates/inflect/version.go
  vendor/github.com/onsi/ginkgo/config/config.go
  vendor/github.com/onsi/ginkgo/ginkgo_dsl.go
  vendor/github.com/onsi/ginkgo/internal/leafnodes/setup_nodes.go
  vendor/github.com/onsi/ginkgo/internal/spec/spec.go
  vendor/github.com/onsi/ginkgo/internal/suite/suite.go
  vendor/github.com/onsi/ginkgo/reporters/junit_reporter.go
  vendor/github.com/onsi/ginkgo/types/types.go
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers/be_closed_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_sent_matcher.go
  vendor/github.com/onsi/gomega/matchers/match_yaml_matcher.go
  vendor/github.com/onsi/gomega/matchers/receive_matcher.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/bipartitegraph/bipartitegraph.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/timer.go
  vendor/google.golang.org/appengine/appengine.go
  vendor/google.golang.org/appengine/internal/api.go
  vendor/google.golang.org/appengine/internal/api_pre17.go
  vendor/google.golang.org/appengine/internal/identity.go
  vendor/google.golang.org/appengine/internal/identity_classic.go
  vendor/google.golang.org/appengine/internal/identity_flex.go
  vendor/gopkg.in/yaml.v2/encode.go
Labels: approved, lgtm, size/XXL

#161 Update test-infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L
