Repository knative/eventing-contrib, pull requests merged in 2018-10, with the labels that each got.

#1 Adding smaller set of owners for sources.
  .gitattributes
  .github/issue-template.md
  .github/pull-request-template.md
  .gitignore
  AUTHORS
  OWNERS
Labels: size/M

#7 adding a test shell dir
  test/OWNERS
  test/README.md
  test/e2e-tests.sh
  test/image_paths.txt
  test/presubmit-tests.sh
  test/upload-test-images.sh
Labels: size/L

#9 tone down the release to not overwrite eventing.
  hack/release.sh
Labels: size/M

#13 Update the README and supporting documents.
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
Labels: approved, lgtm, size/L

#14 Fix container source.
  Makefile
  config/crds/sources_v1alpha1_containersources.yaml
  hack/release.sh
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  pkg/apis/sources/v1alpha1/register.go
  pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#17 Fix simple instructions typo
  DEVELOPMENT.md
Labels: lgtm, size/XS

#20 Convert README.md to text
  README.md
Labels: approved, lgtm, size/XS

#24 Add rbac annotations to ContainerSource controller
  config/default.yaml
  config/rbac/rbac_role.yaml
  pkg/controller/containersource/doc.go
Labels: approved, lgtm, size/M

#32 adding a new makefile, like the old makefile.
  Makefile
Labels: approved, lgtm, size/M

#34 Some of the methods could be helpful in the sdk
  pkg/controller/containersource/reconcile.go
  pkg/controller/containersource/reconcile_test.go
  pkg/controller/sdk/helpers.go
  pkg/controller/sdk/sinks.go
Labels: approved, lgtm, size/L

#44 Found that we were calling to dep ensure, call the hack script instead.
  hack/update-manifests.sh
Labels: approved, lgtm, size/XS

#43 Add support for manipulating Finalizers to the SDK
  Gopkg.lock
  pkg/controller/sdk/finalizers_accessor.go
  pkg/controller/sdk/finalizers_accessor_test.go
  pkg/controller/sdk/reconciler.go
Labels: approved, lgtm, size/L

#27 using cloud events for the sample heartbeat
  Gopkg.lock
  cmd/heartbeats/main.go
  cmd/heartbeats_receiver/main.go
Labels: approved, lgtm, size/L

#47 Fix: update to new test-infra.
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: lgtm, size/L

#48 Integrate k8s events
  cmd/kuberneteseventsource/main.go
  config/crds/sources_v1alpha1_kuberneteseventsource.yaml
  config/default.yaml
  pkg/apis/sources/v1alpha1/kuberneteseventsource_types.go
  pkg/controller/kuberneteseventsource/resources/containersource.go
Labels: approved, lgtm, size/M

#53 ContainerSource updates
  config/crds/sources_v1alpha1_containersource.yaml
  config/default.yaml
  pkg/apis/sources/v1alpha1/containersource_types.go
  pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/containersource/reconcile.go
  pkg/controller/containersource/resources/arguments.go
  pkg/controller/containersource/resources/deployment.go
Labels: approved, lgtm, size/M
