Repository knative/eventing-contrib, pull requests merged in 2018-11, with the labels that each got.

#62 Use knative/pkg/cloudevents over knative/eventing/pkg/event
  Gopkg.lock
  cmd/gcppubsub_receive_adapter/main.go
  cmd/heartbeats/main.go
  cmd/heartbeats_receiver/main.go
  cmd/kuberneteseventsource/main.go
  third_party/VENDOR-LICENSE
  vendor/github.com/knative/eventing/AUTHORS
  vendor/github.com/knative/eventing/LICENSE
  vendor/github.com/knative/eventing/cmd/controller/kodata/LICENSE
  vendor/github.com/knative/eventing/cmd/controller/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/cmd/fanoutsidecar/kodata/LICENSE
  vendor/github.com/knative/eventing/cmd/fanoutsidecar/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/cmd/sendevent/kodata/LICENSE
  vendor/github.com/knative/eventing/cmd/sendevent/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/cmd/webhook/kodata/LICENSE
  vendor/github.com/knative/eventing/cmd/webhook/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/pkg/buses/gcppubsub/dispatcher/kodata/LICENSE
  vendor/github.com/knative/eventing/pkg/buses/gcppubsub/dispatcher/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/pkg/buses/gcppubsub/provisioner/kodata/LICENSE
  vendor/github.com/knative/eventing/pkg/buses/gcppubsub/provisioner/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/pkg/buses/kafka/dispatcher/kodata/LICENSE
  vendor/github.com/knative/eventing/pkg/buses/kafka/dispatcher/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/pkg/buses/kafka/provisioner/kodata/LICENSE
  vendor/github.com/knative/eventing/pkg/buses/kafka/provisioner/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/pkg/buses/stub/dispatcher/kodata/LICENSE
  vendor/github.com/knative/eventing/pkg/buses/stub/dispatcher/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/pkg/controller/eventing/inmemory/controller/kodata/LICENSE
  vendor/github.com/knative/eventing/pkg/controller/eventing/inmemory/controller/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/pkg/sources/gcppubsub/kodata/LICENSE
  vendor/github.com/knative/eventing/pkg/sources/gcppubsub/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/pkg/sources/gcppubsub/receive_adapter/kodata/LICENSE
  vendor/github.com/knative/eventing/pkg/sources/gcppubsub/receive_adapter/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/pkg/sources/github/feedlet/kodata/LICENSE
  vendor/github.com/knative/eventing/pkg/sources/github/feedlet/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/pkg/sources/github/receive_adapter/kodata/LICENSE
  vendor/github.com/knative/eventing/pkg/sources/github/receive_adapter/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/pkg/sources/k8sevents/kodata/LICENSE
  vendor/github.com/knative/eventing/pkg/sources/k8sevents/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/pkg/sources/k8sevents/receive_adapter/kodata/LICENSE
  vendor/github.com/knative/eventing/pkg/sources/k8sevents/receive_adapter/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/test/e2e/k8sevents/kodata/LICENSE
  vendor/github.com/knative/eventing/test/e2e/k8sevents/kodata/VENDOR-LICENSE
  vendor/github.com/knative/pkg/cloudevents/doc.go
  vendor/github.com/knative/pkg/cloudevents/encoding_binary.go
  vendor/github.com/knative/pkg/cloudevents/encoding_structured.go
  vendor/github.com/knative/pkg/cloudevents/event.go
  vendor/github.com/knative/pkg/cloudevents/handler.go
Labels: approved, lgtm, size/XL

#60 Add ServiceAccountName to ContainerSource and KES
  pkg/apis/sources/v1alpha1/containersource_types.go
  pkg/apis/sources/v1alpha1/kuberneteseventsource_types.go
  pkg/controller/containersource/reconcile.go
  pkg/controller/containersource/reconcile_test.go
  pkg/controller/containersource/resources/arguments.go
  pkg/controller/containersource/resources/deployment.go
  pkg/controller/kuberneteseventsource/resources/containersource.go
Labels: approved, lgtm, size/L

#63 do not respect crd status generation.
  Gopkg.lock
  Gopkg.toml
  config/crds/sources_v1alpha1_containersource.yaml
  config/crds/sources_v1alpha1_gcppubsubsource.yaml
  config/crds/sources_v1alpha1_kuberneteseventsource.yaml
  config/default-gcppubsub.yaml
  config/default.yaml
  vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/crd.go
Labels: approved, lgtm, size/M

#64 Update DEVELOPMENT.md with correct instructions
  DEVELOPMENT.md
Labels: approved, lgtm, size/M

#66 Define release yamls
  hack/release.sh
Labels: approved, lgtm, size/XS

#51 Sample for working with k8s events
  samples/kubernetes-event-source/README.md
  samples/kubernetes-event-source/channel.yaml
  samples/kubernetes-event-source/k8s-events.yaml
  samples/kubernetes-event-source/serviceaccount.yaml
  samples/kubernetes-event-source/subscription.yaml
Labels: approved, lgtm, size/L

#69 Add a release.yaml default release
  hack/release.sh
Labels: approved, lgtm, size/XS

#70 Update the release script
  Gopkg.lock
  hack/release.sh
  hack/update-manifests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/dummy.go
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#71 Return an error from GetSinkURI if DomainInternal is empty
  pkg/controller/sinks/sinks.go
Labels: approved, lgtm, size/S

#72 Update documentation about hack/ and release.sh
  hack/README.md
  hack/release.md
Labels: approved, lgtm, size/M

#76 Addressable change
  Gopkg.lock
  Gopkg.toml
  pkg/controller/containersource/reconcile_test.go
  pkg/controller/gcppubsub/reconcile_test.go
  pkg/controller/sinks/sinks.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/register.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/retired_targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/sinkable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL

#73 Correcting file reference
  samples/kubernetes-event-source/README.md
Labels: approved, lgtm, size/XS

#77 Adding status accessor tests in SDK.
  pkg/controller/sdk/reconciler.go
  pkg/controller/sdk/status_accessor.go
  pkg/controller/sdk/status_accessor_test.go
Labels: approved, lgtm, size/L

#80 Switch to PullIfNotPresent
  pkg/controller/containersource/reconcile_test.go
  pkg/controller/containersource/resources/deployment.go
Labels: approved, lgtm, size/XS

#82 More updates to the release script
  Gopkg.lock
  hack/release.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/M

#83 Exclude test and vendor from coverage. now matches serving
  .gitattributes
Labels: approved, lgtm, size/XS

#84 Update Deployment spec on ContainerSource change
  pkg/controller/containersource/reconcile.go
Labels: approved, lgtm, size/S

#81 Refactor pub/sub receive adapter + Add tests.
  cmd/gcppubsub_receive_adapter/main.go
  pkg/adapter/gcppubsub/adapter.go
  pkg/adapter/gcppubsub/adapter_test.go
  pkg/adapter/gcppubsub/pubsub.go
  pkg/adapter/gcppubsub/pubsub_test.go
Labels: approved, lgtm, size/XL

#87 test register resource
  pkg/apis/sources/v1alpha1/register_test.go
Labels: approved, lgtm, size/M

#85 Refactor the k8s events adapter, adding test
  Gopkg.lock
  cmd/kuberneteseventsource/main.go
  pkg/adapter/kubernetesevents/adapter.go
  pkg/adapter/kubernetesevents/adapter_test.go
  pkg/adapter/kubernetesevents/cloudevent.go
  pkg/adapter/kubernetesevents/cloudevent_test.go
Labels: approved, lgtm, size/XL

#90 Bump Serving to 0.2.1
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/knative/serving/pkg/apis/serving/v1alpha1/route_types.go
  vendor/github.com/knative/serving/pkg/apis/serving/v1alpha1/service_types.go
  vendor/github.com/knative/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#91 Adding categories
  config/crds/sources_v1alpha1_githubsource.yaml
  config/crds/sources_v1alpha1_kuberneteseventsource.yaml
  config/default-gcppubsub.yaml
  config/default.yaml
  pkg/apis/sources/v1alpha1/githubsource_types.go
  pkg/apis/sources/v1alpha1/kuberneteseventsource_types.go
Labels: approved, lgtm, size/M

#94 Test MakeContainerSource
  pkg/controller/kuberneteseventsource/resources/containersource_test.go
Labels: approved, lgtm, size/M

#93 Adding ContainerSource reconcile to happy test.
  pkg/controller/containersource/reconcile.go
  pkg/controller/containersource/reconcile_test.go
Labels: approved, lgtm, size/L

#88 Adding container source deployment conversion test.
  pkg/controller/containersource/resources/deployment.go
  pkg/controller/containersource/resources/deployment_test.go
Labels: approved, lgtm, size/L

#99 Print the string instead of the pointer
  cmd/githubsource/main.go
Labels: approved, lgtm, size/XS

#101 Fix passing yamls to hub tool
  hack/release.sh
Labels: approved, lgtm, size/XS

#103 Exclude code in testing/ dirs from coverage
  .gitattributes
Labels: approved, lgtm, size/XS

#104 Fix schema in gcp pubsub sample
  samples/gcp-pubsub-source/subscriber.yaml
Labels: approved, lgtm, size/XS

#108 Use DeepDerivative instead of DeepEqual
  pkg/controller/containersource/reconcile.go
Labels: approved, lgtm, size/XS

#110 Use Status subresource
  config/crds/sources_v1alpha1_containersource.yaml
  config/crds/sources_v1alpha1_gcppubsubsource.yaml
  config/crds/sources_v1alpha1_githubsource.yaml
  config/crds/sources_v1alpha1_kuberneteseventsource.yaml
  config/default-gcppubsub.yaml
  config/default.yaml
  pkg/apis/sources/v1alpha1/containersource_types.go
  pkg/apis/sources/v1alpha1/gcp_pubsub_types.go
  pkg/apis/sources/v1alpha1/githubsource_types.go
  pkg/apis/sources/v1alpha1/kuberneteseventsource_types.go
  pkg/controller/kuberneteseventsource/reconcile.go
  pkg/controller/sdk/reconciler.go
Labels: approved, lgtm, size/M

#98 Only try to print out the subscription if it has been created successfully
  pkg/controller/gcppubsub/reconcile.go
Labels: approved, lgtm, size/XS

#112 Convert README.md to UTF8
  README.md
Labels: approved, lgtm, size/XS

#113 Change Sinkable to Addressable again
  README.md
Labels: approved, lgtm, size/S

#115 Revert "Use Status subresource (#110)"
  config/crds/sources_v1alpha1_containersource.yaml
  config/crds/sources_v1alpha1_gcppubsubsource.yaml
  config/crds/sources_v1alpha1_githubsource.yaml
  config/crds/sources_v1alpha1_kuberneteseventsource.yaml
  config/default-gcppubsub.yaml
  config/default.yaml
  pkg/apis/sources/v1alpha1/containersource_types.go
  pkg/apis/sources/v1alpha1/gcp_pubsub_types.go
  pkg/apis/sources/v1alpha1/githubsource_types.go
  pkg/apis/sources/v1alpha1/kuberneteseventsource_types.go
  pkg/controller/kuberneteseventsource/reconcile.go
  pkg/controller/sdk/reconciler.go
Labels: approved, lgtm, size/M

#117 Improve debugability of the KubernetesEventsSource.
  pkg/adapter/kubernetesevents/adapter.go
Labels: approved, lgtm, size/S

#116 Bump controller tools
  Gopkg.lock
  Gopkg.toml
  config/crds/sources_v1alpha1_containersource.yaml
  config/crds/sources_v1alpha1_gcppubsubsource.yaml
  config/crds/sources_v1alpha1_githubsource.yaml
  config/crds/sources_v1alpha1_kuberneteseventsource.yaml
  config/default-gcppubsub.yaml
  config/default.yaml
  vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/crd.go
  vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/util.go
  vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/types.go
Labels: approved, lgtm, size/L

#122 Adding sinks test
  pkg/controller/sinks/sinks_test.go
Labels: approved, lgtm, size/L

#125 Make message dumper a releasable thing.
  config/tools/message-dumper.yaml
  hack/release.sh
Labels: approved, lgtm, size/S

#130 Update pkg, ignoring severity in tests
  Gopkg.lock
  Gopkg.toml
  config/crds/sources_v1alpha1_containersource.yaml
  config/crds/sources_v1alpha1_gcppubsubsource.yaml
  config/crds/sources_v1alpha1_githubsource.yaml
  config/crds/sources_v1alpha1_kuberneteseventsource.yaml
  config/default-gcppubsub.yaml
  config/default.yaml
  pkg/apis/sources/v1alpha1/containersource_types_test.go
  pkg/apis/sources/v1alpha1/gcp_pubsub_types_test.go
  pkg/apis/sources/v1alpha1/githubsource_types_test.go
  pkg/apis/sources/v1alpha1/kuberneteseventsource_types_test.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/retired_targetable_types.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/changeset/commit.go
  vendor/github.com/knative/pkg/changeset/doc.go
  vendor/github.com/knative/pkg/cloudevents/encoding_binary.go
  vendor/github.com/knative/pkg/cloudevents/event.go
  vendor/github.com/knative/pkg/kmeta/accessor.go
  vendor/github.com/knative/pkg/logging/config.go
  vendor/github.com/knative/pkg/logging/logkey/constants.go
Labels: approved, lgtm, needs-ok-to-test, size/L

#131 Remove images deletion step from e2e test / Update test-infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/github.com/knative/test-infra/tools/dep-collector/imports.go
Labels: approved, lgtm, size/L

#132 Publish nightly knative/eventing-sources releases to knative-nightly
  hack/release.md
  hack/release.sh
Labels: approved, lgtm, size/XS
