Repository knative/eventing-contrib, pull requests merged in 2019-07, with the labels that each got.

#480 fix 404 in API comment for HTML ref doc build
  contrib/gcppubsub/pkg/apis/sources/v1alpha1/gcp_pubsub_types.go
Labels: approved, cla: yes, lgtm, size/XS

#486 YAMLS_TO_PUBLISH is deprecated, use ARTIFACTS_TO_PUBLISH
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#489 Added v1beta1 serving API for github source.
  contrib/github/pkg/apis/addtoscheme_serving_v1beta1.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#485 Remove Erik and Nikhil from Productivity Reviewers
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#488 Point release documentation to knative/test-infra
  hack/release.md
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/M

#479 Make gcloud a no-op if not available for test scripts
  test/upload-test-images.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#494 Format markdown
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#495 golang format tools
  gcppubsub/cmd/receive_adapter/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#497 clean up gopkg.lock
  Gopkg.lock
Labels: approved, cla: yes, lgtm, size/M

#498 verify codegen also check Gopkg.lock
  hack/verify-codegen.sh
Labels: approved, cla: yes, lgtm, size/S
