Repository knative/eventing-contrib, pull requests merged in 2019-09, with the labels that each got.

#548 Doc improvement: Adding some content for Apache Kafka components
  README.md
  kafka/README.md
  kafka/channel/README.md
  kafka/source/README.md
  kafka/source/samples/README.md
  kafka/source/samples/event-display.yaml
  kafka/source/samples/event-source.yaml
  kafka/source/samples/kafka-topic.yaml
Labels: approved, cla: yes, lgtm, size/L

#567 Add missing flow field to Camel source CRD validation
  camel/source/config/300-camelsource.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#568 golang format tools
  kafka/channel/pkg/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#569 Format markdown
  kafka/README.md
  kafka/channel/README.md
  kafka/source/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#554 Refactored Kafka src and ch code to reuse same consumer group handler code
  Gopkg.lock
  kafka/channel/cmd/channel_dispatcher/main.go
  kafka/channel/config/400-kafka-config.yaml
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
  kafka/channel/pkg/utils/util.go
  kafka/channel/pkg/utils/util_test.go
  kafka/common/OWNERS
  kafka/common/pkg/kafka/consumer_factory.go
  kafka/common/pkg/kafka/consumer_factory_test.go
  kafka/common/pkg/kafka/consumer_handler.go
  kafka/common/pkg/kafka/consumer_handler_test.go
  kafka/source/pkg/adapter/adapter.go
  kafka/source/pkg/adapter/adapter_test.go
  third_party/VENDOR-LICENSE
  vendor/github.com/bsm/sarama-cluster/LICENSE
  vendor/github.com/bsm/sarama-cluster/balancer.go
  vendor/github.com/bsm/sarama-cluster/client.go
  vendor/github.com/bsm/sarama-cluster/cluster.go
  vendor/github.com/bsm/sarama-cluster/config.go
  vendor/github.com/bsm/sarama-cluster/consumer.go
  vendor/github.com/bsm/sarama-cluster/doc.go
  vendor/github.com/bsm/sarama-cluster/offsets.go
  vendor/github.com/bsm/sarama-cluster/partitions.go
  vendor/github.com/bsm/sarama-cluster/util.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#572 Update compatible Camel K version and polish Camel source doc
  camel/source/samples/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#517 Adding NatssChannel CRD for release script
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#576 eventing-contrib test work with go1.13
  test/e2e_flags.go
Labels: approved, cla: yes, lgtm, size/XS

#579 Fix for issue 1059: implemented Kafka channel controller and dispatcher restart on config-kafka ConfigMap update
  kafka/channel/cmd/channel_controller/main.go
  kafka/channel/cmd/channel_dispatcher/main.go
  kafka/channel/pkg/utils/util.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#581 golang format tools
  kafka/channel/cmd/channel_controller/main.go
  kafka/channel/cmd/channel_dispatcher/main.go
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  kafka/channel/pkg/utils/util.go
  kafka/channel/pkg/utils/util_test.go
  kafka/common/pkg/kafka/consumer_factory.go
  kafka/common/pkg/kafka/consumer_factory_test.go
  kafka/common/pkg/kafka/consumer_handler.go
  kafka/common/pkg/kafka/consumer_handler_test.go
  kafka/source/pkg/adapter/adapter.go
  kafka/source/pkg/adapter/adapter_test.go
  natss/pkg/dispatcher/dispatcher.go
  natss/pkg/reconciler/dispatcher/natsschannel.go
  test/crd.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#582 Adding matzew to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#578 use ResourceAdmissionControllerPath setting
  kafka/channel/cmd/webhook/main.go
Labels: approved, cla: yes, lgtm, size/S

#587 add lionelvillard to the list of reviewers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#592 Use the term source
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#600 Stop using PrependGenerateNameReactor.
  kafka/channel/pkg/reconciler/testing/factory.go
  natss/pkg/reconciler/testing/factory.go
Labels: approved, cla: yes, lgtm, size/XS

#601 Improvements to KafkaSource adapter
  kafka/source/pkg/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/M

#602 Added benchmark for adapter
  kafka/source/pkg/adapter/adapter_benchmark_test.go
Labels: approved, cla: yes, lgtm, size/L

#603 golang format tools
  kafka/source/pkg/adapter/adapter.go
  kafka/source/pkg/adapter/adapter_benchmark_test.go
  test/config.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#605 Update eventing/pkg/test-infra
  Gopkg.lock
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/storage/names/generate.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/choice_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/parallel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/parallel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/parallel_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1alpha1/choice.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1alpha1/fake/fake_choice.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1alpha1/fake/fake_messaging_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1alpha1/fake/fake_parallel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1alpha1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1alpha1/messaging_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1alpha1/parallel.go
  vendor/knative.dev/eventing/pkg/client/listers/messaging/v1alpha1/choice.go
  vendor/knative.dev/eventing/pkg/client/listers/messaging/v1alpha1/expansion_generated.go
  vendor/knative.dev/eventing/pkg/client/listers/messaging/v1alpha1/parallel.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/apiserversource.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/choice.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/containersource.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/cronjobsource.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/parallel.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/trigger.go
  vendor/knative.dev/eventing/test/base/resources/constants.go
  vendor/knative.dev/eventing/test/common/creation.go
  vendor/knative.dev/eventing/test/common/test_runner.go
  vendor/knative.dev/eventing/test/common/typemeta.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/XXL

#606 Update Status.ObservedGeneration when reconcile sources resources
  awssqs/pkg/reconciler/awssqssource.go
  camel/source/pkg/reconciler/camelsource.go
  camel/source/pkg/reconciler/camelsource_test.go
  github/pkg/reconciler/githubsource.go
  github/pkg/reconciler/githubsource_test.go
  kafka/source/pkg/reconciler/kafkasource.go
  kafka/source/pkg/reconciler/kafkasource_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#593 Documentation Improvements
  DEVELOPMENT.md
  awssqs/samples/README.md
  awssqs/samples/awssqs-source.yaml
  awssqs/samples/display-resources.yaml
  camel/source/samples/display_resources.yaml
  camel/source/samples/source_camel_k.yaml
  camel/source/samples/source_telegram.yaml
  camel/source/samples/source_timer_flow.yaml
  github/samples/githubsource.yaml
  samples/cronjob-source/README.md
  samples/cronjob-source/channel.yaml
  samples/cronjob-source/source.yaml
  samples/cronjob-source/subscriber.yaml
  samples/heartbeats/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#611 golang format tools
  camel/source/pkg/reconciler/camelsource_test.go
  github/pkg/reconciler/githubsource_test.go
  kafka/source/pkg/reconciler/kafkasource_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#613 Format markdown
  DEVELOPMENT.md
  awssqs/samples/README.md
  samples/cronjob-source/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#615 devstats was removed, no need to clean it up
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/XS

#614 Enable NatssChannel control plane metrics
  natss/cmd/channel_controller/main.go
  natss/cmd/channel_dispatcher/main.go
  natss/config/500-controller.yaml
  natss/config/500-dispatcher.yaml
  natss/docs/metrics.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#616 Move OWNERs to root of kafka
  kafka/OWNERS
  kafka/common/OWNERS
  kafka/source/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#618 Format markdown
  natss/docs/metrics.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#619 Update OWNERS_ALIASES for Productivity WG
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#617 Kafka metrics for the channel
  kafka/channel/cmd/channel_controller/main.go
  kafka/channel/cmd/channel_dispatcher/main.go
  kafka/channel/cmd/webhook/main.go
  kafka/channel/config/500-controller.yaml
  kafka/channel/config/500-dispatcher.yaml
  kafka/channel/config/500-webhook.yaml
  kafka/docs/metrics.md
Labels: approved, cla: yes, lgtm, size/L

#623 Format markdown
  kafka/docs/metrics.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#624 golang format tools
  kafka/channel/cmd/webhook/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#626 Minior fix to have controller name to be valid for later metrics usage
  couchdb/source/cmd/controller/main.go
Labels: approved, cla: yes, lgtm, size/XS

#630 Format markdown
  couchdb/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#629 golang format tools
  couchdb/source/pkg/reconciler/couchdbsource.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#633 Skip the flaky e2e test
  test/e2e/channel_defaulter_test.go
Labels: approved, cla: yes, lgtm, size/XS

#628 Added benchmarks for kafka channel/kafka broker
  test/performance/broker-kafka/100-broker-perf-setup.yaml
  test/performance/broker-kafka/200-broker-perf.yaml
  test/performance/channel-kafka/100-channel-perf-setup.yaml
  test/performance/channel-kafka/200-channel-perf.yaml
Labels: approved, cla: yes, lgtm, size/XL

#632 Added couchdb and natss to the ./hack scripts where they were missing, updated third party licenses
  hack/release.sh
  hack/update-deps.sh
  third_party/VENDOR-LICENSE
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#631 Source registry
  awssqs/config/300-awssqssource.yaml
  couchdb/source/config/300-couchdbsource.yaml
  github/config/300-githubsource.yaml
  kafka/source/config/300-kafkasource.yaml
Labels: approved, cla: yes, lgtm, size/L

#634 Update OWNERS_ALIASES for Productivity WG
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS
