Repository knative/eventing-contrib, pull requests merged in 2019-08, with the labels that each got.

#504 Clarify override comment
  Gopkg.toml
Labels: approved, cla: yes, lgtm, size/XS

#501 fix #484: allow to skip camel k check
  camel/source/cmd/controller/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#506 Add eventTypes to importer/source CRDs
  contrib/awssqs/config/300-awssqssource.yaml
  contrib/github/config/300-githubsource.yaml
  gcppubsub/config/300-gcppubsubsource.yaml
  kafka/source/config/300-kafkasource.yaml
Labels: approved, cla: yes, lgtm, size/L

#509 golang format tools
  camel/source/pkg/reconciler/camelsource_test.go
  camel/source/pkg/reconciler/resources/flow.go
  camel/source/pkg/reconciler/resources/flow_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#507 Automatic release tag labels
  camel/source/config/100-namespace.yaml
  camel/source/config/200-serviceaccount.yaml
  camel/source/config/201-clusterrole.yaml
  camel/source/config/202-clusterrolebinding.yaml
  camel/source/config/300-camelsource.yaml
  camel/source/config/400-controller-service.yaml
  camel/source/config/500-controller.yaml
  hack/release.sh
  kafka/source/config/100-namespace.yaml
  kafka/source/config/200-serviceaccount.yaml
  kafka/source/config/201-clusterrole.yaml
  kafka/source/config/202-clusterrolebinding.yaml
  kafka/source/config/300-kafkasource.yaml
  kafka/source/config/400-controller-service.yaml
  kafka/source/config/500-controller.yaml
Labels: approved, cla: yes, lgtm, size/M

#511 move nats-approvers over from eventing
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#513 Updating pkg to latest for 0.9 work.
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/nats-io/nats.go/LICENSE
  vendor/github.com/nats-io/nats.go/context.go
  vendor/github.com/nats-io/nats.go/enc.go
  vendor/github.com/nats-io/nats.go/encoders/builtin/default_enc.go
  vendor/github.com/nats-io/nats.go/encoders/builtin/gob_enc.go
  vendor/github.com/nats-io/nats.go/encoders/builtin/json_enc.go
  vendor/github.com/nats-io/nats.go/nats.go
  vendor/github.com/nats-io/nats.go/netchan.go
  vendor/github.com/nats-io/nats.go/parser.go
  vendor/github.com/nats-io/nats.go/timer.go
  vendor/github.com/nats-io/nats.go/util/tls.go
  vendor/github.com/nats-io/nats.go/util/tls_go17.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/README.md
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/calculator.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/coveragedata.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/ignorefields.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/README.md
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/arraykindnode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/basictypekindnode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/node.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/otherkindnode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/ptrkindnode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/resourceforest.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/resourcetree.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/rule.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/structkindnode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/test_util.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/timetypenode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/tools/README.md
  vendor/knative.dev/pkg/test/webhook-apicoverage/tools/tools.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/README.md
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/html_display.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/rule.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/README.md
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/apicoverage_recorder.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/XXL

#520 Format markdown
  natss/config/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#516 release patch: renaming kafka to kafka importer, and adding CRD and CCP based channels
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#515 Remove kafka ccp
  Gopkg.lock
  hack/release.sh
  kafka/channel/cmd/controller/main.go
  kafka/channel/cmd/dispatcher/main.go
  kafka/channel/config/provisioner/README.md
  kafka/channel/config/provisioner/kafka.yaml
  vendor/github.com/knative/eventing/pkg/channelwatcher/channel_watcher.go
  vendor/github.com/knative/eventing/pkg/provisioners/swappable/swappable.go
Labels: approved, cla: yes, lgtm, size/XL

#522 renaming of release artifact
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#528 Fix NATS contrib.eventing.knative.dev/release labels
  kafka/channel/config/200-addressable-resolver-clusterrole.yaml
  natss/config/200-addressable-resolver-clusterrole.yaml
  natss/config/200-channelable-manipulator-clusterrole.yaml
  natss/config/200-controller-clusterrole.yaml
  natss/config/200-dispatcher-service.yaml
  natss/config/200-serviceaccount.yaml
  natss/config/201-clusterrolebinding.yaml
  natss/config/300-natss-channel.yaml
  natss/config/500-controller.yaml
  natss/config/500-dispatcher.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#524 Point Kafka to eventing-contrib, not the vendored dir for eventing.
  kafka/channel/config/500-controller.yaml
  kafka/channel/config/500-dispatcher.yaml
  kafka/channel/config/500-webhook.yaml
  kafka/channel/config/provisioner/kafka.yaml
Labels: approved, cla: yes, lgtm, size/S

#532 Format markdown
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#530 Reflecting the channel subfolder...
  kafka/channel/config/500-controller.yaml
  kafka/channel/config/500-dispatcher.yaml
  kafka/channel/config/500-webhook.yaml
  kafka/channel/config/provisioner/kafka.yaml
Labels: approved, cla: yes, lgtm, size/S

#531 Reflecting the channel subfolder...
  kafka/channel/config/500-controller.yaml
  kafka/channel/config/500-dispatcher.yaml
  kafka/channel/config/500-webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#536 generate injection
  Gopkg.lock
  awssqs/pkg/client/injection/client/client.go
  awssqs/pkg/client/injection/client/fake/fake.go
  awssqs/pkg/client/injection/informers/sources/factory/fake/fake.go
  awssqs/pkg/client/injection/informers/sources/factory/sourcesfactory.go
  awssqs/pkg/client/injection/informers/sources/v1alpha1/awssqssource/awssqssource.go
  awssqs/pkg/client/injection/informers/sources/v1alpha1/awssqssource/fake/fake.go
  camel/source/pkg/client/injection/client/client.go
  camel/source/pkg/client/injection/client/fake/fake.go
  camel/source/pkg/client/injection/informers/sources/factory/fake/fake.go
  camel/source/pkg/client/injection/informers/sources/factory/sourcesfactory.go
  camel/source/pkg/client/injection/informers/sources/v1alpha1/camelsource/camelsource.go
  camel/source/pkg/client/injection/informers/sources/v1alpha1/camelsource/fake/fake.go
  gcppubsub/pkg/client/injection/client/client.go
  gcppubsub/pkg/client/injection/client/fake/fake.go
  gcppubsub/pkg/client/injection/informers/sources/factory/fake/fake.go
  gcppubsub/pkg/client/injection/informers/sources/factory/sourcesfactory.go
  gcppubsub/pkg/client/injection/informers/sources/v1alpha1/gcppubsubsource/fake/fake.go
  gcppubsub/pkg/client/injection/informers/sources/v1alpha1/gcppubsubsource/gcppubsubsource.go
  github/pkg/client/injection/client/client.go
  github/pkg/client/injection/client/fake/fake.go
  github/pkg/client/injection/informers/sources/factory/fake/fake.go
  github/pkg/client/injection/informers/sources/factory/sourcesfactory.go
  github/pkg/client/injection/informers/sources/v1alpha1/githubsource/fake/fake.go
  github/pkg/client/injection/informers/sources/v1alpha1/githubsource/githubsource.go
  hack/update-codegen.sh
  kafka/source/pkg/client/injection/client/client.go
  kafka/source/pkg/client/injection/client/fake/fake.go
  kafka/source/pkg/client/injection/informers/sources/factory/fake/fake.go
  kafka/source/pkg/client/injection/informers/sources/factory/sourcesfactory.go
  kafka/source/pkg/client/injection/informers/sources/v1alpha1/kafkasource/fake/fake.go
  kafka/source/pkg/client/injection/informers/sources/v1alpha1/kafkasource/kafkasource.go
Labels: approved, cla: yes, lgtm, size/XS

#539 Don't ignore parsing errors
  github/cmd/receive_adapter/main.go
Labels: approved, cla: yes, lgtm, size/XS

#543 remove odd cmd/ double path ... but why does ko not complain...
  kafka/channel/config/500-controller.yaml
  kafka/channel/config/500-dispatcher.yaml
  kafka/channel/config/500-webhook.yaml
  kafka/channel/config/provisioner/kafka.yaml
Labels: approved, cla: yes, lgtm, size/S

#544 Add release tag labels to Kafka Channel objects [0.8]
  kafka/channel/config/200-addressable-resolver-clusterrole.yaml
  kafka/channel/config/200-channelable-manipulator-clusterrole.yaml
  kafka/channel/config/200-controller-clusterrole.yaml
  kafka/channel/config/200-dispatcher-clusterrole.yaml
  kafka/channel/config/200-dispatcher-service.yaml
  kafka/channel/config/200-serviceaccount.yaml
  kafka/channel/config/200-webhook-clusterrole.yaml
  kafka/channel/config/201-clusterrolebinding.yaml
  kafka/channel/config/300-kafka-channel.yaml
  kafka/channel/config/400-webhook-service.yaml
  kafka/channel/config/500-controller.yaml
  kafka/channel/config/500-dispatcher.yaml
  kafka/channel/config/500-webhook.yaml
  kafka/channel/config/provisioner/kafka.yaml
Labels: approved, cla: yes, lgtm, size/M

#545 Add release tag labels to Kafka Channel objects
  kafka/channel/config/200-channelable-manipulator-clusterrole.yaml
  kafka/channel/config/200-controller-clusterrole.yaml
  kafka/channel/config/200-dispatcher-clusterrole.yaml
  kafka/channel/config/200-dispatcher-service.yaml
  kafka/channel/config/200-serviceaccount.yaml
  kafka/channel/config/200-webhook-clusterrole.yaml
  kafka/channel/config/201-clusterrolebinding.yaml
  kafka/channel/config/300-kafka-channel.yaml
  kafka/channel/config/400-webhook-service.yaml
  kafka/channel/config/500-controller.yaml
  kafka/channel/config/500-dispatcher.yaml
  kafka/channel/config/500-webhook.yaml
Labels: approved, cla: yes, lgtm, size/M

#550 adding tests for TopicNames util
  Gopkg.lock
  kafka/channel/pkg/controller/channel/reconcile.go
  kafka/channel/pkg/controller/channel/reconcile_test.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
  kafka/channel/pkg/reconciler/controller/resources/topic.go
  kafka/channel/pkg/utils/util_test.go
  vendor/cloud.google.com/go/iam/iam.go
  vendor/cloud.google.com/go/internal/optional/optional.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/google.golang.org/genproto/googleapis/iam/v1/iam_policy.pb.go
  vendor/google.golang.org/genproto/googleapis/iam/v1/policy.pb.go
  vendor/google.golang.org/genproto/googleapis/pubsub/v1/pubsub.pb.go
  vendor/knative.dev/eventing/pkg/provisioners/utils/topic_names.go
Labels: approved, cla: yes, lgtm, size/XXL

#561 Fix scheme import paths.
  awssqs/pkg/apis/addtoscheme_sources_v1alpha1.go
  github/pkg/apis/addtoscheme_sources_v1alpha1.go
Labels: approved, cla: yes, lgtm, size/XS
