Repository knative/eventing-contrib, pull requests merged in 2019-10, with the labels that each got.

#637 Update DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#640 Stop skipping Broker Tests
  Gopkg.lock
  hack/set-span-id.patch
  test/e2e/broker_channel_flow_test.go
  test/e2e/broker_event_transformation_test.go
  vendor/go.opencensus.io/trace/trace.go
  vendor/knative.dev/eventing/pkg/tracing/traceparent.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#622 Update kafkasource to use knative.dev/pkg runtime
  Gopkg.lock
  kafka/channel/config/200-dispatcher-clusterrole.yaml
  kafka/source/cmd/controller/main.go
  kafka/source/config/500-controller.yaml
  kafka/source/config/config-observability.yaml
  kafka/source/pkg/apis/addtoscheme_eventing_v1alpha1.go
  kafka/source/pkg/apis/sources/register.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_lifecycle.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_lifecycle_test.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_types.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_types_test.go
  kafka/source/pkg/apis/sources/v1alpha1/register.go
  kafka/source/pkg/apis/sources/v1alpha1/register_test.go
  kafka/source/pkg/reconciler/controller.go
  kafka/source/pkg/reconciler/kafkasource.go
  kafka/source/pkg/reconciler/kafkasource_test.go
  kafka/source/pkg/reconciler/resources/eventtype.go
  kafka/source/pkg/reconciler/resources/eventtype_test.go
  kafka/source/pkg/reconciler/resources/labels.go
  kafka/source/pkg/reconciler/resources/labels_test.go
  kafka/source/pkg/reconciler/resources/receive_adapter.go
  vendor/knative.dev/pkg/kmeta/accessor.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/mako/stub-sidecar/main.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/testutils/clustermanager/client.go
  vendor/knative.dev/pkg/testutils/clustermanager/gke.go
  vendor/knative.dev/pkg/tracker/enqueue.go
Labels: approved, cla: yes, lgtm, size/XXL

#641 golang format tools
  kafka/source/cmd/controller/main.go
  kafka/source/pkg/reconciler/resources/labels_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#609 Add ClusterRole to get, list and watch sources in eventing-contrib
  awssqs/config/201-clusterrole.yaml
  camel/source/config/201-clusterrole.yaml
  github/config/201-clusterrole.yaml
  kafka/source/config/201-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/M

#646 Add ClusterRole to get, list and watch couchdb sources
  couchdb/source/config/201-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/S

#647 CE 0.3
  awssqs/pkg/adapter/adapter.go
  cmd/heartbeats/main.go
  cmd/websocketsource/main.go
  couchdb/source/pkg/adapter/adapter.go
  github/pkg/adapter/adapter.go
  github/pkg/adapter/adapter_test.go
  kafka/source/pkg/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/S

#648 Nicer rendering of kafkasource
  kafka/source/config/300-kafkasource.yaml
Labels: approved, cla: yes, lgtm, size/S

#649 hack/udpate-deps.sh removes OWNER_ALIASES.
  hack/update-deps.sh
  vendor/knative.dev/pkg/OWNERS_ALIASES
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#650 update eventing dep
  Gopkg.lock
  couchdb/source/pkg/reconciler/controller.go
  couchdb/source/pkg/reconciler/couchdbsource.go
  vendor/github.com/influxdata/tdigest/LICENSE
  vendor/github.com/influxdata/tdigest/centroid.go
  vendor/github.com/influxdata/tdigest/tdigest.go
  vendor/github.com/mailru/easyjson/LICENSE
  vendor/github.com/mailru/easyjson/buffer/pool.go
  vendor/github.com/mailru/easyjson/jlexer/bytestostr.go
  vendor/github.com/mailru/easyjson/jlexer/bytestostr_nounsafe.go
  vendor/github.com/mailru/easyjson/jlexer/error.go
  vendor/github.com/mailru/easyjson/jlexer/lexer.go
  vendor/github.com/mailru/easyjson/jwriter/writer.go
  vendor/github.com/tsenart/vegeta/LICENSE
  vendor/github.com/tsenart/vegeta/lib/attack.go
  vendor/github.com/tsenart/vegeta/lib/histogram.go
  vendor/github.com/tsenart/vegeta/lib/metrics.go
  vendor/github.com/tsenart/vegeta/lib/pacer.go
  vendor/github.com/tsenart/vegeta/lib/reporters.go
  vendor/github.com/tsenart/vegeta/lib/results.go
  vendor/github.com/tsenart/vegeta/lib/results_easyjson.go
  vendor/github.com/tsenart/vegeta/lib/targets.go
  vendor/github.com/tsenart/vegeta/lib/targets_easyjson.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/in_memory_channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/containersource_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/cron_job_types.go
  vendor/knative.dev/eventing/pkg/duck/listable.go
  vendor/knative.dev/eventing/pkg/duck/resource.go
  vendor/knative.dev/eventing/pkg/duck/subscriber.go
  vendor/knative.dev/eventing/pkg/kncloudevents/good_client.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/mock_resource_tracker.go
  vendor/knative.dev/eventing/pkg/tracing/names.go
  vendor/knative.dev/eventing/test/base/resource_inspectors.go
  vendor/knative.dev/eventing/test/base/resources/kube.go
  vendor/knative.dev/eventing/test/common/client.go
  vendor/knative.dev/eventing/test/common/cloudevents_vegeta_targeter.go
  vendor/knative.dev/eventing/test/common/creation.go
  vendor/knative.dev/eventing/test/common/operation.go
  vendor/knative.dev/eventing/test/common/tracker.go
  vendor/knative.dev/eventing/test/test_images/performance/kodata/dev.config
Labels: approved, cla: yes, lgtm, size/XXL

#652 Bump YAML library to latest release
  Gopkg.lock
  Gopkg.toml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
Labels: approved, cla: yes, lgtm, size/M

#651 couchdb uses shared adapter main
  Gopkg.lock
  couchdb/source/cmd/receive_adapter/main.go
  couchdb/source/pkg/adapter/adapter.go
  vendor/knative.dev/eventing/pkg/adapter/config.go
  vendor/knative.dev/eventing/pkg/adapter/main.go
Labels: approved, cla: yes, lgtm, size/L

#660 Fix for a race in a CouchDB source adapter test
  couchdb/source/pkg/adapter/adapter_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#665 minor cloudevents 1.0 updates
  couchdb/source/pkg/adapter/adapter.go
  kafka/source/pkg/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/XS

#662 refactor natss test logger
  natss/pkg/stanutil/stanutil_test.go
Labels: approved, cla: yes, lgtm, size/M

#671 Format markdown
  couchdb/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#674 Format markdown
  prometheus/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#675 Make our deepcopy-gen approach consistent with other repos.
  awssqs/pkg/apis/apis.go
  camel/source/pkg/apis/apis.go
  couchdb/source/pkg/apis/apis.go
  github/pkg/apis/apis.go
  hack/update-codegen.sh
  prometheus/pkg/apis/apis.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#676 Adding standard duck label on CRD to signal this resource adheres to Addressable
  kafka/channel/config/300-kafka-channel.yaml
  natss/config/300-natss-channel.yaml
Labels: approved, cla: yes, lgtm, size/XS

#677 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/test_helper.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/in_memory_channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/containersource_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/cron_job_types.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/v1alpha1/destination.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/gcp_metadata.go
  vendor/knative.dev/pkg/metrics/metricskey/constants_serving.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/README.md
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#679 Updating pkg to latest for 0.10 release.
  Gopkg.lock
  Gopkg.toml
  couchdb/source/cmd/webhook/main.go
  couchdb/source/config/500-webhook-configuration.yaml
  kafka/channel/cmd/webhook/main.go
  kafka/channel/config/500-webhook-configuration.yaml
  vendor/knative.dev/pkg/apis/duck/README.md
  vendor/knative.dev/pkg/webhook/config_validation_controller.go
  vendor/knative.dev/pkg/webhook/resource_admission_controller.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/L

#680 Upgrade Camel Sources to latest Camel K and Knative Eventing Specs
  Gopkg.lock
  Gopkg.toml
  camel/source/config/203-camel-source-observer-cluster-role.yaml
  camel/source/config/300-camelsource.yaml
  camel/source/pkg/apis/sources/v1alpha1/camelsource_types.go
  camel/source/pkg/apis/sources/v1alpha1/camelsource_types_test.go
  camel/source/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  camel/source/pkg/reconciler/camelsource.go
  camel/source/pkg/reconciler/camelsource_test.go
  camel/source/pkg/reconciler/resources/arguments.go
  camel/source/pkg/reconciler/resources/component.go
  camel/source/pkg/reconciler/resources/flow.go
  camel/source/pkg/reconciler/resources/flow_test.go
  camel/source/pkg/reconciler/resources/integration.go
  camel/source/pkg/reconciler/resources/integration_test.go
  camel/source/samples/README.md
  camel/source/samples/camel_source_hello_world.yaml
  camel/source/samples/display_resources.yaml
  camel/source/samples/source_camel_k.yaml
  camel/source/samples/source_telegram.yaml
  camel/source/samples/source_timer_flow.yaml
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/build_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/camelcatalog_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integration_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integration_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integrationkit_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integrationkit_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integrationplatform_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integrationplatform_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/knative/types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/knative/types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/register.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#687 Keep 2 sec period for continous mode
  couchdb/source/pkg/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/XS

#684 CouchDB sink now uses Destination
  Gopkg.lock
  couchdb/README.md
  couchdb/source/config/300-couchdbsource.yaml
  couchdb/source/pkg/apis/sources/v1alpha1/couchdbsource_lifecycle.go
  couchdb/source/pkg/apis/sources/v1alpha1/couchdbsource_lifecycle_test.go
  couchdb/source/pkg/apis/sources/v1alpha1/couchdbsource_types.go
  couchdb/source/pkg/apis/sources/v1alpha1/couchdbsource_validation.go
  couchdb/source/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  couchdb/source/pkg/reconciler/controller.go
  couchdb/source/pkg/reconciler/couchdbsource.go
  couchdb/source/pkg/reconciler/resources/eventtype.go
Labels: approved, cla: yes, lgtm, size/L

#685 golang format tools
  camel/source/pkg/reconciler/camelsource_test.go
  camel/source/pkg/reconciler/resources/flow.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#686 Format markdown
  camel/source/samples/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#688 Kafka src desitation
  kafka/source/README.md
  kafka/source/config/300-kafkasource.yaml
  kafka/source/pkg/apis/sources/v1alpha1/kafka_lifecycle.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_lifecycle_test.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_types.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_validation_test.go
  kafka/source/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  kafka/source/pkg/reconciler/controller.go
  kafka/source/pkg/reconciler/kafkasource.go
  kafka/source/pkg/reconciler/resources/eventtype.go
  kafka/source/pkg/reconciler/resources/eventtype_test.go
Labels: approved, cla: yes, lgtm, size/L

#690 add missing type
  couchdb/source/config/300-couchdbsource.yaml
  kafka/source/config/300-kafkasource.yaml
Labels: approved, cla: yes, lgtm, size/M

#696 golang format tools
  kafka/source/pkg/reconciler/kafkasource.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#697 Add vaikas to OWNERS via new account
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS
