Repository knative/eventing-contrib, pull requests merged in 2019-06, with the labels that each got.

#448 [RELEASE 0.5] Fix the CI flow error
  Gopkg.lock
  hack/update-deps.sh
  test/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/k8s.io/code-generator/Godeps/OWNERS
  vendor/k8s.io/code-generator/OWNERS
  vendor/k8s.io/code-generator/cmd/client-gen/OWNERS
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/OWNERS
Labels: approved, cla: yes, lgtm, size/L

#460 Fix #457: remove limits from camel controller manager
  contrib/camel/config/500-controller.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#462 Removing limits on Kafka controller
  contrib/kafka/config/500-controller.yaml
Labels: approved, cla: yes, lgtm, size/XS

#463 Format markdown
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#464 golang format tools
  contrib/kafka/pkg/reconciler/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#461 some updates on wrong repo name
  hack/release.md
  test/e2e_flags.go
Labels: approved, cla: yes, lgtm, size/XS

#459 Fix #458: upgrade to camel k 0.3.4
  Gopkg.lock
  Gopkg.toml
  contrib/camel/config/300-camelsource.yaml
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/build_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/camelcatalog_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/common_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/common_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/doc.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integration_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integration_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integrationcontext_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integrationplatform_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/knative/types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/register.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/apache/camel-k/pkg/util/util.go
  vendor/github.com/magiconair/properties/LICENSE
  vendor/github.com/magiconair/properties/decode.go
  vendor/github.com/magiconair/properties/doc.go
  vendor/github.com/magiconair/properties/integrate.go
  vendor/github.com/magiconair/properties/lex.go
  vendor/github.com/magiconair/properties/load.go
  vendor/github.com/magiconair/properties/parser.go
  vendor/github.com/magiconair/properties/properties.go
  vendor/github.com/magiconair/properties/rangecheck.go
  vendor/github.com/mitchellh/mapstructure/LICENSE
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/error.go
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/github.com/scylladb/go-set/LICENSE
  vendor/github.com/scylladb/go-set/strset/strset.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#467 golang format tools
  camel/source/pkg/reconciler/camelsource.go
  camel/source/pkg/reconciler/resources/context.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#469 Make eventSource and eventType to be flags
  cmd/heartbeats/main.go
Labels: approved, cla: yes, lgtm, size/S

#471 Removed the mistakenly added : in the last PR
  cmd/heartbeats/main.go
Labels: approved, cla: yes, lgtm, size/XS

#473 Add release labels to all objects
  config/tools/event-display/event-display.yaml
  contrib/awssqs/config/100-namespace.yaml
  contrib/awssqs/config/200-serviceaccount.yaml
  contrib/awssqs/config/201-clusterrole.yaml
  contrib/awssqs/config/202-clusterrolebinding.yaml
  contrib/awssqs/config/300-awssqssource.yaml
  contrib/awssqs/config/400-controller-service.yaml
  contrib/awssqs/config/500-controller.yaml
  contrib/awssqs/config/600-istioegress.yaml
  contrib/gcppubsub/config/100-namespace.yaml
  contrib/gcppubsub/config/200-serviceaccount.yaml
  contrib/gcppubsub/config/201-clusterrole.yaml
  contrib/gcppubsub/config/202-clusterrolebinding.yaml
  contrib/gcppubsub/config/300-gcppubsubsource.yaml
  contrib/gcppubsub/config/400-controller-service.yaml
  contrib/gcppubsub/config/500-controller.yaml
  contrib/gcppubsub/config/600-istioegress.yaml
  contrib/github/config/100-namespace.yaml
  contrib/github/config/200-serviceaccount.yaml
  contrib/github/config/201-clusterrole.yaml
  contrib/github/config/202-clusterrolebinding.yaml
  contrib/github/config/300-githubsource.yaml
  contrib/github/config/400-controller-service.yaml
  contrib/github/config/500-controller.yaml
Labels: approved, cla: yes, lgtm, size/M

#477 Porting sink change over from 'eventing core'
  camel/source/pkg/reconciler/camelsource_test.go
  contrib/gcppubsub/pkg/reconciler/gcppubsubsource_test.go
  contrib/github/pkg/reconciler/githubsource_test.go
  kafka/source/pkg/reconciler/kafkasource_test.go
  pkg/controller/sinks/sinks.go
  pkg/controller/sinks/sinks_test.go
Labels: approved, cla: yes, lgtm, size/S

#476 Unit test for status.address.hostname
  pkg/controller/sinks/sinks.go
  pkg/controller/sinks/sinks_test.go
Labels: approved, cla: yes, lgtm, size/S
