Repository knative/eventing-contrib, pull requests merged in 2019-11, with the labels that each got.

#705 Prometheus Source: added support for basic TLS configuration and authentication
  prometheus/README.md
  prometheus/config/300-prometheussource.yaml
  prometheus/demo/openshift-service-serving-signer-cabundle.yaml
  prometheus/demo/source_openshift.yaml
  prometheus/pkg/adapter/adapter.go
  prometheus/pkg/apis/sources/v1alpha1/prometheussource_types.go
  prometheus/pkg/reconciler/resources/receive_adapter.go
Labels: approved, cla: yes, lgtm, size/L

#707 Modified yamls to match eventing changes
  test/performance/broker-kafka/200-broker-perf.yaml
  test/performance/channel-kafka/100-channel-perf-setup.yaml
  test/performance/channel-kafka/101-channel-perf-setup.yaml
  test/performance/channel-kafka/200-channel-perf.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#700 Fix #694: use Destination in CamelSources
  Gopkg.lock
  camel/source/pkg/apis/sources/v1alpha1/camelsource_types.go
  camel/source/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  camel/source/pkg/reconciler/camelsource.go
  camel/source/pkg/reconciler/camelsource_test.go
  camel/source/pkg/reconciler/resources/arguments.go
  camel/source/pkg/reconciler/resources/integration.go
  camel/source/pkg/reconciler/resources/integration_test.go
  camel/source/samples/camel_source_hello_world.yaml
  couchdb/source/pkg/apis/sources/v1alpha1/couchdbsource_lifecycle.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_lifecycle.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#703 Bug revise of MutatingWebhookName mismatching
  kafka/channel/cmd/webhook/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#708 KafkaSource uses shared Adapter.Main
  kafka/source/cmd/receive_adapter/main.go
  kafka/source/pkg/adapter/adapter.go
  kafka/source/pkg/adapter/adapter_benchmark_test.go
  kafka/source/pkg/adapter/adapter_test.go
  kafka/source/pkg/reconciler/controller.go
  kafka/source/pkg/reconciler/kafkasource.go
  kafka/source/pkg/reconciler/resources/receive_adapter.go
Labels: approved, cla: yes, lgtm, size/L

#713 Add Ready column to GithubSource
  github/config/300-githubsource.yaml
Labels: approved, cla: yes, lgtm, size/XS

#711 Use Destination in Prometheus source
  Gopkg.lock
  prometheus/README.md
  prometheus/config/300-prometheussource.yaml
  prometheus/demo/source.yaml
  prometheus/demo/source_openshift.yaml
  prometheus/pkg/apis/sources/v1alpha1/prometheussource_lifecycle.go
  prometheus/pkg/apis/sources/v1alpha1/prometheussource_lifecycle_test.go
  prometheus/pkg/apis/sources/v1alpha1/prometheussource_types.go
  prometheus/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  prometheus/pkg/reconciler/controller.go
  prometheus/pkg/reconciler/prometheussource.go
  prometheus/pkg/reconciler/resources/eventtype.go
  vendor/knative.dev/eventing/pkg/duck/listable.go
  vendor/knative.dev/eventing/pkg/duck/sinks.go
  vendor/knative.dev/eventing/pkg/duck/subscriber.go
Labels: approved, cla: yes, lgtm, size/XL

#715 remove vaikas-google in favor of vaikas
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#716 Kafka channel refactor to use sharedmain
  Gopkg.lock
  kafka/channel/cmd/channel_controller/main.go
  kafka/channel/cmd/channel_dispatcher/main.go
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/controller/kafkachannel_test.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  kafka/channel/pkg/reconciler/reconciler.go
  kafka/channel/pkg/reconciler/testing/factory.go
  kafka/channel/pkg/reconciler/testing/listers.go
Labels: approved, cla: yes, lgtm, size/XXL

#701 Pull in the latest knative/pkg, incl. webhook refactor.
  Gopkg.lock
  Gopkg.toml
  couchdb/source/cmd/webhook/main.go
  couchdb/source/config/500-webhook-configuration.yaml
  couchdb/source/config/500-webhook.yaml
  couchdb/source/pkg/apis/sources/v1alpha1/couchdbsource_validation_test.go
  kafka/channel/cmd/webhook/main.go
  kafka/channel/config/500-webhook-configuration.yaml
  kafka/channel/config/500-webhook.yaml
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_types.go
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_validation_test.go
  natss/pkg/apis/messaging/v1alpha1/natss_channel_types.go
  natss/pkg/apis/messaging/v1alpha1/natss_channel_validation_test.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/RELEASING.md
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1beta1/mutatingwebhookconfiguration/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1beta1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1beta1/validatingwebhookconfiguration/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1beta1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/clients/dynamicclient/dynamicclient.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/test/junit/junit.go
  vendor/knative.dev/pkg/test/mako/alerter/slack/message.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/test/slackutil/message_read.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/apicoverage_recorder.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/webhook.go
  vendor/knative.dev/pkg/webhook/README.md
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/pkg/webhook/certificates/resources/secret.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/context.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/resourcesemantics.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/user_info.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/testing/factory.go
  vendor/knative.dev/pkg/webhook/testing/listers.go
  vendor/knative.dev/pkg/webhook/testing/testing.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/XXL

#719 Prometheus source: moved loop-invariant code out of the adapter request loop
  prometheus/pkg/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/M

#722 Format markdown
  prometheus/README.md
  test/test_images/kafka_performance/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#723 golang format tools
  kafka/channel/pkg/reconciler/controller/kafkachannel_test.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  kafka/source/pkg/adapter/adapter.go
  kafka/source/pkg/adapter/adapter_benchmark_test.go
  kafka/source/pkg/adapter/adapter_test.go
  kafka/source/pkg/reconciler/controller.go
  kafka/source/pkg/reconciler/kafkasource.go
  test/test_images/kafka_performance/kafka_load_generator.go
  test/test_images/kafka_performance/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#725 Update vendor/knative.dev/test-infra
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/M

#727 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hack/verify-codegen.sh
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/test/gke/client.go
  vendor/knative.dev/pkg/tracker/doc.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/networking/register.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_accessors.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_conversion.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/knative.dev/serving/pkg/reconciler/revision/config/testdata/config-defaults.yaml
  vendor/knative.dev/serving/test/performance/benchmarks/dataplane-probe/continuous/kodata/HEAD
  vendor/knative.dev/serving/test/performance/benchmarks/dataplane-probe/continuous/kodata/dev.config
  vendor/knative.dev/serving/test/performance/benchmarks/dataplane-probe/continuous/kodata/prod.config
  vendor/knative.dev/serving/test/performance/benchmarks/dataplane-probe/continuous/kodata/refs
  vendor/knative.dev/serving/test/performance/benchmarks/deployment-probe/continuous/kodata/HEAD
  vendor/knative.dev/serving/test/performance/benchmarks/deployment-probe/continuous/kodata/dev.config
  vendor/knative.dev/serving/test/performance/benchmarks/deployment-probe/continuous/kodata/prod.config
  vendor/knative.dev/serving/test/performance/benchmarks/deployment-probe/continuous/kodata/refs
  vendor/knative.dev/serving/test/performance/benchmarks/load-test/continuous/kodata/HEAD
  vendor/knative.dev/serving/test/performance/benchmarks/load-test/continuous/kodata/dev.config
  vendor/knative.dev/serving/test/performance/benchmarks/load-test/continuous/kodata/prod.config
  vendor/knative.dev/serving/test/performance/benchmarks/load-test/continuous/kodata/refs
  vendor/knative.dev/serving/test/performance/benchmarks/scale-from-zero/continuous/kodata/HEAD
  vendor/knative.dev/serving/test/performance/benchmarks/scale-from-zero/continuous/kodata/dev.config
  vendor/knative.dev/serving/test/performance/benchmarks/scale-from-zero/continuous/kodata/prod.config
  vendor/knative.dev/serving/test/performance/benchmarks/scale-from-zero/continuous/kodata/refs
Labels: approved, cla: yes, lgtm, size/XL

#726 golang format tools
  test/config.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#730 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/webhook/README.md
Labels: approved, cla: yes, lgtm, size/M

#734 Always upload test images from vendor
  hack/update-deps.sh
  hack/update-image-paths.patch
  test/e2e-tests.sh
  vendor/knative.dev/eventing/test/test_images/logevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/sendevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/transformevents/pod.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#736 Split the Defaulting and Validation webhook.
  Gopkg.lock
  couchdb/source/cmd/webhook/main.go
  couchdb/source/config/500-webhook-configuration.yaml
  kafka/channel/cmd/webhook/main.go
  kafka/channel/config/500-webhook-configuration.yaml
  kafka/source/pkg/apis/sources/v1alpha1/kafka_types.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_validation.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_validation_test.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtype_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/channel_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/trigger.go
  vendor/knative.dev/eventing/test/base/resources/eventing.go
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/testing/resource.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/interface.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/XL

#737 Prometheus source: added an example for Knative Monitoring
  prometheus/README.md
  prometheus/demo/source_knative.yaml
Labels: approved, cla: yes, lgtm, size/L

#728 Update knative.dev/eventing.
  Gopkg.lock
  Gopkg.toml
  test/config.go
  test/e2e-tests.sh
  test/e2e/main_test.go
  vendor/knative.dev/eventing/cmd/apiserver_receive_adapter/kodata/HEAD
  vendor/knative.dev/eventing/cmd/apiserver_receive_adapter/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/apiserver_receive_adapter/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/apiserver_receive_adapter/kodata/refs
  vendor/knative.dev/eventing/cmd/cronjob_receive_adapter/kodata/HEAD
  vendor/knative.dev/eventing/cmd/cronjob_receive_adapter/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/cronjob_receive_adapter/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/cronjob_receive_adapter/kodata/refs
  vendor/knative.dev/eventing/cmd/in_memory/channel_controller/kodata/HEAD
  vendor/knative.dev/eventing/cmd/in_memory/channel_controller/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/in_memory/channel_controller/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/in_memory/channel_controller/kodata/refs
  vendor/knative.dev/eventing/cmd/in_memory/channel_dispatcher/kodata/HEAD
  vendor/knative.dev/eventing/cmd/in_memory/channel_dispatcher/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/in_memory/channel_dispatcher/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/in_memory/channel_dispatcher/kodata/refs
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/trigger.go
  vendor/knative.dev/eventing/test/common/config.go
  vendor/knative.dev/eventing/test/common/test_runner.go
  vendor/knative.dev/eventing/test/common/typemeta.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_chain_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go
  vendor/knative.dev/eventing/test/e2e_flags.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#741 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/pkg/adapter/main.go
  vendor/knative.dev/eventing/test/common/performance/event_state/event_state.pb.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
Labels: approved, cla: yes, lgtm, size/M

#739 Prometheus Source: added an example of event filtering with Triggers
  prometheus/README.md
  prometheus/demo/broker_trigger.yaml
  prometheus/pkg/reconciler/prometheussource.go
Labels: approved, cla: yes, lgtm, size/L

#743 Microbenchmarks for kafka dispatcher
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_benchmark_test.go
  kafka/common/pkg/kafka/consumer_handler.go
Labels: approved, cla: yes, lgtm, size/L

#742 Perf test improvements
  kafka/common/pkg/kafka/consumer_handler.go
  test/performance/broker-kafka/100-broker-perf-setup.yaml
  test/performance/channel-kafka/100-channel-perf-setup.yaml
  test/performance/channel-kafka/200-channel-perf.yaml
  test/performance/source-kafka/100-source-perf-setup.yaml
  test/test_images/kafka_performance/kafka_load_generator.go
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/L

#744 golang format tools
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_benchmark_test.go
Labels: approved, cla: yes, lgtm, size/S

#745 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/networking/register.go
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/L

#712 Bug revise of MutatingWebhookName mismatching
  kafka/channel/cmd/webhook/main.go
Labels: approved, cla: yes, lgtm, size/XS

#746 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/pkg/websocket/connection.go
Labels: approved, cla: yes, lgtm, size/S

#718 Backport usage of Destination in CamelSource (#700) to release-0.10 b…
  Gopkg.lock
  camel/source/pkg/apis/sources/v1alpha1/camelsource_types.go
  camel/source/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  camel/source/pkg/reconciler/camelsource.go
  camel/source/pkg/reconciler/camelsource_test.go
  camel/source/pkg/reconciler/resources/arguments.go
  camel/source/pkg/reconciler/resources/integration.go
  camel/source/pkg/reconciler/resources/integration_test.go
  camel/source/samples/camel_source_hello_world.yaml
  couchdb/source/pkg/apis/sources/v1alpha1/couchdbsource_lifecycle.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_lifecycle.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#749 Follow-up: service ports name following istio-naming convention
  awssqs/config/400-controller-service.yaml
  camel/source/config/400-controller-service.yaml
  couchdb/source/config/400-controller-service.yaml
  couchdb/source/config/400-webhook-service.yaml
  github/config/400-controller-service.yaml
  kafka/channel/config/200-dispatcher-service.yaml
  kafka/channel/config/400-webhook-service.yaml
  kafka/source/config/400-controller-service.yaml
  natss/config/200-dispatcher-service.yaml
  natss/config/broker/natss.yaml
  prometheus/config/400-controller-service.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#750 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/test/base/resources/eventing.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/test/cmd/command.go
Labels: approved, cla: yes, lgtm, size/L

#755 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/rogpeppe/fastuuid/LICENSE
  vendor/github.com/rogpeppe/fastuuid/uuid.go
  vendor/knative.dev/eventing/pkg/adapter/main.go
  vendor/knative.dev/eventing/test/common/performance/aggregator/aggregator.go
  vendor/knative.dev/eventing/test/common/performance/common/constants.go
  vendor/knative.dev/eventing/test/common/performance/common/executor.go
  vendor/knative.dev/eventing/test/common/performance/image_helpers.go
  vendor/knative.dev/eventing/test/common/performance/receiver/receiver.go
  vendor/knative.dev/eventing/test/common/performance/sender/http_load_generator.go
  vendor/knative.dev/eventing/test/common/performance/sender/sender.go
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/test/mako/stub-sidecar/main.go
  vendor/knative.dev/pkg/test/mako/stub-sidecar/read_results.sh
  vendor/knative.dev/serving/third_party/istio-1.3-latest
Labels: approved, cla: yes, lgtm, size/XL

#760 Remove vestigial listers for istio
  Gopkg.lock
  kafka/channel/pkg/reconciler/testing/listers.go
  natss/pkg/reconciler/testing/listers.go
Labels: approved, cla: yes, lgtm, size/S

#762 Use Namespace and name on kafka consumer group
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/M

#764 Trigger NatssChannel reconciliation in case of errors
  natss/pkg/reconciler/dispatcher/natsschannel.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#763 Trigger NatssChannel reconciliation in case of errors
  natss/pkg/reconciler/dispatcher/natsschannel.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#765 golang format tools
  kafka/channel/pkg/dispatcher/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/XS
