Repository knative/eventing-contrib, pull requests merged in 2019-02, with the labels that each got.

#198 Move cronjobsource to knative/serving style reconcile directory structures.
  pkg/controller/add_cronjobsources.go
  pkg/controller/cronjobsource/provider.go
  pkg/reconciler/cronjobsource/cronjobsource.go
  pkg/reconciler/cronjobsource/cronjobsource_test.go
  pkg/reconciler/cronjobsource/doc.go
  pkg/reconciler/cronjobsource/resources/receive_adapter.go
  pkg/reconciler/cronjobsource/resources/receive_adapter_test.go
Labels: approved, lgtm, size/L

#201 golang format tools
  cmd/cronjob_receive_adapter/main.go
  cmd/heartbeats/main.go
  cmd/websocketsource/main.go
  pkg/adapter/cronjobevents/adapter.go
  pkg/adapter/cronjobevents/adapter_test.go
  pkg/adapter/github/adapter.go
  pkg/adapter/github/adapter_test.go
  pkg/adapter/kubernetesevents/adapter.go
  pkg/reconciler/cronjobsource/cronjobsource.go
Labels: approved, lgtm, needs-ok-to-test, size/M

#199 Move remaining reconcilers to new structure.
  contrib/gcppubsub/cmd/controller/main.go
  contrib/gcppubsub/pkg/controller/doc.go
  contrib/gcppubsub/pkg/controller/provider.go
  contrib/gcppubsub/pkg/reconciler/doc.go
  contrib/gcppubsub/pkg/reconciler/gcppubsubsource.go
  contrib/gcppubsub/pkg/reconciler/gcppubsubsource_test.go
  contrib/gcppubsub/pkg/reconciler/pubsub_wrapper.go
  contrib/gcppubsub/pkg/reconciler/pubsub_wrapper_test.go
  contrib/gcppubsub/pkg/reconciler/resources/receive_adapter.go
  contrib/gcppubsub/pkg/reconciler/resources/receive_adapter_test.go
  pkg/controller/add_awssqssources.go
  pkg/controller/add_containersources.go
  pkg/controller/add_githubsource.go
  pkg/controller/awssqssource/provider.go
  pkg/controller/containersource/provider.go
  pkg/controller/githubsource/provider.go
  pkg/controller/kuberneteseventsource/provider.go
  pkg/reconciler/awssqssource/awssqssource.go
  pkg/reconciler/awssqssource/doc.go
  pkg/reconciler/awssqssource/resources/receive_adapter.go
  pkg/reconciler/containersource/containersource.go
  pkg/reconciler/containersource/containersource_test.go
  pkg/reconciler/containersource/doc.go
  pkg/reconciler/containersource/resources/arguments.go
  pkg/reconciler/containersource/resources/deployment.go
  pkg/reconciler/containersource/resources/deployment_test.go
  pkg/reconciler/githubsource/doc.go
  pkg/reconciler/githubsource/githubsource.go
  pkg/reconciler/githubsource/githubsource_test.go
  pkg/reconciler/githubsource/resources/service.go
  pkg/reconciler/githubsource/webhook_client.go
  pkg/reconciler/kuberneteseventsource/doc.go
  pkg/reconciler/kuberneteseventsource/kuberneteseventsource.go
  pkg/reconciler/kuberneteseventsource/resources/containersource.go
  pkg/reconciler/kuberneteseventsource/resources/containersource_test.go
Labels: approved, lgtm, size/XL

#205 golang format tools
  pkg/reconciler/awssqssource/awssqssource.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#189 Customize markdown checks
  test/markdown-lint-config.rc
Labels: approved, lgtm, size/XS

#212 Remove usage of K8S_CLUSTER_OVERRIDE and friends
  test/README.md
  test/e2e-tests.sh
  test/upload-test-images.sh
Labels: approved, lgtm, size/S

#209 Upgrade `knative/pkg` to latest
  Gopkg.lock
  Gopkg.toml
  cmd/heartbeats_receiver/main.go
  contrib/gcppubsub/pkg/adapter/adapter.go
  pkg/adapter/github/adapter_test.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/apis/interfaces.go
  vendor/github.com/knative/pkg/cloudevents/builder.go
  vendor/github.com/knative/pkg/cloudevents/encoding_binary.go
  vendor/github.com/knative/pkg/cloudevents/encoding_structured.go
  vendor/github.com/knative/pkg/cloudevents/event.go
  vendor/github.com/knative/pkg/cloudevents/event_v01.go
  vendor/github.com/knative/pkg/cloudevents/event_v02.go
  vendor/github.com/knative/pkg/cloudevents/handler.go
  vendor/github.com/knative/pkg/logging/config.go
Labels: approved, lgtm, size/XL

#221 Format markdown
  samples/heartbeats/README.md
  test/README.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#222 Updated the CloudEvent SDK, down-streaming those changes.
  Gopkg.lock
  Gopkg.toml
  cmd/heartbeats/main.go
  cmd/heartbeats_receiver/main.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/client.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/client_http.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/client_nats.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/context.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/options.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/nats/codec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/nats/transport.go
Labels: approved, lgtm, size/L

#219 Modify github source to add ability to specify api url for GHE
  pkg/apis/sources/v1alpha1/githubsource_types.go
  pkg/reconciler/githubsource/githubsource.go
  pkg/reconciler/githubsource/githubsource_test.go
  pkg/reconciler/githubsource/webhook_client.go
Labels: approved, lgtm, size/L

#215 Update k8s source to new version of cloudevents sdk
  pkg/adapter/kubernetesevents/adapter.go
  pkg/adapter/kubernetesevents/cloudevent.go
  pkg/adapter/kubernetesevents/cloudevent_test.go
Labels: approved, lgtm, size/M

#224 Update cloudevent sdk to include auto-generated uuid options.
  Gopkg.lock
  Gopkg.toml
  cmd/heartbeats/main.go
  cmd/heartbeats_receiver/main.go
  pkg/adapter/kubernetesevents/adapter.go
  pkg/adapter/kubernetesevents/cloudevent_test.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/client.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/defaulters.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/options.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/codec/jsoncodec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/content_type.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v01.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v02.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v01.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v02.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v03.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/encoding.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go
Labels: approved, lgtm, size/XL
