Repository knative/eventing-contrib, pull requests merged in 2019-04, with the labels that each got.

#322 Removing inner claim goroutine
  contrib/kafka/pkg/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/S

#329 Stop making sensitive kafka information available for logging
  contrib/kafka/cmd/receive_adapter/main.go
  contrib/kafka/pkg/adapter/adapter.go
  contrib/kafka/samples/README.md
Labels: approved, cla: yes, lgtm, size/S

#326 Documentation: Add example internal kafka cluster to README
  contrib/kafka/samples/README.md
  contrib/kafka/samples/kafka-topic.yaml
Labels: approved, cla: yes, lgtm, size/M

#333 Revert "Make upload test images simpler"
  test/upload-test-images.sh
Labels: approved, cla: yes, lgtm, size/S

#334 Remove message dumper.
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#315 Address function and variable naming lint errors
  pkg/adapter/awssqs/adapter_test.go
  pkg/controller/sinks/sinks_test.go
  pkg/reconciler/containersource/containersource_test.go
  pkg/reconciler/githubsource/githubsource_test.go
Labels: approved, cla: yes, lgtm, size/M

#309 Add check_suite events added to githubsource types
  Gopkg.lock
  cmd/github_receive_adapter/main.go
  config/300-githubsource.yaml
  pkg/adapter/github/adapter.go
  pkg/adapter/github/adapter_test.go
  pkg/apis/sources/v1alpha1/githubsource_types.go
  vendor/gopkg.in/go-playground/webhooks.v3/github/github.go
  vendor/gopkg.in/go-playground/webhooks.v3/logger.go
  vendor/gopkg.in/go-playground/webhooks.v3/webhooks.go
  vendor/gopkg.in/go-playground/webhooks.v5/LICENSE
  vendor/gopkg.in/go-playground/webhooks.v5/github/github.go
  vendor/gopkg.in/go-playground/webhooks.v5/github/payload.go
  vendor/gopkg.in/go-playground/webhooks.v5/testdata/docker/docker_hub_build_notice.json
Labels: approved, cla: yes, lgtm, size/XXL

#338 Format markdown
  contrib/kafka/samples/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#348 Updating test-infra using dep update
  Gopkg.lock
  third_party/VENDOR-LICENSE
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#346 Updated README.md
  contrib/kafka/samples/README.md
Labels: approved, cla: yes, lgtm, size/XS

#301 Update Kafka consumer group error message
  contrib/kafka/pkg/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/XS

#347 Update README.md
  contrib/kafka/samples/README.md
Labels: approved, cla: yes, lgtm, size/XS

#350 Format markdown
  contrib/kafka/samples/README.md
Labels: approved, cla: yes, lgtm, size/XS

#327 Use addressable-resolver aggregated clusterrole
  config/201-clusterrole.yaml
  config/202-clusterrolebinding.yaml
  contrib/gcppubsub/config/201-clusterrole.yaml
  contrib/gcppubsub/config/202-clusterrolebinding.yaml
Labels: approved, cla: yes, lgtm, size/M

#356 Format markdown
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/S

#303 Kafka source image policy
  contrib/kafka/config/500-controller.yaml
  contrib/kafka/pkg/reconciler/resources/receive_adapter.go
  contrib/kafka/pkg/reconciler/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/S

#355 golang format tools
  contrib/gcppubsub/pkg/apis/sources/v1alpha1/gcp_pubsub_validation.go
  contrib/kafka/pkg/apis/sources/v1alpha1/kafka_validation.go
Labels: approved, cla: yes, lgtm, size/XS

#317 Check required parameters for kafka source
  contrib/kafka/config/300-kafkasource.yaml
Labels: approved, cla: yes, lgtm, size/XS

#357 Missing RBAC rules for finalizers
  config/201-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/S

#361 golang format tools
  cmd/event_display/main.go
Labels: approved, cla: yes, lgtm, size/XS

#360 Update event-sources to not use fallback logger
  cmd/manager/main.go
  contrib/camel/cmd/controller/main.go
  contrib/camel/pkg/reconciler/camelsource.go
  contrib/gcppubsub/cmd/controller/main.go
  contrib/gcppubsub/pkg/reconciler/gcppubsubsource.go
  contrib/kafka/cmd/controller/main.go
  contrib/kafka/cmd/receive_adapter/main.go
  contrib/kafka/pkg/adapter/adapter.go
  contrib/kafka/pkg/reconciler/kafkasource.go
  contrib/kafka/samples/README.md
  pkg/controller/controller.go
  pkg/controller/sdk/provider.go
  pkg/controller/sdk/reconciler.go
  pkg/reconciler/awssqssource/awssqssource.go
  pkg/reconciler/containersource/containersource.go
  pkg/reconciler/cronjobsource/cronjobsource.go
  pkg/reconciler/githubsource/githubsource.go
  pkg/reconciler/kuberneteseventsource/kuberneteseventsource.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#359 update test-infra: allow handling stock out with retries
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M

#365 Fixing address in GitHub Receive Adapter
  cmd/github_receive_adapter/main.go
Labels: approved, cla: yes, lgtm, size/XS

#362 use cloudevent alias pkg
  pkg/kncloudevents/good_client.go
Labels: approved, cla: yes, lgtm, size/S

#186 Record more detail about ContainerSource reconcile
  pkg/apis/sources/v1alpha1/containersource_types.go
  pkg/apis/sources/v1alpha1/containersource_types_test.go
  pkg/reconciler/containersource/containersource.go
  pkg/reconciler/containersource/containersource_test.go
Labels: approved, cla: yes, lgtm, size/L

#369 fix owerReferences setup in ApiServer receiver
  contrib/apiserver/config/300-apiserversource.yaml
  contrib/apiserver/pkg/adapter/adapter.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#367 Update k8s test image, sdk now blocks on receive
  test/test_images/k8sevents/function.go
Labels: approved, cla: yes, lgtm, size/XS

#368 Delete moved CronJobSource.
  DEVELOPMENT.md
  Gopkg.lock
  cmd/cronjob_receive_adapter/main.go
  config/201-clusterrole.yaml
  config/300-cronjobsource.yaml
  config/500-controller.yaml
  pkg/adapter/cronjobevents/adapter.go
  pkg/adapter/cronjobevents/adapter_test.go
  pkg/apis/sources/v1alpha1/cron_job_types.go
  pkg/apis/sources/v1alpha1/cron_job_types_test.go
  pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/sources/v1alpha1/cronjobsource.go
  pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_cronjobsource.go
  pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_sources_client.go
  pkg/client/clientset/versioned/typed/sources/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/sources/v1alpha1/sources_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/sources/v1alpha1/cronjobsource.go
  pkg/client/informers/externalversions/sources/v1alpha1/interface.go
  pkg/client/listers/sources/v1alpha1/cronjobsource.go
  pkg/client/listers/sources/v1alpha1/expansion_generated.go
  pkg/controller/add_cronjobsources.go
  pkg/reconciler/cronjobsource/cronjobsource.go
  pkg/reconciler/cronjobsource/cronjobsource_test.go
  pkg/reconciler/cronjobsource/doc.go
  pkg/reconciler/cronjobsource/resources/receive_adapter.go
  pkg/reconciler/cronjobsource/resources/receive_adapter_test.go
  third_party/VENDOR-LICENSE
  vendor/github.com/robfig/cron/LICENSE
  vendor/github.com/robfig/cron/constantdelay.go
  vendor/github.com/robfig/cron/cron.go
  vendor/github.com/robfig/cron/doc.go
  vendor/github.com/robfig/cron/parser.go
  vendor/github.com/robfig/cron/spec.go
Labels: approved, cla: yes, lgtm, size/XXL

#384 golang format tools
  contrib/apiserver/pkg/adapter/adapter_test.go
  contrib/apiserver/pkg/controller/apiserversource/apiserversource_controller_test.go
  contrib/apiserver/pkg/controller/apiserversource/resources/receive_adapter_test.go
  pkg/kncloudevents/good_client.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#383 Format markdown
  DEVELOPMENT.md
  contrib/apiserver/samples/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
