Repository knative/eventing-contrib, pull requests merged in 2019-12, with the labels that each got.

#766 Use K_SINK for where to send events.
  cmd/heartbeats/main.go
Labels: approved, cla: yes, lgtm, size/S

#767 CamelSource unit test fix
  camel/source/pkg/reconciler/camelsource_test.go
Labels: approved, cla: yes, lgtm, size/XS

#759 Kafkasource e2e test
  Gopkg.lock
  Gopkg.toml
  hack/update-deps.sh
  hack/update-image-paths.patch
  kafka/source/pkg/adapter/adapter.go
  test/base/resources/kafka.go
  test/common/creation.go
  test/config/100-kafka-persistent-single-2.3.0.yaml
  test/config/100-kafka-topic.yaml
  test/config/100-strimzi-cluster-operator-0.11.4.yaml
  test/config/100-strimzi-cluster-operator-0.14.0.yaml
  test/e2e-tests.sh
  test/e2e/kafka_source_test.go
  test/test_images/kafka_performance/kafka_load_generator.go
  test/test_images/kafka_performance/pod.yaml
  vendor/github.com/slinkydeveloper/loadastic/kafka/gen-loadastic.go
  vendor/github.com/slinkydeveloper/loadastic/kafka/sender.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_context.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/containersource.go
  vendor/knative.dev/eventing/test/common/creation.go
  vendor/knative.dev/eventing/test/test_images/performance/README.md
  vendor/knative.dev/eventing/test/test_images/performance/kodata/HEAD
  vendor/knative.dev/eventing/test/test_images/performance/kodata/refs
  vendor/knative.dev/eventing/test/test_images/performance/main.go
  vendor/knative.dev/eventing/test/test_images/performance/mako.config
  vendor/knative.dev/eventing/test/test_images/performance/pod.yaml
  vendor/knative.dev/pkg/apis/duck/const.go
  vendor/knative.dev/pkg/apis/duck/interface.go
  vendor/knative.dev/pkg/apis/duck/unstructured.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/testing/duck/doc.go
  vendor/knative.dev/pkg/testing/duck/register.go
  vendor/knative.dev/pkg/testing/duck/testbindable.go
  vendor/knative.dev/pkg/testing/duck/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/webhook/psbinding/README.md
  vendor/knative.dev/pkg/webhook/psbinding/controller.go
  vendor/knative.dev/pkg/webhook/psbinding/doc.go
  vendor/knative.dev/pkg/webhook/psbinding/index.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/pkg/webhook/testing/listers.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#771 Adding Lukas as approver for modules where he did write code
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#773 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_context.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/channel/event_dispatcher.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/containersource.go
  vendor/knative.dev/eventing/test/common/creation.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/const.go
  vendor/knative.dev/pkg/apis/duck/interface.go
  vendor/knative.dev/pkg/apis/duck/unstructured.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/testing/duck/doc.go
  vendor/knative.dev/pkg/testing/duck/register.go
  vendor/knative.dev/pkg/testing/duck/testbindable.go
  vendor/knative.dev/pkg/testing/duck/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/webhook/psbinding/README.md
  vendor/knative.dev/pkg/webhook/psbinding/controller.go
  vendor/knative.dev/pkg/webhook/psbinding/doc.go
  vendor/knative.dev/pkg/webhook/psbinding/index.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/pkg/webhook/testing/listers.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XXL

#774 Updating pkg to latest for 0.11 release.
  Gopkg.lock
  Gopkg.toml
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics_batcher.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics_proto.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics_test_utils.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/aws_identity_doc_utils.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/gcp_metadata_config.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/resource.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stackdriver.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stats.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/trace.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/monitored_resources_eventing.go
  vendor/knative.dev/pkg/metrics/monitored_resources_serving.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
Labels: approved, cla: yes, lgtm, size/XXL

#781 Update source to produce 1.0 data
  awssqs/pkg/adapter/adapter.go
  cmd/heartbeats/main.go
  cmd/websocketsource/main.go
  couchdb/source/pkg/adapter/adapter.go
  github/pkg/adapter/adapter.go
  github/pkg/adapter/adapter_test.go
  kafka/source/pkg/adapter/adapter.go
  prometheus/pkg/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/M

#778 add ceph bucket notification adapter to knative
  ceph/README.md
  ceph/cmd/receive_adapter/main.go
  ceph/pkg/adapter/adapter.go
  ceph/pkg/adapter/adapter_test.go
  ceph/pkg/apis/v1alpha1/bucket_notification_types.go
  ceph/samples/ceph-bucket-notification-svc.yaml
  ceph/samples/ceph-container-source.yaml
  ceph/samples/ceph-display-resources.yaml
  ceph/samples/ceph-eventing-ns.yaml
  ceph/samples/records.json
  ceph/samples/test-pod.yaml
  hack/update-deps.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XL

#785 Format markdown
  ceph/README.md
Labels: approved, cla: yes, lgtm, size/M

#786 golang format tools
  ceph/cmd/receive_adapter/main.go
  ceph/pkg/adapter/adapter.go
  ceph/pkg/adapter/adapter_test.go
  github/pkg/adapter/adapter_test.go
  kafka/source/pkg/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/S

#788 KafkaChannel Dispatcher Refactor to use CloudEvents
  Gopkg.lock
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_benchmark_test.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  pkg/channel/message_dispatcher.go
  pkg/channel/message_receiver.go
  vendor/knative.dev/eventing/pkg/channel/swappable/swappable.go
Labels: approved, cla: yes, lgtm, size/L

#795 updating approver list
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#797 Update to latest pkg and eventing
  Gopkg.lock
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_validation.go
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_validation_test.go
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
  natss/pkg/apis/messaging/v1alpha1/natss_channel_validation.go
  natss/pkg/apis/messaging/v1alpha1/natss_channel_validation_test.go
  natss/pkg/dispatcher/types.go
  vendor/knative.dev/eventing/AUTHORS
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/test_helper.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/channel_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/in_memory_channel_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/parallel_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/sequence_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/subscription_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_handler.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/broker.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/parallel.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/sequence.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/subscription.go
  vendor/knative.dev/eventing/test/README.md
  vendor/knative.dev/eventing/test/base/resources/eventing.go
  vendor/knative.dev/eventing/test/common/performance/aggregator/aggregator.go
  vendor/knative.dev/eventing/test/common/performance/sender/http_load_generator.go
  vendor/knative.dev/eventing/test/common/performance/sender/request_interceptor.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/hack/istio-client-missing-group-name.patch
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/AUTHORS
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/configuration_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_defaults.go
  vendor/knative.dev/serving/pkg/network/error_handler.go
  vendor/knative.dev/serving/pkg/network/h2c.go
  vendor/knative.dev/serving/pkg/network/transports.go
  vendor/knative.dev/serving/third_party/istio-1.3-latest
  vendor/knative.dev/serving/third_party/istio-1.4-latest
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XL

#798 Trivial: drop errant test logging/debug line
  kafka/channel/pkg/dispatcher/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/XS

#799 golang format tools
  kafka/channel/pkg/dispatcher/dispatcher_test.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
Labels: approved, cla: yes, lgtm, size/S

#801 Pull example code into eventing-contrib
  cmd/appender/main.go
  config/tools/appender/appender.yaml
Labels: approved, cla: yes, lgtm, size/L

#802 add appender to release, alphatebize files
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#803 Cherrypick appender
  cmd/appender/main.go
  config/tools/appender/appender.yaml
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#804 update to cloudevents sdk 0.10.2 and eventing master.
  Gopkg.lock
  vendor/github.com/cloudevents/sdk-go/alias.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/client.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/defaulters.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/options.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec.go
  vendor/knative.dev/eventing/test/common/performance/aggregator/aggregator.go
  vendor/knative.dev/eventing/test/common/performance/common/pace.go
  vendor/knative.dev/eventing/test/common/performance/receiver/receiver.go
  vendor/knative.dev/eventing/test/common/performance/sender/http_load_generator.go
  vendor/knative.dev/eventing/test/test_images/sendevents/main.go
  vendor/knative.dev/eventing/test/test_images/transformevents/main.go
Labels: approved, cla: yes, lgtm, size/L

#808 Fix #805: add duck.InformerFactory to camel source context (0.11)
  camel/source/pkg/reconciler/camelsource.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
