Repository knative/eventing-contrib, pull requests merged in 2019-05, with the labels that each got.

#385 Delete moved API server event source
  Gopkg.lock
  contrib/apiserver/PROJECT
  contrib/apiserver/cmd/controller/main.go
  contrib/apiserver/cmd/receiver_adapter/main.go
  contrib/apiserver/config/100-namespace.yaml
  contrib/apiserver/config/200-serviceaccount.yaml
  contrib/apiserver/config/201-clusterrole.yaml
  contrib/apiserver/config/202-clusterrolebinding.yaml
  contrib/apiserver/config/300-apiserversource.yaml
  contrib/apiserver/config/400-controller-service.yaml
  contrib/apiserver/config/500-controller.yaml
  contrib/apiserver/pkg/adapter/adapter.go
  contrib/apiserver/pkg/adapter/adapter_test.go
  contrib/apiserver/pkg/apis/addtoscheme_sources_v1alpha1.go
  contrib/apiserver/pkg/apis/apis.go
  contrib/apiserver/pkg/apis/sources/group.go
  contrib/apiserver/pkg/apis/sources/v1alpha1/apiserversource_types.go
  contrib/apiserver/pkg/apis/sources/v1alpha1/apiserversource_types_test.go
  contrib/apiserver/pkg/apis/sources/v1alpha1/doc.go
  contrib/apiserver/pkg/apis/sources/v1alpha1/register.go
  contrib/apiserver/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  contrib/apiserver/pkg/client/clientset/versioned/clientset.go
  contrib/apiserver/pkg/client/clientset/versioned/doc.go
  contrib/apiserver/pkg/client/clientset/versioned/fake/clientset_generated.go
  contrib/apiserver/pkg/client/clientset/versioned/fake/doc.go
  contrib/apiserver/pkg/client/clientset/versioned/fake/register.go
  contrib/apiserver/pkg/client/clientset/versioned/scheme/doc.go
  contrib/apiserver/pkg/client/clientset/versioned/scheme/register.go
  contrib/apiserver/pkg/client/clientset/versioned/typed/sources/v1alpha1/apiserversource.go
  contrib/apiserver/pkg/client/clientset/versioned/typed/sources/v1alpha1/doc.go
  contrib/apiserver/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/doc.go
  contrib/apiserver/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_apiserversource.go
  contrib/apiserver/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_sources_client.go
  contrib/apiserver/pkg/client/clientset/versioned/typed/sources/v1alpha1/generated_expansion.go
  contrib/apiserver/pkg/client/clientset/versioned/typed/sources/v1alpha1/sources_client.go
  contrib/apiserver/pkg/client/informers/externalversions/factory.go
  contrib/apiserver/pkg/client/informers/externalversions/generic.go
  contrib/apiserver/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  contrib/apiserver/pkg/client/informers/externalversions/sources/interface.go
  contrib/apiserver/pkg/client/informers/externalversions/sources/v1alpha1/apiserversource.go
  contrib/apiserver/pkg/client/informers/externalversions/sources/v1alpha1/interface.go
  contrib/apiserver/pkg/client/listers/sources/v1alpha1/apiserversource.go
  contrib/apiserver/pkg/client/listers/sources/v1alpha1/expansion_generated.go
  contrib/apiserver/pkg/controller/add_apiserversource.go
  contrib/apiserver/pkg/controller/apiserversource/apiserversource_controller.go
  contrib/apiserver/pkg/controller/apiserversource/apiserversource_controller_test.go
  contrib/apiserver/pkg/controller/apiserversource/resources/receive_adapter.go
  contrib/apiserver/pkg/controller/apiserversource/resources/receive_adapter_test.go
  contrib/apiserver/pkg/controller/controller.go
  contrib/apiserver/samples/README.md
  contrib/apiserver/samples/apiserversource.yaml
  contrib/apiserver/samples/clusterrole.yaml
  contrib/apiserver/samples/clusterrolebinding.yaml
  contrib/apiserver/samples/event-display.yaml
  contrib/apiserver/samples/serviceaccount.yaml
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#386 Revert delete of github source yaml.
  config/300-githubsource.yaml
Labels: approved, cla: yes, lgtm, size/L

#349 Add OWNERS for a few of the Source implementations
  OWNERS_ALIASES
  contrib/gcppubsub/OWNERS
  contrib/kafka/OWNERS
  pkg/adapter/github/OWNERS
  pkg/reconciler/githubsource/OWNERS
Labels: approved, cla: yes, lgtm, size/M

#351 contrib/kafka: use secrets for SASL user and password
  contrib/kafka/config/300-kafkasource.yaml
  contrib/kafka/pkg/apis/sources/v1alpha1/kafka_types.go
  contrib/kafka/pkg/reconciler/resources/receive_adapter.go
  contrib/kafka/pkg/reconciler/resources/receive_adapter_test.go
  contrib/kafka/samples/event-source.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#395 remove duplicated keys
  contrib/kafka/config/300-kafkasource.yaml
Labels: approved, cla: yes, lgtm, size/XS

#387 Update test-infra: some fixes
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#392 Updating Source and Subject in GitHubSource
  pkg/adapter/github/adapter.go
  pkg/adapter/github/adapter_test.go
  pkg/apis/sources/v1alpha1/githubsource_types.go
  pkg/reconciler/githubsource/githubsource.go
  pkg/reconciler/githubsource/githubsource_test.go
Labels: approved, cla: yes, lgtm, size/XL

#391 Bind Kafka and Camel sources to the addressable-resolver role.
  contrib/camel/config/201-clusterrole.yaml
  contrib/camel/config/202-clusterrolebinding.yaml
  contrib/kafka/config/201-clusterrole.yaml
  contrib/kafka/config/202-clusterrolebinding.yaml
Labels: approved, cla: yes, lgtm, size/M

#397 update test-infra to remove dependency on Istio published by serving
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#396 GitHub source cosmetic change
  pkg/adapter/github/adapter.go
Labels: approved, cla: yes, lgtm, size/XS

#401 golang format tools
  pkg/adapter/github/adapter.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#405 Update CloudEvents SDK to 0.7.0
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/cloudevents/sdk-go/alias.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/codec/jsoncodec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_data.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_interface.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_reader.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v01_reader.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v02.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v02_reader.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v03_reader.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v02.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v03.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/options.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go
Labels: approved, cla: yes, lgtm, size/L

#407 contrib/kafka: support cert, key, and caCert in spec.net.tls
  contrib/kafka/cmd/receive_adapter/main.go
  contrib/kafka/config/300-kafkasource.yaml
  contrib/kafka/pkg/adapter/adapter.go
  contrib/kafka/pkg/adapter/adapter_test.go
  contrib/kafka/pkg/apis/sources/v1alpha1/kafka_types.go
  contrib/kafka/pkg/reconciler/resources/receive_adapter.go
  contrib/kafka/pkg/reconciler/resources/receive_adapter_test.go
  contrib/kafka/samples/event-source.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#412 allow v1services to be addressable
  pkg/controller/sinks/sinks.go
  pkg/controller/sinks/sinks_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#411 Updating Kafka CloudEvent source
  contrib/kafka/cmd/receive_adapter/main.go
  contrib/kafka/pkg/adapter/adapter.go
  contrib/kafka/pkg/adapter/adapter_test.go
  contrib/kafka/pkg/apis/sources/v1alpha1/kafka_types.go
  contrib/kafka/pkg/reconciler/kafkasource.go
  contrib/kafka/pkg/reconciler/kafkasource_test.go
  contrib/kafka/pkg/reconciler/resources/receive_adapter.go
  contrib/kafka/pkg/reconciler/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/M

#406 awssqs: fix breakage after moving to contrib/
  contrib/awssqs/config/201-clusterrole.yaml
  contrib/awssqs/pkg/apis/addtoscheme_eventing_v1alpha1.go
Labels: approved, cla: yes, lgtm, size/M

#408 AWS is out in contrib, hence removing
  config/201-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#416 Format markdown
  contrib/awssqs/samples/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#417 golang format tools
  contrib/kafka/pkg/apis/sources/v1alpha1/kafka_types.go
  contrib/kafka/pkg/reconciler/kafkasource.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#414 gcppubsub: do not use logger if creation failed
  contrib/gcppubsub/cmd/controller/main.go
Labels: approved, cla: yes, lgtm, size/XS

#398 Adding transformer field to GCPPubSubSource CRD.
  contrib/gcppubsub/cmd/receive_adapter/main.go
  contrib/gcppubsub/config/300-gcppubsubsource.yaml
  contrib/gcppubsub/pkg/adapter/adapter.go
  contrib/gcppubsub/pkg/adapter/adapter_test.go
  contrib/gcppubsub/pkg/apis/sources/v1alpha1/gcp_pubsub_types.go
  contrib/gcppubsub/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  contrib/gcppubsub/pkg/reconciler/gcppubsubsource.go
  contrib/gcppubsub/pkg/reconciler/gcppubsubsource_test.go
  contrib/gcppubsub/pkg/reconciler/resources/receive_adapter.go
  contrib/gcppubsub/pkg/reconciler/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/L

#381 k8s resources spec changes
  config/500-controller.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#419 Update test infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M

#420 Deleting EventTypes when changing sink to a non-Broker kind
  contrib/awssqs/pkg/reconciler/awssqssource.go
  contrib/gcppubsub/pkg/reconciler/gcppubsubsource.go
  contrib/gcppubsub/pkg/reconciler/gcppubsubsource_test.go
  contrib/kafka/pkg/reconciler/kafkasource.go
  contrib/kafka/pkg/reconciler/kafkasource_test.go
  pkg/reconciler/eventtype/eventtype.go
  pkg/reconciler/githubsource/githubsource.go
  pkg/reconciler/githubsource/githubsource_test.go
Labels: approved, cla: yes, lgtm, size/L

#422 golang format tools
  contrib/gcppubsub/cmd/receive_adapter/main.go
  contrib/gcppubsub/pkg/adapter/adapter.go
  contrib/gcppubsub/pkg/reconciler/gcppubsubsource_test.go
  contrib/kafka/pkg/reconciler/kafkasource_test.go
  pkg/reconciler/eventtype/eventtype.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#413 allow controller to get/list Services as sinks
  config/201-clusterrole.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#425 Update test-infra: handle stockout to work with new error string
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/M

#403 Upgrade Camel Sources to use Camel K 0.3.3 and add complex integrations
  Gopkg.lock
  Gopkg.toml
  contrib/camel/cmd/controller/main.go
  contrib/camel/config/201-clusterrole.yaml
  contrib/camel/config/300-camelsource.yaml
  contrib/camel/pkg/apis/sources/v1alpha1/camelsource_types.go
  contrib/camel/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  contrib/camel/pkg/install/install.go
  contrib/camel/pkg/reconciler/camelsource.go
  contrib/camel/pkg/reconciler/camelsource_test.go
  contrib/camel/pkg/reconciler/resources/arguments.go
  contrib/camel/pkg/reconciler/resources/component.go
  contrib/camel/pkg/reconciler/resources/integration.go
  contrib/camel/pkg/reconciler/resources/integration_test.go
  contrib/camel/pkg/reconciler/resources/platform.go
  contrib/camel/pkg/reconciler/resources/source.go
  contrib/camel/samples/README.md
  contrib/camel/samples/source_camel_k.yaml
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/build_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/camelcatalog_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/camelcatalog_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/common_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/common_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integration_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integration_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integrationcontext_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integrationcontext_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integrationplatform_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/integrationplatform_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/knative/types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1alpha1/zz_generated.defaults.go
  vendor/github.com/apache/camel-k/pkg/util/util.go
  vendor/github.com/magiconair/properties/LICENSE
  vendor/github.com/magiconair/properties/decode.go
  vendor/github.com/magiconair/properties/doc.go
  vendor/github.com/magiconair/properties/integrate.go
  vendor/github.com/magiconair/properties/lex.go
  vendor/github.com/magiconair/properties/load.go
  vendor/github.com/magiconair/properties/parser.go
  vendor/github.com/magiconair/properties/properties.go
  vendor/github.com/magiconair/properties/rangecheck.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#433 Format markdown
  contrib/camel/samples/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#434 golang format tools
  contrib/camel/pkg/install/install.go
  contrib/camel/pkg/reconciler/camelsource.go
  contrib/camel/pkg/reconciler/camelsource_test.go
  contrib/camel/pkg/reconciler/resources/integration_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#424 GCPPubSub Transformer cosmetic changes
  contrib/gcppubsub/cmd/receive_adapter/main.go
  contrib/gcppubsub/config/300-gcppubsubsource.yaml
  contrib/gcppubsub/pkg/adapter/adapter.go
  contrib/gcppubsub/pkg/adapter/adapter_test.go
  contrib/gcppubsub/pkg/apis/sources/v1alpha1/gcp_pubsub_types.go
Labels: approved, cla: yes, lgtm, size/M

#429 updating dependency
  Gopkg.lock
Labels: approved, cla: yes, lgtm, size/XS

#440 golang format tools
  contrib/gcppubsub/cmd/receive_adapter/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#447 Update vendored test-infra
  Gopkg.lock
  hack/update-deps.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/k8s.io/code-generator/Godeps/OWNERS
  vendor/k8s.io/code-generator/OWNERS
  vendor/k8s.io/code-generator/cmd/client-gen/OWNERS
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/OWNERS
Labels: approved, cla: yes, lgtm, size/L

#439 Use OWNERS_ALIASES for productivity approvers/reviewers
  OWNERS_ALIASES
  hack/OWNERS
  test/OWNERS
Labels: approved, cla: yes, lgtm, size/M

#399 Issue #364 Add Support to Kafka Source for Resource spec
  Gopkg.lock
  contrib/kafka/config/300-kafkasource.yaml
  contrib/kafka/pkg/apis/sources/v1alpha1/kafka_types.go
  contrib/kafka/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  contrib/kafka/pkg/reconciler/kafkasource.go
  contrib/kafka/pkg/reconciler/kafkasource_test.go
  contrib/kafka/pkg/reconciler/resources/receive_adapter.go
  contrib/kafka/pkg/reconciler/resources/receive_adapter_test.go
  contrib/kafka/samples/event-source.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#449 update test-infra to the latest version
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M
