Repository knative/eventing-contrib, pull requests merged in 2019-03, with the labels that each got.

#226 migrate github, awssqs, cron, and websocket sources to new cloudevents sdk v0.2
  cmd/websocketsource/main.go
  pkg/adapter/awssqs/adapter.go
  pkg/adapter/cronjobevents/adapter.go
  pkg/adapter/cronjobevents/adapter_test.go
  pkg/adapter/github/adapter.go
  pkg/adapter/github/adapter_test.go
Labels: approved, lgtm, size/L

#228 Fix spelling errors
  pkg/reconciler/githubsource/webhook_client.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#225 Adding knative-sources namespace to gcppubsub ServiceAccount
  contrib/gcppubsub/config/200-serviceaccount.yaml
Labels: approved, lgtm, size/XS

#233 Fix wrong namespace to create event-sources in REDME
  samples/cronjob-source/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#230 Adding myself as a reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#235 Correct release artifacts in release.sh
  hack/release.sh
Labels: approved, lgtm, size/XS

#238 Update test-infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.json
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.rc
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#239 Remove references to missing test/e2e dir
  test/README.md
Labels: approved, lgtm, size/S

#234 Fix typo in doc
  test/README.md
Labels: approved, lgtm, size/XS

#236 Remove dead code from release.sh
  hack/release.sh
Labels: approved, lgtm, size/S

#245 Added dev info
  DEVELOPMENT.md
Labels: approved, lgtm, size/S

#240 Fix race condition for creating cloudevent client
  pkg/adapter/awssqs/adapter.go
  pkg/adapter/awssqs/adapter_test.go
  pkg/adapter/cronjobevents/adapter.go
  pkg/adapter/cronjobevents/adapter_test.go
  pkg/adapter/github/adapter.go
Labels: approved, lgtm, size/M

#229 Fix invalid log format from cronjob source
  cmd/cronjob_receive_adapter/main.go
Labels: approved, lgtm, size/XS

#243 Enable specifying https github webhooks
  pkg/apis/sources/v1alpha1/githubsource_types.go
  pkg/reconciler/githubsource/githubsource.go
  pkg/reconciler/githubsource/githubsource_test.go
  pkg/reconciler/githubsource/webhook_client.go
Labels: approved, lgtm, size/M

#251 Disable markdown linting in presubmits.
  test/markdown-lint-config.rc
  test/presubmit-tests.sh
Labels: approved, lgtm, size/S

#250 Use New func to protect race condition for cloudevent client.
  cmd/github_receive_adapter/main.go
  pkg/adapter/github/adapter.go
  pkg/adapter/github/adapter_test.go
Labels: approved, lgtm, size/M

#254 golang format tools
  cmd/heartbeats/main.go
  cmd/heartbeats_receiver/main.go
  cmd/websocketsource/main.go
  contrib/camel/pkg/reconciler/camelsource_test.go
  contrib/camel/pkg/reconciler/resources/context.go
  contrib/camel/pkg/reconciler/resources/platform.go
  contrib/camel/pkg/reconciler/resources/source.go
  contrib/gcppubsub/pkg/adapter/adapter.go
  contrib/gcppubsub/pkg/adapter/adapter_test.go
  pkg/adapter/awssqs/adapter.go
  pkg/adapter/cronjobevents/adapter.go
  pkg/adapter/github/adapter_test.go
  pkg/adapter/kubernetesevents/adapter.go
  pkg/adapter/kubernetesevents/adapter_test.go
Labels: approved, lgtm, needs-ok-to-test, size/M

#255 Format markdown
  DEVELOPMENT.md
  contrib/camel/samples/README.md
Labels: approved, lgtm, needs-ok-to-test, size/L

#249 Move away from Message Dumper and use Event Display.
  cmd/event_display/main.go
  cmd/heartbeats/main.go
  cmd/message_dumper/dumper.go
  config/tools/event-display/event-display.yaml
  contrib/camel/samples/README.md
  contrib/camel/samples/display_resources.yaml
  contrib/gcppubsub/samples/README.md
  contrib/gcppubsub/samples/event-display.yaml
  contrib/gcppubsub/samples/gcp-pubsub-source.yaml
  hack/release.sh
  samples/awssqs_source/README.md
  samples/awssqs_source/subscriber.yaml
  samples/cronjob-source/README.md
  samples/cronjob-source/subscriber.yaml
  samples/kubernetes-event-source/README.md
  samples/kubernetes-event-source/subscription.yaml
Labels: approved, lgtm, size/L

#256 Fix link to Knative Eventing docs
  README.md
Labels: approved, lgtm, size/XS

#252 Adding Broker read permissions
  config/201-clusterrole.yaml
  contrib/camel/config/201-clusterrole.yaml
  contrib/gcppubsub/config/201-clusterrole.yaml
Labels: approved, lgtm, size/XS

#261 Development README fixes
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#262 Use pkg/test for common test components
  test/crd.go
  test/e2e/e2e.go
  test/e2e/k8s_events_test.go
  test/e2e_flags.go
  test/states.go
Labels: approved, lgtm, size/L

#263 Make upload test images simpler
  test/upload-test-images.sh
Labels: approved, lgtm, size/S

#265 Fix broken links to docs repo
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#273 #fixitfriday fix kubernetes sample link
  samples/kubernetes-event-source/README.md
Labels: approved, lgtm, size/XS

#276 Update links to docs repo
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  contrib/gcppubsub/samples/README.md
  samples/awssqs_source/README.md
  samples/cronjob-source/README.md
  samples/heartbeats/README.md
  samples/kubernetes-event-source/README.md
Labels: approved, lgtm, size/L

#277 Format markdown
  CONTRIBUTING.md
  README.md
  samples/awssqs_source/README.md
  samples/cronjob-source/README.md
  samples/heartbeats/README.md
  samples/kubernetes-event-source/README.md
  test/e2e/README.md
Labels: approved, lgtm, needs-ok-to-test, size/M

#285 wire labels and annotations through to the deployment
  pkg/reconciler/containersource/containersource.go
  pkg/reconciler/containersource/containersource_test.go
  pkg/reconciler/containersource/resources/arguments.go
  pkg/reconciler/containersource/resources/deployment.go
  pkg/reconciler/containersource/resources/deployment_test.go
Labels: approved, lgtm, size/L

#287 golang format tools
  cmd/event_display/main.go
Labels: approved, lgtm, size/XS

#293 Kafka doc fixes
  contrib/kafka/cmd/controller/main.go
  contrib/kafka/cmd/receive_adapter/main.go
  contrib/kafka/pkg/reconciler/kafkasource.go
  contrib/kafka/samples/README.md
  contrib/kafka/samples/event-source.yaml
Labels: approved, cla: yes, lgtm, size/M

#289 Change brokers references to bootstrap servers for Kafka event source
  contrib/kafka/cmd/receive_adapter/main.go
  contrib/kafka/config/300-kafkasource.yaml
  contrib/kafka/pkg/adapter/adapter.go
  contrib/kafka/pkg/adapter/adapter_test.go
  contrib/kafka/pkg/apis/sources/v1alpha1/kafka_types.go
  contrib/kafka/pkg/apis/sources/v1alpha1/kafka_validation_test.go
  contrib/kafka/pkg/reconciler/kafkasource_test.go
  contrib/kafka/pkg/reconciler/resources/receive_adapter.go
  contrib/kafka/pkg/reconciler/resources/receive_adapter_test.go
  contrib/kafka/samples/README.md
  contrib/kafka/samples/event-source.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#260 Adding n3wscott to owners.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#298 Clean up args handling, remove todo
  pkg/reconciler/githubsource/githubsource.go
Labels: approved, cla: yes, lgtm, size/M

#296 golang format tools
  contrib/kafka/cmd/controller/main.go
  contrib/kafka/pkg/adapter/adapter.go
  contrib/kafka/pkg/adapter/adapter_test.go
  contrib/kafka/pkg/apis/sources/v1alpha1/register_test.go
  contrib/kafka/pkg/reconciler/kafkasource.go
  contrib/kafka/pkg/reconciler/kafkasource_test.go
  contrib/kafka/pkg/reconciler/resources/receive_adapter.go
  contrib/kafka/pkg/reconciler/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/S

#307 GitHub Webhooks Broken - Important
  pkg/reconciler/githubsource/githubsource.go
Labels: approved, cla: yes, lgtm, size/XS

#308 KafkaSource does NO LONGERignore failures when POSTing to sinks
  contrib/kafka/pkg/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/S

#311 Rename release artifacts to eventing-sources.yaml
  hack/release.sh
  samples/awssqs_source/README.md
  samples/cronjob-source/README.md
Labels: approved, cla: yes, kind/feature-request, lgtm, size/XS

#310 Format markdown
  contrib/kafka/samples/README.md
Labels: approved, cla: yes, lgtm, size/L

#290 Update order of Kafka sample steps
  contrib/kafka/samples/README.md
Labels: approved, cla: yes, lgtm, size/M

#313 Fix spelling errors
  contrib/kafka/pkg/adapter/adapter.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#312 Update gengo
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/gengo/.import-restrictions
  vendor/k8s.io/gengo/.travis.yml
  vendor/k8s.io/gengo/CONTRIBUTING.md
  vendor/k8s.io/gengo/OWNERS
  vendor/k8s.io/gengo/README.md
  vendor/k8s.io/gengo/SECURITY_CONTACTS
  vendor/k8s.io/gengo/boilerplate/boilerplate.go.txt
  vendor/k8s.io/gengo/boilerplate/no-boilerplate.go.txt
  vendor/k8s.io/gengo/code-of-conduct.md
  vendor/k8s.io/gengo/examples/deepcopy-gen/.gitignore
  vendor/k8s.io/gengo/examples/deepcopy-gen/Makefile
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/main.go
  vendor/k8s.io/gengo/examples/defaulter-gen/.gitignore
  vendor/k8s.io/gengo/examples/defaulter-gen/.import-restrictions
  vendor/k8s.io/gengo/examples/defaulter-gen/Makefile
  vendor/k8s.io/gengo/examples/defaulter-gen/OWNERS
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/defaulter-gen/main.go
  vendor/k8s.io/gengo/examples/import-boss/.gitignore
  vendor/k8s.io/gengo/examples/import-boss/generators/import_restrict.go
  vendor/k8s.io/gengo/examples/import-boss/main.go
  vendor/k8s.io/gengo/examples/set-gen/.gitignore
  vendor/k8s.io/gengo/examples/set-gen/Makefile
  vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
  vendor/k8s.io/gengo/examples/set-gen/generators/tags.go
  vendor/k8s.io/gengo/examples/set-gen/main.go
  vendor/k8s.io/gengo/generator/execute.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/parser/parse.go
  vendor/k8s.io/gengo/types/types.go
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XXL

#316 add missing test for nil address
  pkg/controller/sinks/sinks_test.go
Labels: approved, cla: yes, lgtm, size/XS

#319 Add a label knative.dev/crd-install to CRDs to allow installing CRDs in a separate pass.
  config/300-awssqssource.yaml
  config/300-containersource.yaml
  config/300-cronjobsource.yaml
  config/300-githubsource.yaml
  config/300-kuberneteseventsource.yaml
  contrib/camel/config/300-camelsource.yaml
  contrib/gcppubsub/config/300-gcppubsubsource.yaml
  contrib/kafka/config/300-kafkasource.yaml
Labels: approved, cla: yes, lgtm, size/XS

#318 KafkaSource missing RBAC rule for finalizers
  contrib/kafka/config/201-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS
