Repository knative/eventing-contrib, pull requests merged in 2019-01, with the labels that each got.

#164 Align GitHubSource receive adapter naming with others
  cmd/github_receive_adapter/main.go
  config/default-awssqs.yaml
  config/default-gcppubsub.yaml
  config/default.yaml
  config/default/manager_image_patch.yaml
  pkg/adapter/github/adapter.go
  pkg/adapter/github/adapter_test.go
Labels: approved, lgtm, size/M

#154 Update KubernetesEventSource sample doc
  samples/kubernetes-event-source/README.md
Labels: approved, lgtm, size/M

#165 Format markdown
  samples/kubernetes-event-source/README.md
Labels: approved, lgtm

#167 awssqs: fix README format and paths
  samples/awssqs_source/README.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#166 Improve error messages when event delivery fails.
  cmd/awssqs_receive_adapter/main.go
  cmd/cronjob_receive_adapter/main.go
  cmd/kuberneteseventsource/main.go
  contrib/gcppubsub/cmd/receive_adapter/main.go
  contrib/gcppubsub/pkg/adapter/adapter.go
  pkg/adapter/awssqs/adapter.go
  pkg/adapter/awssqs/adapter_test.go
  pkg/adapter/cronjobevents/adapter.go
  pkg/adapter/cronjobevents/adapter_test.go
  pkg/adapter/kubernetesevents/adapter.go
  pkg/adapter/kubernetesevents/adapter_test.go
Labels: approved, lgtm, size/L

#170 Format markdown
  contrib/gcppubsub/samples/README.md
  samples/awssqs_source/README.md
Labels: approved, lgtm, needs-ok-to-test, size/M

#169 golang format tools
  cmd/kuberneteseventsource/main.go
  contrib/gcppubsub/cmd/receive_adapter/main.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#171 fix compilation of gcppubsub adapter test
  contrib/gcppubsub/pkg/adapter/adapter_test.go
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#173 Update update-manifests to look harder in contrib.
  Gopkg.lock
  config/default-awssqs.yaml
  config/default-gcppubsub.yaml
  contrib/gcppubsub/PROJECT
  contrib/gcppubsub/config/default-gcppubsub.yaml
  contrib/gcppubsub/config/kustomization.yaml
  contrib/gcppubsub/config/rbac_role.yaml
  contrib/gcppubsub/config/rbac_role_binding.yaml
  contrib/gcppubsub/config/rbac_role_binding_patch.yaml
  contrib/gcppubsub/pkg/controller/doc.go
  hack/update-manifests.sh
Labels: approved, lgtm, size/XL

#168 awssqs: consolidate pkg name
  pkg/controller/add_awssqssources.go
  pkg/controller/awssqssource/doc.go
  pkg/controller/awssqssource/provider.go
  pkg/controller/awssqssource/reconcile.go
  pkg/controller/awssqssource/resources/receive_adapter.go
Labels: approved, lgtm, size/S

#175 Allow ce-type in message attributes to specify event type
  contrib/gcppubsub/pkg/adapter/adapter.go
  contrib/gcppubsub/pkg/adapter/adapter_test.go
Labels: approved, lgtm, size/M

#184 add n3wscott to reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#192 Removing kubebuilder.
  DEVELOPMENT.md
  Makefile
  PROJECT
  config/100-namespace.yaml
  config/200-serviceaccount.yaml
  config/201-clusterrole.yaml
  config/202-clusterrolebinding.yaml
  config/300-awssqssource.yaml
  config/300-containersource.yaml
  config/300-cronjobsource.yaml
  config/300-githubsource.yaml
  config/300-kuberneteseventsource.yaml
  config/400-controller-service.yaml
  config/500-controller.yaml
  config/README.md
  config/awssqs/conditions_patch.yaml
  config/awssqs/env_patch.yaml
  config/awssqs/istio_egress.yaml
  config/awssqs/kustomization.yaml
  config/default-awssqs.yaml
  config/default.yaml
  config/default/containersource_conditions_patch.yaml
  config/default/cronjobsource_conditions_patch.yaml
  config/default/githubsource_conditions_patch.yaml
  config/default/kuberneteseventsource_conditions_patch.yaml
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  config/manager/manager.yaml
  config/rbac/rbac_role.yaml
  config/rbac/rbac_role_binding.yaml
  config/samples/githubsource.yaml
  config/samples/kuberneteseventsource.yaml
  config/tools/message-dumper.yaml
  config/tools/message-dumper/message-dumper.yaml
  contrib/gcppubsub/config/200-serviceaccount.yaml
  contrib/gcppubsub/config/201-clusterrole.yaml
  contrib/gcppubsub/config/202-clusterrolebinding.yaml
  contrib/gcppubsub/config/300-gcppubsubsource.yaml
  contrib/gcppubsub/config/400-controller-service.yaml
  contrib/gcppubsub/config/500-controller.yaml
  contrib/gcppubsub/config/600-istioegress.yaml
  contrib/gcppubsub/config/conditions_patch.yaml
  contrib/gcppubsub/config/default-gcppubsub.yaml
  contrib/gcppubsub/config/istio_egress.yaml
  contrib/gcppubsub/config/kustomization.yaml
  contrib/gcppubsub/config/manager.yaml
  contrib/gcppubsub/config/rbac_role.yaml
  contrib/gcppubsub/config/rbac_role_binding.yaml
  contrib/gcppubsub/config/rbac_role_binding_patch.yaml
  contrib/gcppubsub/config/service_account.yaml
  contrib/gcppubsub/samples/dumper.yaml
  hack/README.md
  hack/release.sh
  hack/update-manifests.sh
  hack/verify-manifests.sh
  pkg/apis/sources/v1alpha1/containersource_types.go
  samples/cronjob-source/README.md
  samples/kubernetes-event-source/README.md
  samples/kubernetes-event-source/serviceaccount.yaml
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XXL

#195 Replace repeated YAML lists with anchors and aliases.
  config/201-clusterrole.yaml
  config/500-controller.yaml
  contrib/gcppubsub/config/201-clusterrole.yaml
  contrib/gcppubsub/config/500-controller.yaml
Labels: approved, lgtm, size/M

#196 Update test-infra
  Gopkg.lock
  hack/release.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.json
  vendor/github.com/knative/test-infra/scripts/markdown-lint-config.rc
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/github.com/knative/test-infra/tools/dep-collector/README.md
Labels: approved, lgtm, size/XXL

#197 Change Signature of KnativeReconciler.Reconcile
  contrib/gcppubsub/pkg/controller/reconcile.go
  pkg/controller/awssqssource/reconcile.go
  pkg/controller/containersource/reconcile.go
  pkg/controller/containersource/reconcile_test.go
  pkg/controller/cronjobsource/reconcile.go
  pkg/controller/githubsource/reconcile.go
  pkg/controller/githubsource/reconcile_test.go
  pkg/controller/sdk/provider.go
  pkg/controller/sdk/reconciler.go
  pkg/controller/testing/table.go
Labels: approved, lgtm, size/M
