Repository knative/eventing-contrib, pull requests merged in 2020-12, with the labels that each got.

#1671 fix label consistency
  kafka/source/pkg/reconciler/source/resources/labels.go
  kafka/source/pkg/reconciler/source/resources/labels_test.go
  test/e2e/helpers/kafka_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#1672 Set subscription readiness based on consumer group status
  kafka/channel/cmd/channel_dispatcher/main.go
  kafka/channel/pkg/kafka/admin.go
  kafka/channel/pkg/kafka/admin_test.go
  kafka/channel/pkg/reconciler/controller/consumer_group_watcher.go
  kafka/channel/pkg/reconciler/controller/consumer_group_watcher_test.go
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/controller/kafkachannel_test.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  kafka/channel/pkg/reconciler/testing/kafkachannel.go
Labels: approved, cla: yes, lgtm, size/XL

#1675 Updating the file that generates the build
  config/tools/websocket-source/websocket-source.yaml
Labels: approved, cla: yes, lgtm, size/S

#1676 fix custom consumer group error channel lifecycle (#263)
  kafka/common/pkg/kafka/consumer_factory.go
  kafka/common/pkg/kafka/consumer_factory_test.go
  kafka/common/pkg/kafka/consumer_handler.go
  kafka/common/pkg/kafka/consumer_handler_test.go
Labels: approved, cla: yes, lgtm, size/M
