Repository knative/eventing-contrib, pull requests merged in 2020-03, with the labels that each got.

#981 Add an `--upgrade` flag to `./hack/update-deps.sh`
  hack/update-deps.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#982 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/channelable_combined_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/register.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/apiserver_validation.go
  vendor/knative.dev/eventing/test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#984 support overriding event type
  cmd/appender/main.go
Labels: approved, cla: yes, lgtm, size/XS

#987 Remove myself from GitHub / Kafka approvers / reviewers
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#985 Post v0.13 release, point pkg to master.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/metrics/README.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metricskey/constants.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/testdata/README.md
  vendor/knative.dev/pkg/metrics/testdata/client-cert.pem
  vendor/knative.dev/pkg/metrics/testdata/client-key.pem
  vendor/knative.dev/pkg/metrics/testdata/server-cert.pem
  vendor/knative.dev/pkg/metrics/testdata/server-key.pem
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/test/logging/logging.go
Labels: approved, cla: yes, lgtm, size/L

#989 remove empty statefulset for kafkaSRC
  kafka/source/config/500-controller.yaml
Labels: approved, cla: yes, lgtm, size/M

#988 Fix link to Eventing setup in NATSS
  natss/config/README.md
Labels: approved, cla: yes, lgtm, size/XS

#991 Upgrade Camel K to 1.0.0-RC2
  Gopkg.lock
  Gopkg.toml
  camel/source/pkg/reconciler/camelsource_test.go
  camel/source/pkg/reconciler/resources/integration.go
  camel/source/pkg/reconciler/resources/integration_test.go
  test/config/100-camel-k-1.0.0-RC2.yaml
  test/e2e-tests.sh
  test/e2e/camel_source_test.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/build_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/build_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/camelcatalog_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/camelcatalog_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/common_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integration_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integration_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integrationkit_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integrationkit_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integrationplatform_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integrationplatform_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/zz_generated.deepcopy.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/L

#998 Use ko's strict mode for better errors messages
  awssqs/samples/display-resources.yaml
  ceph/samples/ceph-display-resources.yaml
  config/tools/appender/appender.yaml
  config/tools/event-display/event-display.yaml
  hack/release.sh
  samples/cronjob-source/subscriber.yaml
  samples/heartbeats/heartbeats-receiver.yaml
  samples/heartbeats/heartbeats-sender.yaml
  samples/sources_v1alpha1_containersources.yaml
  samples/sources_v1alpha2_websocketsource.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1000 Backport to 0.13: upgrade Camel K to 1.0.0-RC2 (#991)
  Gopkg.lock
  Gopkg.toml
  camel/source/pkg/reconciler/camelsource_test.go
  camel/source/pkg/reconciler/resources/integration.go
  camel/source/pkg/reconciler/resources/integration_test.go
  test/config/100-camel-k-1.0.0-RC2.yaml
  test/e2e-tests.sh
  test/e2e/camel_source_test.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/build_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/build_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/camelcatalog_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/camelcatalog_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/common_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integration_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integration_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integrationkit_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integrationkit_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integrationplatform_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integrationplatform_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/zz_generated.deepcopy.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1001 Switch additional images to strict mode
  awssqs/config/500-controller.yaml
  camel/source/config/500-controller.yaml
  ceph/samples/ceph-container-source.yaml
  couchdb/source/config/500-controller.yaml
  couchdb/source/config/500-webhook.yaml
  github/config/500-controller.yaml
  github/config/500-webhook.yaml
  kafka/channel/config/500-controller.yaml
  kafka/channel/config/500-webhook.yaml
  kafka/source/config/500-controller.yaml
  natss/config/500-controller.yaml
  natss/config/500-dispatcher.yaml
  prometheus/config/500-controller.yaml
  test/performance/broker-kafka/200-broker-perf.yaml
  test/performance/channel-kafka/200-channel-perf.yaml
  test/performance/source-kafka/200-source-perf.yaml
  test/test_images/kafka_performance/pod.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#996 Fixing issue with incorrect conversion of sqs SentTimestamp
  awssqs/pkg/adapter/adapter.go
  awssqs/pkg/adapter/adapter_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#992 adding Nicola to Camel reviewers
  OWNERS_ALIASES
  camel/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#1009 Drop pkg/apis in eventing-contrib.
  Gopkg.lock
  couchdb/source/pkg/apis/sources/v1alpha1/register.go
  couchdb/source/pkg/apis/sources/v1alpha1/register_test.go
  couchdb/source/pkg/reconciler/controller.go
  github/pkg/apis/sources/v1alpha1/githubsource_types.go
  github/pkg/apis/sources/v1alpha1/register.go
  github/pkg/apis/sources/v1alpha1/register_test.go
  github/pkg/reconciler/controller.go
  kafka/source/pkg/apis/sources/group.go
  kafka/source/pkg/apis/sources/v1alpha1/register.go
  pkg/apis/sources/register.go
  pkg/apis/sources/v1alpha1/register.go
  prometheus/pkg/apis/sources/v1alpha1/register.go
  prometheus/pkg/apis/sources/v1alpha1/register_test.go
  prometheus/pkg/reconciler/controller.go
Labels: approved, cla: yes, lgtm, size/L

#1011 GitHubSource to genreconciler
  Gopkg.lock
  github/pkg/apis/sources/v1alpha1/githubsource_types.go
  github/pkg/client/injection/reconciler/sources/v1alpha1/githubsource/controller.go
  github/pkg/client/injection/reconciler/sources/v1alpha1/githubsource/reconciler.go
  github/pkg/client/injection/reconciler/sources/v1alpha1/githubsource/stub/controller.go
  github/pkg/client/injection/reconciler/sources/v1alpha1/githubsource/stub/reconciler.go
  github/pkg/reconciler/controller.go
  github/pkg/reconciler/githubsource.go
  github/pkg/reconciler/resources/service.go
  vendor/knative.dev/serving/pkg/client/injection/informers/serving/v1/service/service.go
Labels: approved, cla: yes, lgtm, size/L

#1010 Drop use of deprecated filter API
  couchdb/source/pkg/reconciler/controller.go
  kafka/source/pkg/reconciler/controller.go
  prometheus/pkg/reconciler/controller.go
Labels: approved, cla: yes, lgtm, size/S

#1004 Update to latest pkg 0.13
  Gopkg.lock
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/exporter.go
Labels: approved, cla: yes, lgtm, size/XS

#1013 Fixing issue with awssqs controller pointing to stub class
  awssqs/cmd/controller/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1016 EventTypes from listers.
  github/pkg/reconciler/controller.go
  github/pkg/reconciler/githubsource.go
Labels: approved, cla: yes, lgtm, size/S

#963 Get rid of the hacky patch for test images and use sed instead
  hack/update-deps.sh
  hack/update-image-paths.patch
  test/e2e-tests.sh
  vendor/knative.dev/eventing/test/test_images/logevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/performance/pod.yaml
  vendor/knative.dev/eventing/test/test_images/sendevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/transformevents/pod.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1018 For now, disable --strict for release
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1015 Update CouchDB to use genreconciler
  couchdb/source/pkg/apis/sources/v1alpha1/couchdbsource_types.go
  couchdb/source/pkg/client/injection/reconciler/sources/v1alpha1/couchdbsource/controller.go
  couchdb/source/pkg/client/injection/reconciler/sources/v1alpha1/couchdbsource/reconciler.go
  couchdb/source/pkg/client/injection/reconciler/sources/v1alpha1/couchdbsource/stub/controller.go
  couchdb/source/pkg/client/injection/reconciler/sources/v1alpha1/couchdbsource/stub/reconciler.go
  couchdb/source/pkg/reconciler/controller.go
  couchdb/source/pkg/reconciler/couchdbsource.go
  hack/update-codegen.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1017 PrometheusSource to genreconciler
  prometheus/pkg/apis/sources/v1alpha1/prometheussource_types.go
  prometheus/pkg/client/injection/reconciler/sources/v1alpha1/prometheussource/controller.go
  prometheus/pkg/client/injection/reconciler/sources/v1alpha1/prometheussource/reconciler.go
  prometheus/pkg/client/injection/reconciler/sources/v1alpha1/prometheussource/stub/controller.go
  prometheus/pkg/client/injection/reconciler/sources/v1alpha1/prometheussource/stub/reconciler.go
  prometheus/pkg/reconciler/controller.go
  prometheus/pkg/reconciler/prometheussource.go
Labels: approved, cla: yes, lgtm, size/L

#1014 [RELEASE 0.13] Backport a minimal fix for GitHubSource
  pkg/apis/sources/register.go
Labels: approved, cla: yes, lgtm, size/XS

#1021 Add logic to reconcile the github webhook.
  github/pkg/reconciler/githubsource.go
  github/pkg/reconciler/webhook_client.go
Labels: approved, cla: yes, lgtm, size/M

#1023 Support for GitHubSource + auto-TLS
  github/pkg/apis/sources/v1alpha1/githubsource_types.go
  github/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  github/pkg/reconciler/githubsource.go
  github/pkg/reconciler/webhook_client.go
Labels: approved, cla: yes, lgtm, size/M

#1026 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/knative.dev/serving/third_party/istio-1.4-latest
Labels: approved, cla: yes, lgtm, size/M

#1028 Fix a bug in https support
  github/pkg/reconciler/githubsource.go
Labels: approved, cla: yes, lgtm, size/XS

#1020 Update KafkaChannel controller to use genreconciler
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_types.go
  kafka/channel/pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/controller.go
  kafka/channel/pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/reconciler.go
  kafka/channel/pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/stub/controller.go
  kafka/channel/pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/stub/reconciler.go
  kafka/channel/pkg/reconciler/controller/controller.go
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/controller/kafkachannel_test.go
Labels: approved, cla: yes, lgtm, size/L

#1027 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/fake/fake.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/factory/factory.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/psbinding/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/third_party/istio-1.5-latest
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#1030 Don't advance the consumer group when events can't be delivered.
  kafka/channel/pkg/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, size/XS

#1038 Prune pkg/kncloudevents
  awssqs/pkg/adapter/adapter.go
  ceph/pkg/adapter/adapter.go
  cmd/event_display/main.go
  cmd/heartbeats/main.go
  cmd/heartbeats_receiver/main.go
  cmd/websocketsource/main.go
  github/pkg/adapter/adapter.go
  github/pkg/adapter/adapter_test.go
  kafka/source/pkg/adapter/adapter_benchmark_test.go
  kafka/source/pkg/adapter/adapter_test.go
  pkg/kncloudevents/good_client.go
Labels: approved, cla: yes, lgtm, size/M

#1008 NatssChannel Dispatcher Refactor to use CloudEvents
  Gopkg.lock
  natss/cmd/channel_controller/main.go
  natss/cmd/channel_dispatcher/main.go
  natss/pkg/dispatcher/dispatcher.go
  natss/pkg/dispatcher/testing/testing.go
  natss/pkg/dispatcher/types.go
  natss/pkg/reconciler/controller/natsschannel.go
  natss/pkg/reconciler/controller/natsschannel_test.go
  natss/pkg/reconciler/dispatcher/natsschannel.go
  natss/pkg/reconciler/dispatcher/natsschannel_test.go
  natss/pkg/reconciler/testing/factory.go
  natss/pkg/reconciler/testing/listers.go
  natss/pkg/util/util.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1044 Prune eventing-contrib/pkg/channel
  Gopkg.lock
  kafka/channel/pkg/dispatcher/dispatcher_benchmark_test.go
  pkg/channel/message.go
  pkg/channel/message_dispatcher.go
  pkg/channel/message_dispatcher_test.go
  pkg/channel/message_receiver.go
  pkg/channel/message_receiver_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#1039 Port KafkaChannel to new bindings API
  Gopkg.lock
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_benchmark_test.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  vendor/knative.dev/eventing/cmd/mtbroker/filter/kodata/HEAD
  vendor/knative.dev/eventing/cmd/mtbroker/filter/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/mtbroker/filter/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/mtbroker/filter/kodata/refs
  vendor/knative.dev/eventing/cmd/mtbroker/ingress/kodata/HEAD
  vendor/knative.dev/eventing/cmd/mtbroker/ingress/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/mtbroker/ingress/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/mtbroker/ingress/kodata/refs
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/200-filter-clusterrole.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/200-filter-serviceaccount.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/200-ingress-clusterrole.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/200-ingress-serviceaccount.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/201-filter-clusterrolebinding.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/201-ingress-clusterrolebinding.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/500-broker-filter.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/500-broker-ingress.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/500-mt-broker-controller.yaml
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/broker.go
  vendor/knative.dev/eventing/test/lib/resources/constants.go
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
Labels: approved, cla: yes, lgtm, size/XL

#1045 golang format tools
  natss/pkg/dispatcher/types.go
Labels: approved, cla: yes, lgtm, size/XS

#1043 Adding services and eventtypes rbac to sqssource clusterrole
  awssqs/config/201-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1047 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
Labels: approved, cla: yes, lgtm, size/M

#1059 fix webhook config to use svc in knative-sources ns
  github/config/500-webhook-configuration.yaml
  github/config/500-webhook.yaml
Labels: approved, cla: yes, lgtm, size/S

#1060 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/test/cmd/command.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_conversion.go
Labels: approved, cla: yes, lgtm, size/M

#1065 squash extra commas
  kafka/source/pkg/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/S

#1063 migrate prometheus off reconciler.Base
  prometheus/pkg/reconciler/controller.go
  prometheus/pkg/reconciler/prometheussource.go
Labels: approved, cla: yes, lgtm, size/M

#1064 migrate gitlab source to genreconciler and drop reconciler.Base
  Gopkg.lock
  gitlab/pkg/apis/sources/v1alpha1/gitlabsource_types.go
  gitlab/pkg/client/injection/reconciler/sources/v1alpha1/gitlabsource/controller.go
  gitlab/pkg/client/injection/reconciler/sources/v1alpha1/gitlabsource/reconciler.go
  gitlab/pkg/client/injection/reconciler/sources/v1alpha1/gitlabsource/stub/controller.go
  gitlab/pkg/client/injection/reconciler/sources/v1alpha1/gitlabsource/stub/reconciler.go
  gitlab/pkg/reconciler/controller.go
  gitlab/pkg/reconciler/gitlabsource.go
  third_party/VENDOR-LICENSE
  vendor/github.com/juju/errors/LICENSE
  vendor/github.com/juju/errors/doc.go
  vendor/github.com/juju/errors/error.go
  vendor/github.com/juju/errors/errortypes.go
  vendor/github.com/juju/errors/functions.go
  vendor/github.com/juju/errors/path.go
  vendor/knative.dev/eventing/pkg/reconciler/names/mtbroker.go
Labels: approved, cla: yes, lgtm, size/XXL

#1069 Add unit tests for comma split kafka adapter
  kafka/source/pkg/adapter/adapter_test.go
Labels: approved, cla: yes, lgtm, size/M

#1052 Update to manage the condition of GitHubSource webhook
  github/pkg/apis/sources/v1alpha1/githubsource_types.go
  github/pkg/apis/sources/v1alpha1/githubsource_types_test.go
  github/pkg/reconciler/githubsource.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1073 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/400-config-br-defaults.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/hpa.yaml
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/register.go
  vendor/knative.dev/eventing/pkg/channel/event_dispatcher.go
  vendor/knative.dev/eventing/pkg/channel/event_receiver.go
  vendor/knative.dev/eventing/pkg/kncloudevents/good_client.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_client.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/customresourcedefinition.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/listers.go
  vendor/knative.dev/eventing/test/lib/validation.go
  vendor/knative.dev/eventing/test/test_images/sendevents/main.go
  vendor/knative.dev/pkg/kvstore/kvstore.go
  vendor/knative.dev/pkg/kvstore/kvstore_cm.go
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/L

#1083 remove couchdb reconciler of reconciler.Base
  couchdb/source/pkg/reconciler/controller.go
  couchdb/source/pkg/reconciler/couchdbsource.go
Labels: approved, cla: yes, lgtm, size/M

#1088 install channel based broker
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1079 Migrate github source off reconciler.Base
  github/pkg/reconciler/controller.go
  github/pkg/reconciler/githubsource.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1093 Remove unused handler in KafkaDispatcher
  Gopkg.lock
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  vendor/knative.dev/eventing/pkg/channel/swappable/swappable.go
  vendor/knative.dev/eventing/pkg/channel/swappable/swappable_message_handler.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1092 Gitlab service wait removed
  gitlab/pkg/reconciler/gitlabsource.go
Labels: approved, cla: yes, lgtm, size/M

#1081 Migrate Kafka channel off reconciler.Base
  kafka/channel/cmd/channel_dispatcher/main.go
  kafka/channel/pkg/reconciler/controller/controller.go
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/controller/kafkachannel_test.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1095 latet Strimzi for e2e tests
  test/config/100-strimzi-cluster-operator-0.17.0.yaml
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL
