Repository knative/eventing-contrib, pull requests merged in 2020-07, with the labels that each got.

#1363 Pin knative.dev/{pkg,test-infra} to release-0.16
  awssqs/pkg/client/injection/reconciler/sources/v1alpha1/awssqssource/controller.go
  awssqs/pkg/client/injection/reconciler/sources/v1alpha1/awssqssource/reconciler.go
  camel/source/pkg/client/injection/reconciler/sources/v1alpha1/camelsource/controller.go
  camel/source/pkg/client/injection/reconciler/sources/v1alpha1/camelsource/reconciler.go
  couchdb/source/pkg/client/injection/reconciler/sources/v1alpha1/couchdbsource/controller.go
  couchdb/source/pkg/client/injection/reconciler/sources/v1alpha1/couchdbsource/reconciler.go
  github/pkg/client/injection/reconciler/sources/v1alpha1/githubsource/controller.go
  github/pkg/client/injection/reconciler/sources/v1alpha1/githubsource/reconciler.go
  gitlab/pkg/client/injection/reconciler/sources/v1alpha1/gitlabsource/controller.go
  gitlab/pkg/client/injection/reconciler/sources/v1alpha1/gitlabsource/reconciler.go
  go.mod
  go.sum
  hack/update-deps.sh
  kafka/channel/pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/controller.go
  kafka/channel/pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/reconciler.go
  kafka/source/pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/controller.go
  kafka/source/pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/reconciler.go
  kafka/source/pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/controller.go
  kafka/source/pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/reconciler.go
  kafka/source/pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/controller.go
  kafka/source/pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/reconciler.go
  kafka/source/pkg/client/injection/reconciler/sources/v1beta1/kafkasource/controller.go
  kafka/source/pkg/client/injection/reconciler/sources/v1beta1/kafkasource/reconciler.go
  natss/pkg/client/injection/reconciler/messaging/v1alpha1/natsschannel/controller.go
  natss/pkg/client/injection/reconciler/messaging/v1alpha1/natsschannel/reconciler.go
  prometheus/pkg/client/injection/reconciler/sources/v1alpha1/prometheussource/controller.go
  prometheus/pkg/client/injection/reconciler/sources/v1alpha1/prometheussource/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_data_plane_helper.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/send_event.go
  vendor/knative.dev/eventing/test/lib/sender/events.go
  vendor/knative.dev/eventing/test/lib/sender/resources.go
  vendor/knative.dev/eventing/test/test_images/event-sender/main.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/knative.dev/eventing/test/test_images/transformevents/main.go
  vendor/knative.dev/eventing/test/test_images/utils.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1359 Adding v1beta1 to Kafka Source/Binding CRDs
  kafka/source/config/300-kafkabinding.yaml
  kafka/source/config/300-kafkasource.yaml
Labels: approved, cla: yes, lgtm, size/L

#1365 Updates
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1366 KafkaChannel validation tweak
  kafka/channel/config/300-kafka-channel.yaml
Labels: approved, cla: yes, lgtm, size/M

#1367 Channelable for kafka types
  kafka/channel/pkg/apis/messaging/v1beta1/kafka_channel_lifecycle_test.go
  kafka/channel/pkg/apis/messaging/v1beta1/kafka_channel_types.go
  kafka/channel/pkg/apis/messaging/v1beta1/kafka_channel_types_test.go
  kafka/channel/pkg/apis/messaging/v1beta1/kafka_channel_validation.go
  kafka/channel/pkg/apis/messaging/v1beta1/kafka_channel_validation_test.go
  kafka/channel/pkg/apis/messaging/v1beta1/zz_generated.deepcopy.go
  kafka/channel/pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/controller.go
  kafka/channel/pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
Labels: approved, cla: yes, lgtm, size/L

#1368 Adding the v1beta1 to the CRD
  kafka/channel/config/300-kafka-channel.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1373 Workaround for missing monitoring namespace
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1371 Kafka channel v1beta1<>v1alpha1 conversion
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_conversion.go
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_conversion_test.go
  kafka/channel/pkg/apis/messaging/v1beta1/kafka_channel_conversion.go
  kafka/channel/pkg/apis/messaging/v1beta1/kafka_channel_conversion_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1374 Kafkachannel conversion webhook
  kafka/channel/cmd/webhook/main.go
  kafka/channel/config/200-webhook-clusterrole.yaml
  kafka/channel/pkg/apis/messaging/register.go
Labels: approved, cla: yes, lgtm, size/M

#1377 Add aliok to reviewers list
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1380 Use portable bash environment in shell scripts
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1379 KafkaSource/KafkaBinding v1beta1 e2e
  test/e2e/kafka_binding_test.go
  test/e2e/kafka_source_test.go
  test/lib/creation.go
  test/lib/resources/kafka.go
  test/performance/source-kafka/101-source-perf-setup.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1381 GitHubSourceSpec inherits duck.SourceSpec
  github/config/core/300-githubsource.yaml
  github/pkg/apis/sources/v1alpha1/githubsource_types.go
  github/pkg/apis/sources/v1alpha1/githubsource_validation.go
  github/pkg/apis/sources/v1alpha1/githubsource_validation_test.go
  github/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/S

#1383 Change abd4lla to devguyio due to username change
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1384 Pin to knative.dev/{eventing,serving}@release-16
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1392 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/duck/resource_inspectors.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1398 Fix KafkaChannel conversion
  kafka/channel/config/300-kafka-channel.yaml
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_conversion.go
Labels: approved, cla: yes, lgtm, size/M

#1400 Fix minor typo
  kafka/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1378 KafkaChannel v1beta1 e2e
  test/conformance/README.md
  test/e2e-tests.sh
  test/performance/broker-kafka/100-broker-perf-setup.yaml
  test/performance/channel-kafka/100-channel-perf-setup.yaml
  test/performance/channel-kafka/101-channel-perf-setup.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1155 KafkaChannel Tracing
  go.mod
  go.sum
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_it_test.go
  kafka/channel/pkg/dispatcher/tracing.go
  kafka/channel/pkg/dispatcher/tracing_test.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  test/config/config-tracing.yaml
  test/conformance/channel_tracing_test.go
  test/e2e-tests.sh
  vendor/go.opencensus.io/plugin/ocgrpc/client_metrics.go
  vendor/go.opencensus.io/plugin/ocgrpc/server_metrics.go
  vendor/go.opencensus.io/plugin/ochttp/propagation/tracecontext/propagation.go
  vendor/go.opencensus.io/stats/view/aggregation.go
  vendor/go.opencensus.io/stats/view/aggregation_data.go
  vendor/go.opencensus.io/stats/view/collector.go
  vendor/go.opencensus.io/stats/view/view_to_metric.go
  vendor/go.opencensus.io/stats/view/worker.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1402 Assorted linting fixes.
  github/pkg/mtadapter/adapter_test.go
  github/pkg/mtadapter/router_test.go
  github/pkg/reconciler/source/fake_webhook_client_test.go
  github/pkg/reconciler/source/githubsource.go
  kafka/source/pkg/adapter/message.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_conversion.go
Labels: approved, cla: yes, lgtm, size/M

#1403 Updated deps
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1405 Kafkasource v1beta1 reconciler
  kafka/source/pkg/adapter/adapter_test.go
  kafka/source/pkg/adapter/message.go
  kafka/source/pkg/apis/sources/v1beta1/kafka_lifecycle.go
  kafka/source/pkg/reconciler/binding/controller.go
  kafka/source/pkg/reconciler/source/controller.go
  kafka/source/pkg/reconciler/source/kafkasource.go
  kafka/source/pkg/reconciler/source/resources/receive_adapter.go
  kafka/source/pkg/reconciler/source/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/L

#1411 Migrate KafkaChannel dispatcher reconciler to new generated reconciler
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
Labels: approved, cla: yes, lgtm, size/M

#1415 Update CloudEvents SDK to v2.2.0
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/protocol/kafka_sarama/v2/go.mod
  vendor/github.com/cloudevents/sdk-go/protocol/kafka_sarama/v2/go.sum
  vendor/github.com/cloudevents/sdk-go/protocol/kafka_sarama/v2/sender.go
  vendor/github.com/cloudevents/sdk-go/protocol/stan/v2/go.mod
  vendor/github.com/cloudevents/sdk-go/protocol/stan/v2/go.sum
  vendor/github.com/cloudevents/sdk-go/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_validation.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/result.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/write_request.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/result.go
  vendor/github.com/cloudevents/sdk-go/v2/test/event_mocks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1409 Kafka Channel retries sending events
  kafka/channel/pkg/dispatcher/dispatcher.go
  test/config.go
  test/e2e/broker_redelivery_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1417 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_netbsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm64.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_conversion.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/trigger.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1420 [master] Auto-update dependencies
  awssqs/pkg/client/injection/reconciler/sources/v1alpha1/awssqssource/reconciler.go
  awssqs/pkg/client/injection/reconciler/sources/v1alpha1/awssqssource/state.go
  camel/source/pkg/client/injection/reconciler/sources/v1alpha1/camelsource/reconciler.go
  camel/source/pkg/client/injection/reconciler/sources/v1alpha1/camelsource/state.go
  couchdb/source/pkg/client/injection/reconciler/sources/v1alpha1/couchdbsource/reconciler.go
  couchdb/source/pkg/client/injection/reconciler/sources/v1alpha1/couchdbsource/state.go
  github/pkg/client/injection/reconciler/sources/v1alpha1/githubsource/reconciler.go
  github/pkg/client/injection/reconciler/sources/v1alpha1/githubsource/state.go
  gitlab/pkg/client/injection/reconciler/sources/v1alpha1/gitlabsource/reconciler.go
  gitlab/pkg/client/injection/reconciler/sources/v1alpha1/gitlabsource/state.go
  go.mod
  go.sum
  kafka/channel/pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/reconciler.go
  kafka/channel/pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/state.go
  kafka/channel/pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
  kafka/channel/pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/state.go
  kafka/source/pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/reconciler.go
  kafka/source/pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/state.go
  kafka/source/pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/reconciler.go
  kafka/source/pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/state.go
  kafka/source/pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/reconciler.go
  kafka/source/pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/state.go
  kafka/source/pkg/client/injection/reconciler/sources/v1beta1/kafkasource/reconciler.go
  kafka/source/pkg/client/injection/reconciler/sources/v1beta1/kafkasource/state.go
  natss/pkg/client/injection/reconciler/messaging/v1alpha1/natsschannel/reconciler.go
  natss/pkg/client/injection/reconciler/messaging/v1alpha1/natsschannel/state.go
  prometheus/pkg/client/injection/reconciler/sources/v1alpha1/prometheussource/reconciler.go
  prometheus/pkg/client/injection/reconciler/sources/v1alpha1/prometheussource/state.go
  vendor/knative.dev/eventing/pkg/adapter/v2/test/test_client.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_control_plane_test_helper.go
  vendor/knative.dev/eventing/test/lib/operation.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
