Repository knative/eventing-contrib, pull requests merged in 2020-06, with the labels that each got.

#1290 Receive adapter now starts in a context
  ceph/pkg/adapter/adapter.go
  ceph/pkg/adapter/adapter_test.go
  couchdb/source/pkg/adapter/adapter.go
  couchdb/source/pkg/adapter/adapter_test.go
  github/pkg/adapter/adapter.go
  github/pkg/adapter/adapter_test.go
  gitlab/pkg/adapter/receive_adapter.go
  gitlab/pkg/adapter/receive_adapter_test.go
  go.mod
  go.sum
  kafka/source/pkg/adapter/adapter.go
  kafka/source/pkg/adapter/adapter_test.go
  prometheus/pkg/adapter/adapter.go
  prometheus/pkg/adapter/adapter_test.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/test/gcs/client.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/gcs/helpers.go
  vendor/knative.dev/pkg/test/prow/prow.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1292 More conformance tests
  test/conformance/channel_addressable_resolver_cluster_role_test.go
  test/conformance/channel_status_subscriber_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1289 Do not use 8080 as a test port
  github/pkg/adapter/adapter.go
  github/pkg/adapter/adapter_test.go
  gitlab/pkg/adapter/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1287 Update go.mod to specify the module is go1.14
  go.mod
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1225 Add PrometheusSource webhook
  prometheus/cmd/webhook/main.go
  prometheus/config/200-serviceaccount.yaml
  prometheus/config/202-clusterrolebinding.yaml
  prometheus/config/203-webhook-clusterrole.yaml
  prometheus/config/500-webhook-config.yaml
  prometheus/config/500-webhook.yaml
  prometheus/pkg/apis/sources/v1alpha1/prometheus_defaults.go
  prometheus/pkg/apis/sources/v1alpha1/prometheus_defaults_test.go
  prometheus/pkg/apis/sources/v1alpha1/prometheus_validation.go
  prometheus/pkg/apis/sources/v1alpha1/prometheus_validation_test.go
  prometheus/pkg/apis/sources/v1alpha1/prometheussource_types.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1298 bring new eventing bits, remove ref to eventing.v1alpha1
  awssqs/pkg/apis/addtoscheme_eventing_v1alpha1.go
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtype_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtype_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtype_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtype_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/test_helper.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_defaults.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/broker.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_broker.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_trigger.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/trigger.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/parallel.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/e2e-tests.sh
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_dls_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_with_config_helper.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/knative.dev/eventing/test/lib/resources/serving.go
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1303 [master] golang format tools
  hack/tools.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1304 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/certificate_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/serverlessservice_lifecycle.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1312 Ported KafkaBinding test to new test images
  go.mod
  kafka/source/pkg/adapter/adapter_test.go
  test/e2e/kafka_binding_test.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1311 Improve KafkaSource e2e tests
  go.mod
  go.sum
  kafka/client.go
  kafka/client_test.go
  kafka/source/config/config-observability.yaml
  kafka/source/pkg/adapter/adapter.go
  kafka/source/pkg/adapter/message.go
  test/e2e/helpers/kafka_helper.go
  test/e2e/kafka_source_test.go
  test/lib/resources/kafka.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1313 Port CamelSource to new test images
  test/e2e/camel_source_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1315 [master] Auto-update dependencies
  awssqs/pkg/client/injection/reconciler/sources/v1alpha1/awssqssource/reconciler.go
  camel/source/pkg/client/injection/reconciler/sources/v1alpha1/camelsource/reconciler.go
  couchdb/source/pkg/client/injection/reconciler/sources/v1alpha1/couchdbsource/reconciler.go
  github/pkg/client/injection/reconciler/sources/v1alpha1/githubsource/reconciler.go
  gitlab/pkg/client/injection/reconciler/sources/v1alpha1/gitlabsource/reconciler.go
  go.mod
  go.sum
  kafka/channel/pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/reconciler.go
  kafka/source/pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/reconciler.go
  kafka/source/pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/reconciler.go
  natss/pkg/client/injection/reconciler/messaging/v1alpha1/natsschannel/reconciler.go
  prometheus/pkg/client/injection/reconciler/sources/v1alpha1/prometheussource/reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1316 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/ghutil/client.go
  vendor/knative.dev/pkg/test/ghutil/repo.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1314 KafkaSource: Fixed wrong error logging during reconciliation
  kafka/source/pkg/reconciler/source/kafkasource.go
Labels: approved, cla: yes, lgtm, size/S

#1318 Fix missing error return
  kafka/source/pkg/reconciler/source/kafkasource.go
Labels: approved, cla: yes, lgtm, size/XS

#1320 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1305 Assorted linting fixes.
  github/pkg/adapter/adapter.go
  github/pkg/adapter/adapter_test.go
  github/pkg/reconciler/source/githubsource.go
  gitlab/pkg/adapter/receive_adapter_test.go
  gitlab/pkg/reconciler/source/controller.go
Labels: approved, cla: yes, lgtm, size/S

#1321 Updated eventing removing the old test images
  go.mod
  go.sum
  hack/tools.go
  test/e2e/broker_channel_flow_test.go
  test/e2e/broker_dls_test.go
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_header_single_event_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_subscriber_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_chain_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/parallel_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/performance_image_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/sequence_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/trigger_no_broker_test_helper.go
  vendor/knative.dev/eventing/test/lib/cloudevents.go
  vendor/knative.dev/eventing/test/lib/cloudevents/cloud_events.go
  vendor/knative.dev/eventing/test/lib/config.go
  vendor/knative.dev/eventing/test/lib/operation.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_matchers.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/resources/kube.go
  vendor/knative.dev/eventing/test/lib/resources/sender/sender.go
  vendor/knative.dev/eventing/test/lib/send_event.go
  vendor/knative.dev/eventing/test/lib/validation.go
  vendor/knative.dev/eventing/test/performance/infra/receiver/receiver.go
  vendor/knative.dev/eventing/test/test_images/event-sender/main.go
  vendor/knative.dev/eventing/test/test_images/eventdetails/README.md
  vendor/knative.dev/eventing/test/test_images/eventdetails/main.go
  vendor/knative.dev/eventing/test/test_images/eventdetails/pod.yaml
  vendor/knative.dev/eventing/test/test_images/filterevents/main.go
  vendor/knative.dev/eventing/test/test_images/heartbeats/main.go
  vendor/knative.dev/eventing/test/test_images/logevents/main.go
  vendor/knative.dev/eventing/test/test_images/logevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/sendevents/main.go
  vendor/knative.dev/eventing/test/test_images/sendevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/transformevents/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1323 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1327 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/k8s.io/kube-openapi/cmd/openapi-gen/openapi-gen.go
  vendor/knative.dev/pkg/hack/tools.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/metrics/testing.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1324 CAMEL-14575, time pattern dropped in Camel 3.2
  test/e2e/camel_source_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#1334 Enable sources conformance tests and add Source CRD Metadata test
  test/conformance/main_test.go
  test/conformance/source_crd_metadata_test.go
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1335 Use CloudEvents 1.0 in GitLabSource
  gitlab/pkg/adapter/receive_adapter.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#1336 Using latest strimzi
  test/config/100-kafka-ephemeral-triple-2.5.0.yaml
  test/config/100-strimzi-cluster-operator-0.18.0.yaml
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1338 [master] golang format tools
  kafka/source/pkg/apis/sources/v1alpha1/kafka_conversion.go
  kafka/source/pkg/apis/sources/v1beta1/kafka_conversion.go
Labels: approved, cla: yes, lgtm, size/XS

#1341 KafkaSource and binding v1beta1<>v1alpha1 conversion
  go.mod
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_conversion.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_conversion_test.go
  kafka/source/pkg/apis/bindings/v1beta1/kafka_conversion.go
  kafka/source/pkg/apis/bindings/v1beta1/kafka_conversion_test.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_conversion.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_conversion_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1345 Update to the latest release of the CloudEvents SDK - 2.1
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/protocol/kafka_sarama/v2/go.mod
  vendor/github.com/cloudevents/sdk-go/protocol/kafka_sarama/v2/go.sum
  vendor/github.com/cloudevents/sdk-go/protocol/stan/v2/go.mod
  vendor/github.com/cloudevents/sdk-go/protocol/stan/v2/go.sum
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/client/http_receiver.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/result.go
  vendor/github.com/cloudevents/sdk-go/v2/test/event_matchers.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1349 KafkaSource/KafkaBinding conversion webhook
  kafka/source/cmd/controller/main.go
  kafka/source/config/201-clusterrole.yaml
  kafka/source/pkg/apis/bindings/register.go
  kafka/source/pkg/apis/sources/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/expansion_generated.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/apiextensions/v1/customresourcedefinition/customresourcedefinition.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/factory/factory.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1357 [master] golang format tools
  kafka/source/cmd/controller/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1358 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_conversion.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/parallel_conversion.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/sequence_conversion.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_conversion.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_conversion.go
  vendor/knative.dev/eventing/pkg/channel/message_receiver.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_message_modes_specversion_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-upgrade-tests.sh
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/parallel_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/sequence_test_helper.go
  vendor/knative.dev/eventing/test/e2e_flags.go
  vendor/knative.dev/eventing/test/flags/eventing_environment.go
  vendor/knative.dev/eventing/test/lib/operation.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_matchers.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/send_event.go
  vendor/knative.dev/eventing/test/test_images/event-sender/main.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/leaderelection/ordinal.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1361 Add missing PromoteFunc for bindings
  github/pkg/reconciler/binding/controller.go
  gitlab/pkg/reconciler/binding/controller.go
  kafka/source/pkg/reconciler/binding/controller.go
Labels: approved, cla: yes, lgtm, size/M

#1364 update eventing, fix tests to cover v1/v1beta1 broker/trigger matrix
  go.mod
  go.sum
  test/e2e/broker_channel_flow_test.go
  test/e2e/broker_event_transformation_test.go
  third_party/VENDOR-LICENSE/github.com/pmezard/go-difflib/difflib/LICENSE
  third_party/VENDOR-LICENSE/github.com/stretchr/testify/LICENSE
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/test_helper.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_conversion.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/parallel_conversion.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_header_single_event_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_message_modes_specversion_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/zipkin.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/knative.dev/eventing/test/lib/send_event.go
  vendor/knative.dev/eventing/test/lib/sender/events.go
  vendor/knative.dev/eventing/test/lib/sender/matchers.go
  vendor/knative.dev/eventing/test/lib/sender/resources.go
  vendor/knative.dev/eventing/test/lib/tracing/config.go
  vendor/knative.dev/eventing/test/test_images/event-sender/main.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/knative.dev/eventing/test/test_images/transformevents/main.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/test-infra/scripts/dummy.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL
