Repository knative/eventing-contrib, pull requests merged in 2020-09, with the labels that each got.

#1525 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/channel_spec_test_helper.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1526 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1529 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/listers.go
  vendor/knative.dev/eventing/test/e2e-conformance-tests.sh
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_validation.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1531 [master] Auto-update dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/knative.dev/networking/pkg/LICENSE
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/bufferpool.go
  vendor/knative.dev/networking/pkg/doc.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/networking/pkg/probe_handler.go
  vendor/knative.dev/networking/pkg/stats.go
  vendor/knative.dev/networking/pkg/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/service_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1534 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1535 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#1537 Updating deps
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1536 Fix Kafka Channel dispatcher ownerRef
  kafka/channel/config/500-dispatcher.yaml
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/controller/kafkachannel_test.go
  kafka/channel/pkg/reconciler/controller/resources/dispatcher.go
  kafka/channel/pkg/reconciler/controller/resources/dispatcher_test.go
  kafka/channel/pkg/utils/util.go
  kafka/channel/pkg/utils/util_test.go
Labels: approved, cla: yes, lgtm, size/L

#1540 Remove master terminology
  github/cmd/mt_receive_adapter/main.go
Labels: approved, cla: yes, lgtm, size/S

#1541 Fixing typo
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
Labels: approved, cla: yes, lgtm, size/XS

#1543 Add linting config and fix issues.
  .golangci.yaml
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
Labels: approved, cla: yes, lgtm, size/M

#1544 Better grouping of config for source
  kafka/source/config/201-clusterrole.yaml
  kafka/source/config/300-kafkabinding.yaml
  kafka/source/config/300-kafkasource.yaml
  kafka/source/config/400-controller-service.yaml
  kafka/source/config/500-controller.yaml
  kafka/source/config/500-webhook-configuration.yaml
  kafka/source/config/config-leader-election.yaml
  kafka/source/config/config-observability.yaml
  kafka/source/config/configmaps/leader-election.yaml
  kafka/source/config/configmaps/observability.yaml
  kafka/source/config/deployments/controller-service.yaml
  kafka/source/config/deployments/controller.yaml
  kafka/source/config/resources/kafkabinding.yaml
  kafka/source/config/resources/kafkasource.yaml
  kafka/source/config/roles/clusterrole.yaml
  kafka/source/config/webhooks/kafka.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1546 Updating to latest Strimzi version
  test/config/100-strimzi-cluster-operator-0.19.0.yaml
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1551 Allow access to the coordination API for leader election
  github/config/core/203-webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1553 Allow access to the coordination API for leader election (#1551)
  github/config/core/203-webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1533 delete ra deployment when sink is not found
  kafka/source/pkg/reconciler/source/kafkasource.go
  test/e2e-tests.sh
  test/e2e/helpers/kafka_helper.go
  test/e2e/kafka_source_reconciler_test.go
  test/lib/deletion.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1545 Better grouping of config for channel
  kafka/channel/config/200-addressable-resolver-clusterrole.yaml
  kafka/channel/config/200-channelable-manipulator-clusterrole.yaml
  kafka/channel/config/200-controller-clusterrole.yaml
  kafka/channel/config/200-dispatcher-clusterrole.yaml
  kafka/channel/config/200-webhook-clusterrole.yaml
  kafka/channel/config/300-kafka-channel.yaml
  kafka/channel/config/400-kafka-config.yaml
  kafka/channel/config/400-leader-election-config.yaml
  kafka/channel/config/400-webhook-service.yaml
  kafka/channel/config/500-controller.yaml
  kafka/channel/config/500-dispatcher.yaml
  kafka/channel/config/500-webhook-configuration.yaml
  kafka/channel/config/500-webhook.yaml
  kafka/channel/config/configmaps/kafka-config.yaml
  kafka/channel/config/configmaps/leader-election.yaml
  kafka/channel/config/deployments/controller.yaml
  kafka/channel/config/deployments/dispatcher.yaml
  kafka/channel/config/deployments/webhook-service.yaml
  kafka/channel/config/deployments/webhook.yaml
  kafka/channel/config/resources/kafka-channel.yaml
  kafka/channel/config/roles/addressable-resolver-clusterrole.yaml
  kafka/channel/config/roles/channelable-manipulator-clusterrole.yaml
  kafka/channel/config/roles/controller-clusterrole.yaml
  kafka/channel/config/roles/dispatcher-clusterrole.yaml
  kafka/channel/config/roles/webhook-clusterrole.yaml
  kafka/channel/config/webhooks/webhook-configuration.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1547 [master] golang format tools
  kafka/channel/pkg/utils/util.go
  kafka/channel/pkg/utils/util_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1559 Fix camelsource unit test for sink not found
  camel/source/pkg/reconciler/camelsource_test.go
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/parallel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/sequence_defaults.go
  vendor/knative.dev/eventing/pkg/utils/headers.go
  vendor/knative.dev/eventing/test/conformance/helpers/sources/source_status_test_helper.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/performance/infra/aggregator/aggregator.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/ghutil/pullrequest.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_conversion.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1552 allow access to coordination API for leader election
  couchdb/source/config/201-webhook-clusterrole.yaml
  gitlab/config/203-webhook-clusterrole.yaml
  prometheus/config/203-webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/S

#1565 Adding comment on API access
  kafka/source/config/roles/clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1566 Use webhook.PortFromEnv
  kafka/channel/cmd/webhook/main.go
Labels: approved, cla: yes, lgtm, size/S

#1567 [Backport 0.16] Fix KafkaChannel conversion (#1398)
  kafka/channel/config/300-kafka-channel.yaml
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_conversion.go
Labels: approved, cla: yes, lgtm, size/M

#1575 Fix the red CI
  go.mod
  go.sum
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_conversion.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_control_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_validation.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1568 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#1570 Removing PVCs from clusterrole
  kafka/source/config/roles/clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1578 [master] Update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1579 Remove the unneeded kafka topic setup and yamls
  test/config/100-kafka-topic.yaml
  test/e2e-tests.sh
  test/e2e/kafka_source_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1582 Adding DSL e2e test
  test/e2e/channel_dls_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1588 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1585 Drop Ceph Source
  README.md
  ceph/README.md
  ceph/cmd/receive_adapter/main.go
  ceph/pkg/adapter/adapter.go
  ceph/pkg/adapter/adapter_test.go
  ceph/pkg/apis/v1alpha1/bucket_notification_types.go
  ceph/samples/ceph-bucket-notification-svc.yaml
  ceph/samples/ceph-display-resources.yaml
  ceph/samples/ceph-eventing-ns.yaml
  ceph/samples/ceph-source.yaml
  ceph/samples/records.json
  ceph/samples/test-pod.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1574 remove camel from release
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1597 [master] Update GitHub Actions
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#1602 Backport #1575
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_conversion.go
Labels: approved, cla: yes, lgtm, size/M

#1601 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1607 [Release] Pin upstreams for release 0.18
  hack/update-deps.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1606 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/container_validation.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/pkg/tracing/setup.go
  vendor/knative.dev/eventing/test/lib/duck/resource_checks.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1605 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#1608 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1612 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_redelivery_helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1611 [Automated] Fix misspellings
  test/config/100-strimzi-cluster-operator-0.19.0.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1614 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1609 [release-0.17] Update deps release-0.17 eventing
  go.mod
  go.sum
  test/config.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_redelivery_helper.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1615 Add aliok to approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1618 [release-0.18] Remove SQS Source from release artifacts
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1610 Add pierDipi to approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1620 clean up redundancies code with knative/pkg
  kafka/channel/pkg/reconciler/controller/kafkachannel_test.go
  kafka/channel/pkg/reconciler/controller/resources/service.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S
