Repository knative/eventing-contrib, pull requests merged in 2020-01, with the labels that each got.

#807 Fix #805: add duck.InformerFactory to camel source context
  camel/source/pkg/reconciler/camelsource.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#819 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_lifecycle.go
  vendor/knative.dev/pkg/metrics/README.md
  vendor/knative.dev/pkg/profiling/server.go
Labels: approved, cla: yes, lgtm, size/M

#814 Kafka: can we just use the uid and not name
  kafka/channel/pkg/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, size/XS

#826 Adding webhook support for github source.
  github/cmd/webhook/main.go
  github/config/200-serviceaccount.yaml
  github/config/300-githubsource.yaml
  github/config/500-webhook-configuration.yaml
  github/config/500-webhook.yaml
  github/pkg/apis/sources/v1alpha1/githubsource_defaults.go
  github/pkg/apis/sources/v1alpha1/githubsource_defaults_test.go
  github/pkg/apis/sources/v1alpha1/githubsource_types.go
  github/pkg/apis/sources/v1alpha1/githubsource_validation.go
  github/pkg/apis/sources/v1alpha1/githubsource_validation_test.go
Labels: approved, cla: yes, lgtm, size/L

#825 Updating pkg to latest for 0.12 release.
  Gopkg.lock
  Gopkg.toml
  third_party/VENDOR-LICENSE
  vendor/contrib.go.opencensus.io/exporter/ocagent/LICENSE
  vendor/contrib.go.opencensus.io/exporter/ocagent/common.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/connection.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/nodeinfo.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/ocagent.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/options.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/transform_spans.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/version.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/metrics/v1/metrics_service.pb.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/metrics/v1/metrics_service.pb.gw.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/trace/v1/trace_service.pb.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/trace/v1/trace_service.pb.gw.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1/trace.pb.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1/trace_config.pb.go
  vendor/github.com/golang/protobuf/descriptor/descriptor.go
  vendor/github.com/golang/protobuf/jsonpb/jsonpb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/LICENSE.txt
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/doc.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/fieldmask.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_httpbodyproto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_json.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_jsonpb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_proto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler_registry.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/pattern.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto2_convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto_errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/query.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/LICENSE
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/doc.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/pattern.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/readerfactory.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/trie.go
  vendor/google.golang.org/genproto/googleapis/api/httpbody/httpbody.pb.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/configmap/informed_watcher.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/system/env.go
  vendor/knative.dev/pkg/test/gke/endpoint.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/main.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
Labels: approved, cla: yes, lgtm, size/XXL

#831 golang format tools
  github/pkg/apis/sources/v1alpha1/githubsource_defaults_test.go
  github/pkg/apis/sources/v1alpha1/githubsource_types.go
Labels: approved, cla: yes, lgtm, size/XS

#830 Good client
  Gopkg.lock
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  kafka/channel/pkg/utils/util.go
  kafka/channel/pkg/utils/util_test.go
Labels: approved, cla: yes, lgtm, size/L

#824 NatssChannel Dispatcher: prioritize finalizer removal
  natss/pkg/dispatcher/dispatcher.go
  natss/pkg/dispatcher/testing/testing.go
  natss/pkg/reconciler/controller/natsschannel.go
  natss/pkg/reconciler/controller/natsschannel_test.go
  natss/pkg/reconciler/dispatcher/natsschannel.go
  natss/pkg/reconciler/dispatcher/natsschannel_test.go
  natss/pkg/reconciler/testing/natsschannel.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#837 golang format tools
  natss/pkg/dispatcher/testing/testing.go
  natss/pkg/reconciler/dispatcher/natsschannel_test.go
Labels: approved, cla: yes, lgtm, size/S

#840 Update the dependency on sdk-go to match eventing repo
  Gopkg.lock
  Gopkg.toml
  kafka/channel/pkg/dispatcher/dispatcher.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_marshal.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v1.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/extensions.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/types/value.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/legacysources/v1alpha1/deprecated.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_dls_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_chain_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
Labels: approved, cla: yes, lgtm, size/L

#838 Updating pkg to master post 0.12 release.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/RELEASING.md
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/test/junit/junit.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/tools/tools.go
  vendor/knative.dev/pkg/testutils/junithelper/README.md
  vendor/knative.dev/pkg/testutils/junithelper/main.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/L

#843 applying defaults for empty flieds :lipstick:
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
Labels: approved, cla: yes, lgtm, size/XS

#844 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/doc.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/doc.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/register.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscribable_channelable_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/channel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/fake/fake_channel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/fake/fake_inmemorychannel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/fake/fake_messaging_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/fake/fake_subscription.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/inmemorychannel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/messaging_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/subscription.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/messaging/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/messaging/v1beta1/channel.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/messaging/v1beta1/inmemorychannel.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/messaging/v1beta1/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/messaging/v1beta1/subscription.go
  vendor/knative.dev/eventing/pkg/client/listers/messaging/v1beta1/channel.go
  vendor/knative.dev/eventing/pkg/client/listers/messaging/v1beta1/expansion_generated.go
  vendor/knative.dev/eventing/pkg/client/listers/messaging/v1beta1/inmemorychannel.go
  vendor/knative.dev/eventing/pkg/client/listers/messaging/v1beta1/subscription.go
  vendor/knative.dev/pkg/apis/convert.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XXL

#847 Update test-infra to the latest
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XS

#845 applying defaults for empty flieds
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
Labels: approved, cla: yes, lgtm, size/XS

#850 Added Kafka headers to event generated from KafkaSource
  kafka/source/pkg/adapter/adapter.go
  kafka/source/pkg/adapter/adapter_test.go
Labels: approved, cla: yes, lgtm, size/L

#854 Fix spelling errors
  test/test_images/kafka_performance/kafka_load_generator_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#855 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/config/300-apiserversource.yaml
  vendor/knative.dev/eventing/config/300-pingsource.yaml
  vendor/knative.dev/eventing/config/300-sinkbindings.yaml
  vendor/knative.dev/eventing/config/500-webhook-legacysinkbindings.yaml
Labels: approved, cla: yes, lgtm, size/S

#856 add missing resource needed by the Kafka webhook
  kafka/channel/config/200-webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#858 add missing resource needed by the Kafka webhook
  kafka/channel/config/200-webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#859 read and watch Kafka configmap instead of mounting config
  Gopkg.lock
  kafka/channel/config/500-controller.yaml
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_lifecycle.go
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_lifecycle_test.go
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/controller/kafkachannel_test.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  kafka/channel/pkg/reconciler/testing/kafkachannel.go
  kafka/channel/pkg/utils/util.go
  kafka/channel/pkg/utils/util_test.go
Labels: approved, cla: yes, lgtm, size/L

#860 Implemented key deserializers in KafkaSource
  kafka/source/pkg/adapter/adapter.go
  kafka/source/pkg/adapter/adapter_benchmark_test.go
  kafka/source/pkg/adapter/adapter_test.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_types.go
  kafka/source/pkg/reconciler/kafkasource.go
  kafka/source/pkg/reconciler/resources/receive_adapter.go
  kafka/source/pkg/reconciler/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/L

#869 move to sources.knative.dev group
  couchdb/README.md
  couchdb/source/config/201-clusterrole.yaml
  couchdb/source/config/201-webhook-clusterrole.yaml
  couchdb/source/config/300-couchdbsource.yaml
  couchdb/source/pkg/apis/sources/v1alpha1/doc.go
  couchdb/source/pkg/apis/sources/v1alpha1/register.go
  couchdb/source/pkg/apis/sources/v1alpha1/register_test.go
  couchdb/source/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_couchdbsource.go
  couchdb/source/pkg/client/clientset/versioned/typed/sources/v1alpha1/sources_client.go
  couchdb/source/pkg/client/informers/externalversions/generic.go
  couchdb/source/pkg/reconciler/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/S

#877 GitHub webhook rbac clusterrole
  github/config/202-clusterrolebinding.yaml
  github/config/203-webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/L

#871 create Kafka dispatcher on-demand
  Gopkg.lock
  kafka/channel/config/200-controller-clusterrole.yaml
  kafka/channel/config/200-dispatcher-service.yaml
  kafka/channel/config/500-controller.yaml
  kafka/channel/config/500-dispatcher.yaml
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_lifecycle.go
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/controller/kafkachannel_test.go
  kafka/channel/pkg/reconciler/controller/resources/dispatcher.go
  kafka/channel/pkg/reconciler/controller/resources/dispatcher_service.go
  kafka/channel/pkg/reconciler/controller/resources/dispatcher_service_test.go
  kafka/channel/pkg/reconciler/controller/resources/dispatcher_test.go
  kafka/channel/pkg/reconciler/controller/resources/service_test.go
Labels: approved, cla: yes, lgtm, size/XL
