Repository knative/eventing-contrib, pull requests merged in 2020-08, with the labels that each got.

#1428 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/state.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/state.go
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1437 Add a name for the port
  kafka/source/config/500-controller.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1438 Export logs from system namespace
  test/conformance/main_test.go
  test/conformance/source_crd_metadata_test.go
  test/conformance/source_status_test.go
  test/e2e/main_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1445 Prune eventTracker.Cleanup()
  test/e2e/camel_source_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1407 KafkaChannel reconciler to use KafkaChannel v1beta1 API
  kafka/channel/README.md
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_defaults.go
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_defaults_test.go
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_it_test.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
  kafka/channel/pkg/reconciler/controller/controller.go
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/controller/kafkachannel_test.go
  kafka/channel/pkg/reconciler/controller/resources/service.go
  kafka/channel/pkg/reconciler/controller/resources/service_test.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  kafka/channel/pkg/reconciler/testing/kafkachannel.go
  kafka/channel/pkg/reconciler/testing/listers.go
  test/e2e/broker_redelivery_test.go
  test/e2e/channel_single_event_test.go
  third_party/VENDOR-LICENSE/github.com/valyala/bytebufferpool/LICENSE
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/acks_before_finish_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/binary_buffer_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/copy_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/struct_buffer_message.go
  vendor/github.com/valyala/bytebufferpool/.travis.yml
  vendor/github.com/valyala/bytebufferpool/LICENSE
  vendor/github.com/valyala/bytebufferpool/README.md
  vendor/github.com/valyala/bytebufferpool/bytebuffer.go
  vendor/github.com/valyala/bytebufferpool/doc.go
  vendor/github.com/valyala/bytebufferpool/pool.go
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1444 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_validation.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1457 [master] golang format tools
  kafka/channel/pkg/dispatcher/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1460 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/channelable_combined_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_control_plane_test_helper.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1461 Pin knative/pkg and knative/test-infra to release-0.17
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1465 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/register.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1447 Increase e2e tests timeout
  test/e2e-tests.sh
  test/e2e/broker_redelivery_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1468 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_sources_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/sources_client.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1alpha1/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1alpha1/pingsource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha1/expansion_generated.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha1/pingsource.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/listers.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/serving/pkg/apis/config/store.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1474 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_defaults.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/register.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1476 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1479 Pin knative/eventing and knative/serving to release-0.17
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1480 Gitlabsource Prometheus port envvar set to 9092
  gitlab/pkg/reconciler/source/gitlabsource.go
Labels: approved, cla: yes, lgtm, size/XS

#1483 Gitlabsource leader election RBAC
  gitlab/cmd/controller/main.go
  gitlab/config/201-clusterrole.yaml
  gitlab/pkg/reconciler/source/controller.go
Labels: approved, cla: yes, lgtm, size/S

#1486 unpin knative deps post 0.17 release
  awssqs/pkg/client/injection/reconciler/sources/v1alpha1/awssqssource/reconciler.go
  camel/source/pkg/client/injection/reconciler/sources/v1alpha1/camelsource/reconciler.go
  couchdb/source/pkg/client/injection/reconciler/sources/v1alpha1/couchdbsource/reconciler.go
  github/pkg/client/injection/reconciler/sources/v1alpha1/githubsource/reconciler.go
  gitlab/pkg/client/injection/reconciler/sources/v1alpha1/gitlabsource/reconciler.go
  go.mod
  go.sum
  hack/update-deps.sh
  kafka/channel/pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/reconciler.go
  kafka/channel/pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
  kafka/source/pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/reconciler.go
  kafka/source/pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/reconciler.go
  kafka/source/pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/reconciler.go
  kafka/source/pkg/client/injection/reconciler/sources/v1beta1/kafkasource/reconciler.go
  natss/pkg/client/injection/reconciler/messaging/v1alpha1/natsschannel/reconciler.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/kmp/diff.go
  vendor/knative.dev/pkg/kmp/reporters.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#1488 Gitlabsource additional Conditions and Printer Columns
  gitlab/config/300-gitlabsource.yaml
  gitlab/pkg/apis/sources/v1alpha1/gitlabsource_types.go
  gitlab/pkg/apis/sources/v1alpha1/gitlabsource_types_test.go
  gitlab/pkg/reconciler/source/gitlabsource.go
Labels: approved, cla: yes, lgtm, size/L

#1491 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/reconciler/sugar/labels.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1490 Rename ReceiveAdapterConfigured condition to Deployed
  gitlab/config/300-gitlabsource.yaml
  gitlab/pkg/apis/sources/v1alpha1/gitlabsource_types.go
  gitlab/pkg/apis/sources/v1alpha1/gitlabsource_types_test.go
  gitlab/pkg/reconciler/source/gitlabsource.go
Labels: approved, cla: yes, lgtm, size/M

#1498 [master] Auto-update dependencies
  camel/source/pkg/camel-k/injection/informers/camel/v1/camelcatalog/camelcatalog.go
  camel/source/pkg/camel-k/injection/informers/camel/v1/camelcatalog/fake/fake.go
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/channelable_combined_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/channel.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_subscriber_test_helper.go
  vendor/knative.dev/pkg/apis/duck/README.md
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1503 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1502 [release-0.17] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1506 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/eventing/test/lib/duck/resource_getters.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1511 Update broker to be v1 in BrokerRedelivery test
  test/e2e/broker_redelivery_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1515 do not use eventing/pkg/logging, use pkg/logging instead.
  couchdb/source/pkg/reconciler/couchdbsource.go
  github/pkg/mtadapter/githubsource_test.go
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_it_test.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
  kafka/channel/pkg/reconciler/controller/controller.go
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  kafka/common/pkg/kafka/consumer_factory.go
  kafka/common/pkg/kafka/consumer_factory_test.go
  kafka/common/pkg/kafka/consumer_handler.go
  kafka/common/pkg/kafka/consumer_handler_test.go
  kafka/source/pkg/adapter/adapter.go
  kafka/source/pkg/adapter/adapter_benchmark_test.go
  kafka/source/pkg/adapter/adapter_test.go
  kafka/source/pkg/adapter/message.go
  natss/pkg/reconciler/dispatcher/natsschannel.go
Labels: approved, cla: yes, lgtm, size/L

#1512 [release-0.17] Updating broker to be v1 in BrokerRedelivery test (#1511)
  test/e2e/broker_redelivery_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1514 [release-0.17] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_lifecycle.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1522 [master] golang format tools
  couchdb/source/pkg/reconciler/couchdbsource.go
  github/pkg/mtadapter/githubsource_test.go
  kafka/channel/pkg/reconciler/controller/controller.go
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  natss/pkg/reconciler/dispatcher/natsschannel.go
Labels: approved, cla: yes, lgtm, size/S
