Repository knative/eventing-contrib, pull requests merged in 2020-02, with the labels that each got.

#870 Update OWNERS_ALIASES for Productivity WG
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#883 Complete refactor of the kafka source test
  test/e2e/helpers/kafka_sender_helper.go
  test/e2e/kafka_source_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#880 Fixing missing error handling in kafka consumer group handler
  kafka/common/pkg/kafka/consumer_factory.go
  kafka/common/pkg/kafka/consumer_factory_test.go
Labels: approved, cla: yes, lgtm, size/M

#884 Now KafkaSource supports cloudevents Kafka Structured Encoding
  Gopkg.lock
  kafka/source/pkg/adapter/adapter.go
  kafka/source/pkg/adapter/adapter_benchmark_test.go
  kafka/source/pkg/adapter/adapter_test.go
  test/e2e-tests.sh
  test/e2e/helpers/kafka_helper.go
  test/e2e/kafka_source_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#885 Kafka dispatcher does not need to mount the logging cm
  kafka/channel/pkg/reconciler/controller/resources/dispatcher.go
  kafka/channel/pkg/reconciler/controller/resources/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/S

#878 Use ce overrides if given in heartbeat sample.
  cmd/heartbeats/main.go
Labels: approved, cla: yes, lgtm, size/M

#887 Fix #867: migrate camel source to sources.knative.dev
  camel/source/config/201-clusterrole.yaml
  camel/source/config/203-camel-source-observer-cluster-role.yaml
  camel/source/config/300-camelsource.yaml
  camel/source/pkg/apis/sources/v1alpha1/doc.go
  camel/source/pkg/apis/sources/v1alpha1/register.go
  camel/source/pkg/apis/sources/v1alpha1/register_test.go
  camel/source/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_camelsource.go
  camel/source/pkg/client/clientset/versioned/typed/sources/v1alpha1/sources_client.go
  camel/source/pkg/client/informers/externalversions/generic.go
  camel/source/samples/camel_source_hello_world.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#875 Source Migration for kafkaSource, promSource and githubSource
  github/config/201-clusterrole.yaml
  github/config/203-webhook-clusterrole.yaml
  github/config/300-githubsource.yaml
  github/pkg/apis/sources/v1alpha1/doc.go
  github/pkg/apis/sources/v1alpha1/register.go
  github/pkg/apis/sources/v1alpha1/register_test.go
  github/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_githubsource.go
  github/pkg/client/clientset/versioned/typed/sources/v1alpha1/sources_client.go
  github/pkg/client/informers/externalversions/generic.go
  github/samples/githubsource.yaml
  prometheus/README.md
  prometheus/config/201-clusterrole.yaml
  prometheus/config/300-prometheussource.yaml
  prometheus/demo/broker_trigger.yaml
  prometheus/demo/source.yaml
  prometheus/demo/source_knative.yaml
  prometheus/demo/source_openshift.yaml
  prometheus/demo/source_range.yaml
  prometheus/pkg/apis/sources/v1alpha1/doc.go
  prometheus/pkg/apis/sources/v1alpha1/register.go
  prometheus/pkg/apis/sources/v1alpha1/register_test.go
  prometheus/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_prometheussource.go
  prometheus/pkg/client/clientset/versioned/typed/sources/v1alpha1/sources_client.go
  prometheus/pkg/client/informers/externalversions/generic.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#889 golang format tools
  cmd/heartbeats/main.go
  kafka/channel/pkg/reconciler/controller/resources/dispatcher.go
  kafka/channel/pkg/reconciler/controller/resources/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/S

#892 CamelSource e2e test (2nd attempt)
  camel/source/pkg/apis/sources/v1alpha1/camelsource_types.go
  test/config/100-camel-k-1.0.0-RC1.yaml
  test/e2e-tests.sh
  test/e2e/camel_source_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XL

#898 GitHub webhook rbac clusterrole (#877)
  github/config/202-clusterrolebinding.yaml
  github/config/203-webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/L

#901 Adjust yaml formatting...
  kafka/channel/config/300-kafka-channel.yaml
Labels: approved, cla: yes, lgtm, size/XS

#903 fixing typo
  kafka/source/pkg/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/XS

#905 do not prefix extension headers with ce
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/XS

#907 do not prefix extension headers with ce (#905)
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
Labels: approved, cla: no, lgtm, size/XS

#912 strip ce_ headers before adding extensions
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/S

#914 do not pass kafka headers into cloudevents extensions
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/S

#913 diff the dispatcher.Spec and update as necessary
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/controller/kafkachannel_test.go
Labels: approved, cla: yes, lgtm, size/L

#906 enable e2e tests for kafka channel
  test/config/100-kafka-ephemeral-triple-2.4.0.yaml
  test/config/100-strimzi-cluster-operator-0.16.2.yaml
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#918 remove do not submit and add an issue to track parallelism
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#924 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_conversion.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/channel_types.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/channel.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/reconciler/configstore.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/knative.dev/serving/pkg/autoscaler/config/testdata/config-autoscaler.yaml
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#902 Migrate kafkasource to sources.knative.dev
  Gopkg.lock
  kafka/source/README.md
  kafka/source/config/201-clusterrole.yaml
  kafka/source/config/300-kafkasource.yaml
  kafka/source/pkg/adapter/adapter.go
  kafka/source/pkg/apis/sources/register.go
  kafka/source/pkg/apis/sources/v1alpha1/doc.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_types.go
  kafka/source/pkg/apis/sources/v1alpha1/register.go
  kafka/source/pkg/apis/sources/v1alpha1/register_test.go
  kafka/source/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_kafkasource.go
  kafka/source/pkg/client/clientset/versioned/typed/sources/v1alpha1/sources_client.go
  kafka/source/pkg/client/informers/externalversions/generic.go
  kafka/source/pkg/client/injection/informers/sources/factory/fake/fake.go
  kafka/source/pkg/client/injection/informers/sources/factory/sourcesfactory.go
  kafka/source/pkg/reconciler/controller.go
  kafka/source/pkg/reconciler/kafkasource.go
  kafka/source/pkg/reconciler/resources/receive_adapter.go
  test/performance/source-kafka/100-source-perf-setup.yaml
  test/performance/source-kafka/101-source-perf-setup.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#925 Adding type test for kafka channel...
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_types_test.go
Labels: approved, cla: yes, lgtm, size/M

#929 only see if image has changed before redeploy
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
Labels: approved, cla: yes, lgtm, size/XS

#934 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/config/300-flows-parallel.yaml
  vendor/knative.dev/eventing/config/300-flows-sequence.yaml
  vendor/knative.dev/eventing/config/channels/in-memory-channel-ns/100-config-event-dispatcher.yaml
  vendor/knative.dev/eventing/config/channels/in-memory-channel-ns/200-addressable-resolver-clusterrole.yaml
  vendor/knative.dev/eventing/config/channels/in-memory-channel-ns/200-channelable-manipulator-clusterrole.yaml
  vendor/knative.dev/eventing/config/channels/in-memory-channel-ns/200-dispatcher-clusterrole.yaml
  vendor/knative.dev/eventing/config/channels/in-memory-channel-ns/200-serviceaccount.yaml
  vendor/knative.dev/eventing/config/channels/in-memory-channel-ns/201-clusterrolebinding.yaml
  vendor/knative.dev/eventing/config/channels/in-memory-channel-ns/300-in-memory-channel.yaml
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_types.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/broker.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/boskos/boskos.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
Labels: approved, cla: yes, lgtm, size/L

#932 like other webhooks, adding list/watch for secrets
  kafka/channel/config/200-webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#930 Remove kafka statefulset
  kafka/source/config/500-controller.yaml
Labels: approved, cla: yes, lgtm, size/M

#928 add Alek (aslom) to list of reviewers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#938 Add lberk to base OWNERS reviews
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#937 GenReconciler for kafkasource
  Gopkg.lock
  kafka/source/cmd/controller/main.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_types.go
  kafka/source/pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/controller.go
  kafka/source/pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/reconciler.go
  kafka/source/pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/stub/controller.go
  kafka/source/pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/stub/reconciler.go
  kafka/source/pkg/reconciler/controller.go
  kafka/source/pkg/reconciler/kafkasource.go
Labels: approved, cla: yes, lgtm, size/L

#945 point to the new pkg.go.dev website for api docs
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#940 Allowing sinkbinding for websocket source
  cmd/websocketsource/main.go
Labels: approved, cla: yes, lgtm, size/XS

#953 Format markdown
  kafka/channel/README.md
Labels: approved, cla: yes, lgtm, size/M

#954 golang format tools
  cmd/websocketsource/main.go
Labels: approved, cla: yes, lgtm, size/XS

#957 Update knative.dev/test-infra dependency
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#941 Update templates from eventing
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/issue-template.md
  .github/pull-request-template.md
  test/markdown-lint-config.rc
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#968 Preparing for v0.13 release, point pkg to release-0.13.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/metrics/README.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/testdata/README.md
  vendor/knative.dev/pkg/metrics/testdata/client-cert.pem
  vendor/knative.dev/pkg/metrics/testdata/client-key.pem
  vendor/knative.dev/pkg/metrics/testdata/server-cert.pem
  vendor/knative.dev/pkg/metrics/testdata/server-key.pem
  vendor/knative.dev/pkg/test/logging/logging.go
Labels: approved, cla: yes, lgtm, size/L

#956 Migrate awssqsSource to sources.knative.dev
  awssqs/config/201-clusterrole.yaml
  awssqs/config/300-awssqssource.yaml
  awssqs/pkg/apis/sources/v1alpha1/doc.go
  awssqs/pkg/apis/sources/v1alpha1/register.go
  awssqs/pkg/apis/sources/v1alpha1/register_test.go
  awssqs/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_awssqssource.go
  awssqs/pkg/client/clientset/versioned/typed/sources/v1alpha1/sources_client.go
  awssqs/pkg/client/informers/externalversions/generic.go
  awssqs/pkg/client/injection/reconciler/sources/v1alpha1/awssqssource/controller.go
  awssqs/samples/awssqs-source.yaml
Labels: approved, cla: yes, lgtm, size/S

#962 allow Kafka Channel to use ns dispatcher based on annotation
  Gopkg.lock
  hack/release.sh
  kafka/channel/README.md
  kafka/channel/config/200-controller-clusterrole.yaml
  kafka/channel/config/500-controller.yaml
  kafka/channel/config/namespace/200-addressable-resolver-clusterrole.yaml
  kafka/channel/config/namespace/200-channelable-manipulator-clusterrole.yaml
  kafka/channel/config/namespace/200-controller-clusterrole.yaml
  kafka/channel/config/namespace/200-controller-serviceaccount.yaml
  kafka/channel/config/namespace/200-dispatcher-clusterrole.yaml
  kafka/channel/config/namespace/200-webhook-clusterrole.yaml
  kafka/channel/config/namespace/200-webhook-serviceaccount.yaml
  kafka/channel/config/namespace/201-clusterrolebinding.yaml
  kafka/channel/config/namespace/300-kafka-channel.yaml
  kafka/channel/config/namespace/400-webhook-service.yaml
  kafka/channel/config/namespace/500-controller.yaml
  kafka/channel/config/namespace/500-webhook-configuration.yaml
  kafka/channel/config/namespace/500-webhook.yaml
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_validation.go
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_validation_test.go
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  vendor/knative.dev/eventing/pkg/apis/sources/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/doc.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/fake/fake_pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/fake/fake_sources_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/sources_client.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1alpha2/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1alpha2/pingsource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha2/expansion_generated.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha2/pingsource.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#971 Format markdown
  kafka/channel/README.md
Labels: approved, cla: yes, lgtm, size/S

#966 Add support for leader election
  Gopkg.lock
  awssqs/cmd/controller/main.go
  awssqs/config/201-clusterrole.yaml
  awssqs/config/500-controller.yaml
  awssqs/config/config-leader-election.yaml
  couchdb/source/cmd/controller/main.go
  couchdb/source/config/201-clusterrole.yaml
  couchdb/source/config/500-controller.yaml
  couchdb/source/config/config-leader-election.yaml
  github/cmd/controller/main.go
  github/config/201-clusterrole.yaml
  github/config/500-controller.yaml
  github/config/config-leader-election.yaml
  kafka/channel/cmd/channel_controller/main.go
  kafka/channel/cmd/channel_dispatcher/main.go
  kafka/channel/cmd/webhook/main.go
  kafka/channel/config/200-controller-clusterrole.yaml
  kafka/channel/config/200-dispatcher-clusterrole.yaml
  kafka/channel/config/400-leader-election-config.yaml
  kafka/channel/config/500-controller.yaml
  kafka/channel/pkg/reconciler/controller/resources/dispatcher.go
  kafka/channel/pkg/reconciler/controller/resources/dispatcher_test.go
  kafka/docs/metrics.md
  kafka/source/config/201-clusterrole.yaml
  kafka/source/config/500-controller.yaml
  kafka/source/config/config-leader-election.yaml
  prometheus/cmd/controller/main.go
  prometheus/config/201-clusterrole.yaml
  prometheus/config/500-controller.yaml
  prometheus/config/config-leader-election.yaml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
Labels: approved, cla: yes, lgtm, size/XL

#969 Add support for DeadLetterSink in KafkaChannel
  kafka/channel/pkg/dispatcher/dispatcher.go
  test/e2e/broker_dls_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M
