Repository knative/eventing-contrib, pull requests merged in 2020-04, with the labels that each got.

#1061 Performance tests for Natss channel and Natss broker
  test/performance/broker-natss/100-broker-perf-setup.yaml
  test/performance/broker-natss/200-broker-perf.yaml
  test/performance/channel-natss/100-channel-perf-setup.yaml
  test/performance/channel-natss/101-channel-perf-setup.yaml
  test/performance/channel-natss/200-channel-perf.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XL

#1089 Remove finalizer to avoid finalize loop in GitHubSource FinalizeKind().
  github/pkg/reconciler/githubsource.go
  github/pkg/reconciler/webhook_client.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1057 fix github webhook rbac rules
  github/config/203-webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1101 Make KafkaSource implement GenericCRD
  kafka/source/pkg/apis/sources/v1alpha1/kafka_defaults.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_types.go
Labels: approved, cla: yes, lgtm, size/S

#1094 UpdateFromLoggingConfigMap removed from Gitlabsource
  gitlab/pkg/reconciler/controller.go
  gitlab/pkg/reconciler/gitlabsource.go
Labels: approved, cla: yes, lgtm, size/S

#1103 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_client.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#1078 Migrate natss channel off reconciler.Base and fix NATSS channel
  Gopkg.lock
  natss/cmd/channel_controller/main.go
  natss/pkg/apis/messaging/v1alpha1/natss_channel_types.go
  natss/pkg/client/injection/reconciler/messaging/v1alpha1/natsschannel/controller.go
  natss/pkg/client/injection/reconciler/messaging/v1alpha1/natsschannel/reconciler.go
  natss/pkg/client/injection/reconciler/messaging/v1alpha1/natsschannel/stub/controller.go
  natss/pkg/client/injection/reconciler/messaging/v1alpha1/natsschannel/stub/reconciler.go
  natss/pkg/dispatcher/dispatcher.go
  natss/pkg/reconciler/controller/controller.go
  natss/pkg/reconciler/controller/controller_test.go
  natss/pkg/reconciler/controller/natsschannel.go
  natss/pkg/reconciler/controller/natsschannel_test.go
  natss/pkg/reconciler/dispatcher/natsschannel.go
  natss/pkg/reconciler/dispatcher/natsschannel_test.go
  natss/pkg/reconciler/reconciler.go
  natss/pkg/reconciler/testing/factory.go
  test/e2e/broker_channel_flow_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XL

#1106 [master] Auto-update dependencies
  Gopkg.lock
  vendor/github.com/kballard/go-shellquote/LICENSE
  vendor/github.com/kballard/go-shellquote/doc.go
  vendor/github.com/kballard/go-shellquote/quote.go
  vendor/github.com/kballard/go-shellquote/unquote.go
  vendor/knative.dev/eventing/config/200-jobrunner-clusterrole.yaml
  vendor/knative.dev/eventing/config/201-jobrunner-serviceaccount.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/200-channel-clusterrole.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/201-channel-clusterrolebinding.yaml
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/test_helpers.go
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_handler.go
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/knative.dev/eventing/pkg/channel/message_receiver.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_client.go
  vendor/knative.dev/eventing/pkg/tracing/traceparent_transformer.go
  vendor/knative.dev/eventing/pkg/tracing/transformers.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/config.go
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/pkg/apiextensions/storageversion/migrator.go
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/monitored_resources.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/cmd/command.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/testgrid/testgrid.go
  vendor/knative.dev/pkg/testing/resource.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/config.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/setup.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/create.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/delete.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/options/options.go
  vendor/knative.dev/pkg/testutils/metahelper/client/client.go
  vendor/knative.dev/pkg/testutils/metahelper/main.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/testing/testing.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
Labels: approved, cla: yes, lgtm, size/XXL

#1112 Add mattmoor to github approvers
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1115 Preparing for v0.14 release, point pkg to release-0.14.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/images/Knative-Duck0.png
Labels: approved, cla: yes, lgtm, size/L

#1107 Add a webhook for KafkaSource that runs alongside the controller.
  kafka/source/cmd/controller/main.go
  kafka/source/config/201-clusterrole.yaml
  kafka/source/config/500-controller.yaml
  kafka/source/config/500-webhook-configuration.yaml
Labels: approved, cla: yes, lgtm, size/L

#1117 Removed default content type in kafkasource
  kafka/source/pkg/adapter/adapter_test.go
  kafka/source/pkg/adapter/message.go
  test/e2e/kafka_source_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1121 [master] Auto-update dependencies
  Gopkg.lock
  vendor/github.com/kballard/go-shellquote/LICENSE
  vendor/github.com/kballard/go-shellquote/doc.go
  vendor/github.com/kballard/go-shellquote/quote.go
  vendor/github.com/kballard/go-shellquote/unquote.go
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
Labels: approved, cla: yes, lgtm, size/L

#1104 [master] golang format tools
  natss/pkg/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, size/XS

#1124 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/config/400-config-br-default-channel.yaml
  vendor/knative.dev/eventing/config/400-config-br-defaults.yaml
  vendor/knative.dev/eventing/config/brokers/channel-broker/400-config-br-default-channel.yaml
  vendor/knative.dev/eventing/config/brokers/channel-broker/400-config-br-defaults.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/400-config-br-default-channel.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/400-config-br-defaults.yaml
  vendor/knative.dev/eventing/test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/S

#1126 [release-0.13] Pin test-infra to release branch
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
Labels: approved, cla: yes, lgtm, size/L

#1128 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#1125 Include empty validation callback lists
  couchdb/source/cmd/webhook/main.go
  github/cmd/webhook/main.go
  kafka/channel/cmd/webhook/main.go
  kafka/source/cmd/controller/main.go
Labels: approved, cla: yes, lgtm, size/M

#1132 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/serving/third_party/istio-1.5-latest
Labels: approved, cla: yes, lgtm, size/S

#1133 Point test-infra to release-0.14 in prep for 0.14 release
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1135 Point release to v0.14 release branch of knative/serving
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/serving/third_party/istio-1.4-latest
  vendor/knative.dev/serving/third_party/istio-stable
Labels: approved, cla: yes, lgtm, size/S

#1136 Point release to v0.14 release branch of knative/eventing
  Gopkg.lock
  Gopkg.toml
Labels: approved, cla: yes, lgtm, size/XS

#1138 Adding the gitlab source for release
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1137 Adding the gitlab source for release
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1141 Updating pkg/serving/eventing/testing-contrib to latest.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/DEVELOPMENT.md
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/RELEASING.md
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/serving/pkg/apis/networking/register.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#1123 Drop reconciler.Base from eventing.
  Gopkg.lock
  natss/pkg/reconciler/testing/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/reconciler.go
  vendor/knative.dev/eventing/pkg/reconciler/stats_reporter.go
Labels: approved, cla: yes, lgtm, size/L

#1142 KafkaSource make consumergroup optional, set to uuid if not specified
  kafka/source/config/300-kafkasource.yaml
  kafka/source/pkg/apis/sources/v1alpha1/kafka_defaults.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_defaults_test.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_types.go
Labels: approved, cla: yes, lgtm, size/M

#1144 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/test/helpers/name.go
Labels: approved, cla: yes, lgtm, size/S

#1140 :lipstick: updating component list
  README.md
Labels: approved, cla: yes, lgtm, size/S

#1145 Gitlabsource example URL fixed
  gitlab/config/300-gitlabsource.yaml
  gitlab/pkg/apis/sources/v1alpha1/gitlabsource_types.go
Labels: approved, cla: yes, lgtm, size/XS

#1120 GitlabSource webhook that runs alongside the controller
  gitlab/cmd/controller/main.go
  gitlab/config/201-clusterrole.yaml
  gitlab/config/400-controller-service.yaml
  gitlab/config/500-controller.yaml
  gitlab/config/500-webhook-configuration.yaml
Labels: approved, cla: yes, lgtm, size/L

#1146 [master] Format markdown
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1147 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
Labels: approved, cla: yes, lgtm, size/M

#1150 Update eventing master
  kafka/channel/pkg/dispatcher/dispatcher_it_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1152 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/pkg/channel/config.go
  vendor/knative.dev/eventing/pkg/channel/event_dispatcher.go
  vendor/knative.dev/eventing/pkg/channel/event_receiver.go
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_handler.go
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
  vendor/knative.dev/eventing/pkg/channel/history.go
  vendor/knative.dev/eventing/pkg/channel/history_transformer.go
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/knative.dev/eventing/pkg/channel/message_receiver.go
  vendor/knative.dev/eventing/pkg/channel/multichannelfanout/multi_channel_fanout_handler.go
  vendor/knative.dev/eventing/pkg/channel/multichannelfanout/multi_channel_fanout_message_handler.go
  vendor/knative.dev/eventing/pkg/channel/references.go
  vendor/knative.dev/pkg/apis/duck/cached.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
Labels: approved, cla: yes, lgtm, size/XL

#1153 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/cmd/mtping/kodata/HEAD
  vendor/knative.dev/eventing/cmd/mtping/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/mtping/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/mtping/kodata/refs
  vendor/knative.dev/eventing/cmd/ping/adapter/kodata/HEAD
  vendor/knative.dev/eventing/cmd/ping/adapter/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/ping/adapter/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/ping/adapter/kodata/refs
  vendor/knative.dev/eventing/cmd/ping/jobrunner/kodata/HEAD
  vendor/knative.dev/eventing/cmd/ping/jobrunner/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/ping/jobrunner/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/ping/jobrunner/kodata/refs
  vendor/knative.dev/eventing/cmd/ping/kodata/HEAD
  vendor/knative.dev/eventing/cmd/ping/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/ping/kodata/VENDOR-LICENSE
  vendor/knative.dev/eventing/cmd/ping/kodata/refs
  vendor/knative.dev/eventing/config/200-jobrunner-clusterrole.yaml
  vendor/knative.dev/eventing/config/200-pingsource-mt-adapter-clusterrole.yaml
  vendor/knative.dev/eventing/config/201-jobrunner-serviceaccount.yaml
  vendor/knative.dev/eventing/config/201-pingsource-mt-adapter-serviceaccount.yaml
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_types.go
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/knative.dev/eventing/pkg/channel/multichannelfanout/multi_channel_fanout_message_handler.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_conversion.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#1154 Status conformance tests for channels
  Gopkg.lock
  test/conformance/README.md
  test/conformance/channel_status_test.go
  test/conformance/main_test.go
  test/e2e-tests.sh
  vendor/go.opentelemetry.io/otel/LICENSE
  vendor/go.opentelemetry.io/otel/api/core/doc.go
  vendor/go.opentelemetry.io/otel/api/core/key.go
  vendor/go.opentelemetry.io/otel/api/core/number.go
  vendor/go.opentelemetry.io/otel/api/core/numberkind_string.go
  vendor/go.opentelemetry.io/otel/api/core/rawhelpers.go
  vendor/go.opentelemetry.io/otel/api/core/span_context.go
  vendor/go.opentelemetry.io/otel/api/core/valuetype_string.go
  vendor/go.opentelemetry.io/otel/api/propagation/doc.go
  vendor/go.opentelemetry.io/otel/api/propagation/propagation.go
  vendor/go.opentelemetry.io/otel/api/trace/always_off_sampler.go
  vendor/go.opentelemetry.io/otel/api/trace/always_on_sampler.go
  vendor/go.opentelemetry.io/otel/api/trace/api.go
  vendor/go.opentelemetry.io/otel/api/trace/b3_propagator.go
  vendor/go.opentelemetry.io/otel/api/trace/context.go
  vendor/go.opentelemetry.io/otel/api/trace/doc.go
  vendor/go.opentelemetry.io/otel/api/trace/noop_span.go
  vendor/go.opentelemetry.io/otel/api/trace/noop_trace.go
  vendor/go.opentelemetry.io/otel/api/trace/noop_trace_provider.go
  vendor/go.opentelemetry.io/otel/api/trace/sampler.go
  vendor/go.opentelemetry.io/otel/api/trace/trace_context_propagator.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_crd_name_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_header_single_event_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/traces.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/zipkin.go
  vendor/knative.dev/eventing/test/conformance/helpers/uri.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XXL

#1156 kafkasource: change bootstrapServers and Topics to accept arrays
  kafka/source/README.md
  kafka/source/config/300-kafkasource.yaml
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_lifecycle.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_lifecycle_test.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_types.go
  kafka/source/pkg/apis/bindings/v1alpha1/zz_generated.deepcopy.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_types.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_validation_test.go
  kafka/source/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  kafka/source/pkg/reconciler/source/kafkasource.go
  kafka/source/pkg/reconciler/source/resources/receive_adapter.go
  kafka/source/pkg/reconciler/source/resources/receive_adapter_test.go
  test/lib/resources/kafka.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1158 Metadata conformance tests for channels
  Gopkg.lock
  test/conformance/channel_crd_metadata_test.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_crd_metadata_test_helper.go
  vendor/knative.dev/eventing/test/lib/client.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/L

#1159 Channel CRD name conformance test
  test/conformance/channel_crd_name_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/M

#1163 kafka,github sources - clusterroles add namespace patching for bindings
  Gopkg.lock
  awssqs/pkg/client/injection/reconciler/sources/v1alpha1/awssqssource/controller.go
  awssqs/pkg/client/injection/reconciler/sources/v1alpha1/awssqssource/reconciler.go
  camel/source/pkg/client/injection/reconciler/sources/v1alpha1/camelsource/controller.go
  camel/source/pkg/client/injection/reconciler/sources/v1alpha1/camelsource/reconciler.go
  couchdb/source/pkg/client/injection/reconciler/sources/v1alpha1/couchdbsource/controller.go
  couchdb/source/pkg/client/injection/reconciler/sources/v1alpha1/couchdbsource/reconciler.go
  github/config/201-clusterrole.yaml
  github/pkg/client/injection/reconciler/sources/v1alpha1/githubsource/controller.go
  github/pkg/client/injection/reconciler/sources/v1alpha1/githubsource/reconciler.go
  github/pkg/reconciler/binding/controller.go
  gitlab/pkg/client/injection/reconciler/sources/v1alpha1/gitlabsource/controller.go
  gitlab/pkg/client/injection/reconciler/sources/v1alpha1/gitlabsource/reconciler.go
  kafka/channel/pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/controller.go
  kafka/channel/pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/reconciler.go
  kafka/source/config/201-clusterrole.yaml
  kafka/source/pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/controller.go
  kafka/source/pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/reconciler.go
  kafka/source/pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/controller.go
  kafka/source/pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/reconciler.go
  kafka/source/pkg/reconciler/binding/controller.go
  natss/pkg/client/injection/reconciler/messaging/v1alpha1/natsschannel/controller.go
  natss/pkg/client/injection/reconciler/messaging/v1alpha1/natsschannel/reconciler.go
  prometheus/pkg/client/injection/reconciler/sources/v1alpha1/prometheussource/controller.go
  prometheus/pkg/client/injection/reconciler/sources/v1alpha1/prometheussource/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1alpha1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1alpha1/broker/reconciler.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_channelable_manipulator_cluster_role_test_helper.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/config/testdata/config-autoscaler.yaml
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/config/testdata/config-deployment.yaml
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/L

#1164 update event-display example to serving v1
  config/tools/event-display/event-display.yaml
Labels: approved, cla: yes, lgtm, size/S

#1169 Reduce namespace verbs for {kafka,github}source webhooks
  github/config/201-clusterrole.yaml
  kafka/source/config/201-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/S

#1168 Fix test builds
  Gopkg.lock
  test/e2e/channel_single_event_test.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_defaults.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go
  vendor/knative.dev/eventing/test/lib/duck/resource_checks.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/test/mako/stub-sidecar/main.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/basictypekindnode.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1176 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/hack/tools.go
  vendor/knative.dev/pkg/injection/context.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/prober/prober.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/ghutil/client.go
  vendor/knative.dev/pkg/test/helpers/dir.go
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
  vendor/knative.dev/pkg/test/mako/alerter/slack/message.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/ignorefields.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/tools/tools.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/webhook.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/boskos/boskos.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/benchmark.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/reconciler.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/L

#1179 Fixed Kafka disconnection issue
  kafka/channel/pkg/dispatcher/dispatcher_it_test.go
  kafka/common/pkg/kafka/consumer_factory.go
  kafka/common/pkg/kafka/consumer_factory_test.go
Labels: approved, cla: yes, lgtm, size/M

#1182 Removed wrong panic
  kafka/channel/pkg/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, size/XS

#1183 Removed wrong panic - backport 0.14
  kafka/channel/pkg/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, size/XS

#1173 [github] add permission to read namespaces to the github-webhook (#1172)
  github/config/201-clusterrole.yaml
  github/config/203-webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1165 Fix parallelism of Kafka's consumer groups
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/common/pkg/kafka/consumer_factory.go
  kafka/common/pkg/kafka/consumer_factory_test.go
  kafka/source/pkg/adapter/adapter.go
  kafka/source/pkg/adapter/adapter_test.go
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/L
