Repository knative/eventing-contrib, pull requests merged in 2020-11, with the labels that each got.

#1656 [0.18] eventing update
  go.mod
  go.sum
  kafka/channel/pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/reconciler.go
  kafka/channel/pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
  kafka/source/pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/reconciler.go
  kafka/source/pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/reconciler.go
  kafka/source/pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/reconciler.go
  kafka/source/pkg/client/injection/reconciler/sources/v1beta1/kafkasource/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1657 [0.17] Update eventing to latest
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/kncloudevents/http_client.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_control_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_subscriber_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/parallel_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/sequence_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/trigger_no_broker_test_helper.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/dropevents/receiver.go
  vendor/knative.dev/eventing/test/lib/k8s_events.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_log.go
  vendor/knative.dev/eventing/test/lib/recordevents/logger_vent/logger.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/observer.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/reply.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/constructor.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/doc.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/recorder.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/eventing/test/lib/resources/kube.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/eventing/test/test_images/recordevents/eventstore.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1658 [0.18] Update eventing to latest
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/http_client.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1660 fix error during upgrade from 0.17 to 0.18
  kafka/channel/config/deployments/dispatcher.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1661 fix namespaced kafka dispacher crash (#172)
  kafka/channel/pkg/reconciler/controller/resources/dispatcher.go
  kafka/channel/pkg/reconciler/controller/resources/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/S

#1662 Add new component locations to the README
  README.md
Labels: approved, cla: yes, lgtm, size/S

#1663 disable leader election (#173)
  kafka/channel/cmd/channel_dispatcher/main.go
  kafka/channel/config/roles/dispatcher-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/S

#1665 set default zap logger to "info" (#177)
  kafka/source/config/configmaps/observability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1664 don't use session context to send messages (#179)
  kafka/common/pkg/kafka/consumer_handler.go
Labels: approved, cla: yes, lgtm, size/XS

#1668 Use SyncProducer to provide safer delivery
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/M

#1669 Removing nachocano from approvers/reviewers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1667 [0.18] Backport: Adding global TLS/SASL for the KafkaChannel
  go.mod
  go.sum
  kafka/channel/config/configmaps/kafka-config.yaml
  kafka/channel/config/roles/controller-clusterrole.yaml
  kafka/channel/config/roles/dispatcher-clusterrole.yaml
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/reconciler/controller/kafkachannel.go
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  kafka/channel/pkg/utils/util.go
  kafka/channel/pkg/utils/util_test.go
  kafka/client.go
  kafka/client_test.go
  kafka/kafka_scram_client.go
  test/config/100-kafka-ephemeral-triple-2.6.0.yaml
  test/config/100-strimzi-users-0.20.0.yaml
  test/config/config-kafka-sasl.yaml
  test/config/config-kafka-tls.yaml
  test/e2e-tests.sh
  test/e2e/kafka_binding_test.go
  test/e2e/kafka_source_reconciler_test.go
  test/e2e/kafka_source_test.go
  third_party/VENDOR-LICENSE/github.com/xdg/scram/LICENSE
  third_party/VENDOR-LICENSE/github.com/xdg/stringprep/LICENSE
  vendor/github.com/xdg/scram/.gitignore
  vendor/github.com/xdg/scram/.travis.yml
  vendor/github.com/xdg/scram/LICENSE
  vendor/github.com/xdg/scram/README.md
  vendor/github.com/xdg/scram/client.go
  vendor/github.com/xdg/scram/client_conv.go
  vendor/github.com/xdg/scram/common.go
  vendor/github.com/xdg/scram/doc.go
  vendor/github.com/xdg/scram/parse.go
  vendor/github.com/xdg/scram/scram.go
  vendor/github.com/xdg/scram/server.go
  vendor/github.com/xdg/scram/server_conv.go
  vendor/github.com/xdg/stringprep/.gitignore
  vendor/github.com/xdg/stringprep/.travis.yml
  vendor/github.com/xdg/stringprep/LICENSE
  vendor/github.com/xdg/stringprep/README.md
  vendor/github.com/xdg/stringprep/bidi.go
  vendor/github.com/xdg/stringprep/doc.go
  vendor/github.com/xdg/stringprep/error.go
  vendor/github.com/xdg/stringprep/map.go
  vendor/github.com/xdg/stringprep/profile.go
  vendor/github.com/xdg/stringprep/saslprep.go
  vendor/github.com/xdg/stringprep/set.go
  vendor/github.com/xdg/stringprep/tables.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1670 Add kafkaSource saslType, e2e tests for auth (tls and sasl512)
  kafka/client.go
  kafka/client_test.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_conversion.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_conversion_test.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_lifecycle.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_lifecycle_test.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_types.go
  kafka/source/pkg/apis/bindings/v1alpha1/zz_generated.deepcopy.go
  kafka/source/pkg/apis/bindings/v1beta1/kafka_lifecycle.go
  kafka/source/pkg/apis/bindings/v1beta1/kafka_lifecycle_test.go
  kafka/source/pkg/apis/bindings/v1beta1/kafka_types.go
  kafka/source/pkg/apis/bindings/v1beta1/zz_generated.deepcopy.go
  kafka/source/pkg/reconciler/source/resources/receive_adapter.go
  kafka/source/pkg/reconciler/source/resources/receive_adapter_test.go
  test/e2e-tests.sh
  test/e2e/kafka_binding_test.go
  test/e2e/kafka_source_reconciler_test.go
  test/e2e/kafka_source_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL
