Repository knative/eventing-contrib, pull requests merged in 2020-10, with the labels that each got.

#1630 [0.18] Port https://github.com/knative-sandbox/eventing-kafka/pull/81
  kafka/channel/config/deployments/webhook.yaml
  kafka/source/config/deployments/controller.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1631 [0.17] Port https://github.com/knative-sandbox/eventing-kafka/pull/81
  kafka/channel/config/500-webhook.yaml
  kafka/source/config/500-controller.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1622 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#1637 Using Knative Sources ns, to allign w/ all the other CMs
  kafka/source/config/configmaps/observability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1636 Using Knative Sources ns, to allign w/ all the other CMs
  kafka/source/config/config-observability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1639 [0.18] Backport https://github.com/knative-sandbox/eventing-kafka/pull/96
  kafka/channel/config/deployments/dispatcher.yaml
  kafka/source/config/configmaps/observability.yaml
  kafka/source/config/roles/clusterrole.yaml
  kafka/source/config/webhooks/kafka.yaml
Labels: approved, cla: yes, lgtm, size/S

#1638 [0.17] Backport https://github.com/knative-sandbox/eventing-kafka/pull/96
  kafka/source/config/201-clusterrole.yaml
  kafka/source/config/500-webhook-configuration.yaml
  kafka/source/config/config-observability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1645 DeepCopy the entire set of conditions (#128)
  go.mod
  kafka/source/pkg/apis/sources/v1alpha1/kafka_conversion.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_types.go
  kafka/source/pkg/apis/sources/v1alpha1/roundtrip_test.go
  kafka/source/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  kafka/source/pkg/apis/sources/v1beta1/fuzzer.go
  kafka/source/pkg/apis/sources/v1beta1/roundtrip_test.go
  test/lib/listers.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/codec.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/compatibility.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/roundtrip.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/fuzzer/fuzzer.go
  vendor/knative.dev/pkg/apis/testing/roundtrip/roundtrip.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1650 [0.17] Fix KafkaSource conversion
  kafka/source/pkg/apis/sources/v1alpha1/kafka_conversion.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_conversion_test.go
Labels: approved, cla: yes, lgtm, size/S

#1651 [0.17] Fix KafkaBinding conversion
  kafka/source/config/300-kafkabinding.yaml
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_conversion.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_conversion_test.go
Labels: approved, cla: yes, lgtm, size/S

#1652 [0.18] Fix KafkaBinding conversion
  kafka/source/config/resources/kafkabinding.yaml
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_conversion.go
  kafka/source/pkg/apis/bindings/v1alpha1/kafka_conversion_test.go
Labels: approved, cla: yes, lgtm, size/S

#1647 [0.18] Updating to latest strimzi and Apache Kafka 2.6
  test/config/100-kafka-ephemeral-triple-2.5.0.yaml
  test/config/100-kafka-ephemeral-triple-2.6.0.yaml
  test/config/100-strimzi-cluster-operator-0.20.0.yaml
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1653 [0.18] Updating to latest eventing release-0.18
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_context.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_control_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_subscriber_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/parallel_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/sequence_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/trigger_no_broker_test_helper.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/dropevents/receiver.go
  vendor/knative.dev/eventing/test/lib/k8s_events.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_log.go
  vendor/knative.dev/eventing/test/lib/recordevents/logger_vent/logger.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/observer.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/reply.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/constructor.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/doc.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/recorder.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/eventing/test/lib/resources/kube.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/eventing/test/test_images/recordevents/eventstore.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL
