Repository knative/eventing-contrib, pull requests merged in 2020-05, with the labels that each got.

#1186 Re-enable e2e tests with go mod.
  go.sum
  hack/tools.go
  hack/update-deps.sh
  test/config/100-camel-k-1.0.0-RC2.yaml
  test/e2e-tests.sh
  vendor/knative.dev/eventing/test/test_images/eventdetails/README.md
  vendor/knative.dev/eventing/test/test_images/eventdetails/main.go
  vendor/knative.dev/eventing/test/test_images/eventdetails/pod.yaml
  vendor/knative.dev/eventing/test/test_images/filterevents/main.go
  vendor/knative.dev/eventing/test/test_images/filterevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/heartbeats/main.go
  vendor/knative.dev/eventing/test/test_images/heartbeats/pod.yaml
  vendor/knative.dev/eventing/test/test_images/logevents/main.go
  vendor/knative.dev/eventing/test/test_images/logevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/performance/README.md
  vendor/knative.dev/eventing/test/test_images/performance/main.go
  vendor/knative.dev/eventing/test/test_images/performance/mako.config
  vendor/knative.dev/eventing/test/test_images/performance/pod.yaml
  vendor/knative.dev/eventing/test/test_images/print/main.go
  vendor/knative.dev/eventing/test/test_images/print/pod.yaml
  vendor/knative.dev/eventing/test/test_images/recordevents/README.md
  vendor/knative.dev/eventing/test/test_images/recordevents/eventstore.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/knative.dev/eventing/test/test_images/recordevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/sendevents/main.go
  vendor/knative.dev/eventing/test/test_images/sendevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/sequencestepper/main.go
  vendor/knative.dev/eventing/test/test_images/sequencestepper/pod.yaml
  vendor/knative.dev/eventing/test/test_images/transformevents/main.go
  vendor/knative.dev/eventing/test/test_images/transformevents/pod.yaml
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1184 Increase conformance tests
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1160 Conformance testing for channels control plane channelable-manipulator ClusterRole
  test/conformance/channel_channelable_manipulator_cluster_role_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/M

#1187 [master] golang format tools
  awssqs/pkg/adapter/adapter_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1193 Fix update-deps --upgrade
  hack/update-deps.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1204 Added slinkydeveloper as approver
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1207 Add dummy.go files to enable vendoring our configs
  awssqs/config/dummy.go
  camel/source/config/dummy.go
  couchdb/source/config/dummy.go
  github/config/dummy.go
  gitlab/config/dummy.go
  kafka/channel/config/dummy.go
  kafka/source/config/dummy.go
  natss/config/dummy.go
  prometheus/config/dummy.go
Labels: approved, cla: yes, lgtm, size/L

#1202 Ported Gitlab receive adapter to adapter/v2
  gitlab/cmd/receive_adapter/main.go
  gitlab/pkg/adapter/receive_adapter.go
  gitlab/pkg/adapter/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/M

#1210 Port Prometheus source to adapter/v2
  prometheus/cmd/receive_adapter/main.go
  prometheus/pkg/adapter/adapter.go
  prometheus/pkg/adapter/adapter_test.go
  vendor/knative.dev/eventing/pkg/adapter/config.go
  vendor/knative.dev/eventing/pkg/adapter/main.go
  vendor/knative.dev/eventing/pkg/kncloudevents/testing/test_client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1213 updating event display util to v2
  cmd/event_display/main.go
Labels: approved, cla: yes, lgtm, size/M

#1215 Enabled tracing/logging/metrics in gitlab source
  gitlab/pkg/reconciler/source/controller.go
  gitlab/pkg/reconciler/source/gitlabsource.go
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/source/config_watcher.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1211 Kafka source tracing
  go.mod
  go.sum
  kafka/source/config/config-observability.yaml
  kafka/source/pkg/adapter/adapter.go
  kafka/source/pkg/adapter/adapter_test.go
  kafka/source/pkg/adapter/message.go
  kafka/source/pkg/reconciler/source/controller.go
  kafka/source/pkg/reconciler/source/kafkasource.go
  kafka/source/pkg/reconciler/source/resources/receive_adapter.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/encoding.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/message.go
  vendor/github.com/cloudevents/sdk-go/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/v2/client/invoker.go
  vendor/github.com/cloudevents/sdk-go/v2/client/options.go
  vendor/github.com/cloudevents/sdk-go/v2/client/receiver.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_marshal.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_validation.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1.go
  vendor/github.com/cloudevents/sdk-go/v2/extensions/distributed_tracing_extension.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/kafka_sarama/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/kafka_sarama/receiver.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/kafka_sarama/sender.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/result.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1220 Rename ConfigWatcher constructor, use ConfigAccessor interface
  gitlab/pkg/reconciler/source/controller.go
  gitlab/pkg/reconciler/source/gitlabsource.go
  go.mod
  go.sum
  kafka/source/pkg/reconciler/source/controller.go
  kafka/source/pkg/reconciler/source/kafkasource.go
  kafka/source/pkg/reconciler/source/resources/receive_adapter_test.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1alpha1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/reconciler/source/config_watcher.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_subscriber_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_test_helper.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1212 Release WebSocket Sources image
  config/tools/websocket-source/websocket-source.yaml
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1223 Fixed kafka source after update to eventing
  kafka/source/pkg/reconciler/source/resources/receive_adapter.go
  test/e2e/helpers/kafka_helper.go
  test/e2e/kafka_binding_test.go
  test/e2e/kafka_source_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1227 awssqs source - fix README.md to be consistent with secret yaml
  awssqs/samples/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1224 Ported cmd to sdk-go v2
  cmd/appender/main.go
  cmd/heartbeats/main.go
  cmd/heartbeats_receiver/main.go
Labels: approved, cla: yes, lgtm, size/M

#1229 Updated to sdk-go rc4
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/binding/format/format.go
  vendor/github.com/cloudevents/sdk-go/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/v2/go.mod
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/options.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1228 Correct references to actual yaml files
  awssqs/config/201-clusterrole.yaml
  camel/source/config/201-clusterrole.yaml
  camel/source/config/202-clusterrolebinding.yaml
  couchdb/source/config/201-clusterrole.yaml
  couchdb/source/config/202-clusterrolebinding.yaml
  github/config/201-clusterrole.yaml
  github/config/202-clusterrolebinding.yaml
  gitlab/config/202-clusterrolebinding.yaml
  kafka/source/config/201-clusterrole.yaml
  kafka/source/config/202-clusterrolebinding.yaml
  prometheus/config/201-clusterrole.yaml
  prometheus/config/202-clusterrolebinding.yaml
Labels: approved, cla: yes, lgtm, size/S

#1226 awssqs source add addressable clusterrole
  awssqs/config/201-clusterrole.yaml
  awssqs/config/202-clusterrolebinding.yaml
Labels: approved, cla: yes, lgtm, size/M

#1231 Add lberk to awssqs OWNERS as approver/reviewer
  OWNERS_ALIASES
  awssqs/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#1234 Removed unused code from Kafka Channel
  kafka/channel/pkg/utils/util.go
Labels: approved, cla: yes, lgtm, size/S

#1241 Fix update-codegen for the post-go-mod world.
  hack/update-codegen.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1242 [RELEASE] Pin knative.dev/{pkg,test-infra} to release-0.15
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1alpha1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/channel/message_receiver.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_spec_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/trigger_no_broker_test_helper.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/prow/prow.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/serverlessservice_types.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#1245 Update for deps
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/k8s_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1232 Channel conformance test spec subscriber
  test/conformance/channel_spec_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1238 Refactored config-kafka CM
  kafka/channel/pkg/reconciler/dispatcher/kafkachannel.go
  kafka/channel/pkg/utils/util.go
  kafka/channel/pkg/utils/util_test.go
Labels: approved, cla: yes, lgtm, size/M

#1240 Prometheus source now supports logging/metrics/tracing CMs
  prometheus/pkg/reconciler/controller.go
  prometheus/pkg/reconciler/prometheussource.go
  prometheus/pkg/reconciler/resources/receive_adapter.go
Labels: approved, cla: yes, lgtm, size/M

#1246 Pressure wash kafka code.
  kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_lifecycle_test.go
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_it_test.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
  kafka/channel/pkg/utils/util.go
  kafka/client.go
  kafka/source/pkg/adapter/adapter.go
  kafka/source/pkg/adapter/adapter_benchmark_test.go
  kafka/source/pkg/apis/sources/v1alpha1/kafka_lifecycle_test.go
  kafka/source/pkg/reconciler/source/kafkasource.go
  test/e2e/helpers/kafka_helper.go
  test/test_images/kafka_performance/kafka_load_generator_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1247 Rename deprecated filter functions to new versions.
  awssqs/pkg/reconciler/controller.go
  camel/source/pkg/reconciler/controller.go
  couchdb/source/pkg/reconciler/controller.go
  github/pkg/reconciler/source/controller.go
  kafka/source/pkg/reconciler/source/controller.go
  prometheus/pkg/reconciler/controller.go
Labels: approved, cla: yes, lgtm, size/S

#1251 Remove unused NewConsumer function
  kafka/client.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1254 Add TOC as approvers
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#1252 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-tests.sh
  vendor/knative.dev/eventing/test/e2e-upgrade-tests.sh
  vendor/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go
  vendor/knative.dev/eventing/test/lib/await.go
  vendor/knative.dev/eventing/test/lib/duck/resource_checks.go
  vendor/knative.dev/eventing/test/lib/duck/serving_checks.go
  vendor/knative.dev/eventing/test/lib/resources/constants.go
  vendor/knative.dev/eventing/test/lib/resources/serving.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1249 Pressure wash natss code.
  natss/pkg/apis/messaging/v1alpha1/natss_channel_lifecycle_test.go
  natss/pkg/dispatcher/dispatcher.go
  natss/pkg/dispatcher/testing/testing.go
  natss/pkg/dispatcher/types.go
  natss/pkg/reconciler/controller/natsschannel.go
Labels: approved, cla: yes, lgtm, size/M

#1258 Attempt to fix flacky CamelSource test
  test/e2e/camel_source_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1244 Add lberk to approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1259 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/config/channel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/channel_conversion.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/in_memory_channel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_defaults.go
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/broker.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_header_single_event_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/traces.go
  vendor/knative.dev/eventing/test/conformance/helpers/uri.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/trigger_no_broker_test_helper.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/performance/infra/receiver/receiver.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1260 minor change for cloud events 2.0
  cmd/heartbeats/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1230 Port Github source to adapter/v2
  github/cmd/receive_adapter/main.go
  github/pkg/adapter/adapter.go
  github/pkg/adapter/adapter_test.go
  github/pkg/reconciler/source/resources/service.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1263 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-upgrade-tests.sh
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1253 Remove unused messageSender and config in KafkaDispatcher
  kafka/channel/pkg/dispatcher/dispatcher.go
  kafka/channel/pkg/dispatcher/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/S

#1265 [RELEASE] Pin serving to 0.15.
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1266 Fix/mitigate data race in kafka source
  kafka/common/pkg/kafka/consumer_factory.go
  kafka/common/pkg/kafka/consumer_factory_test.go
  kafka/common/pkg/kafka/consumer_handler.go
Labels: approved, cla: yes, lgtm, size/M

#1248 Pressure wash couchdb, ceph, gitlab and prometheus.
  ceph/pkg/adapter/adapter_test.go
  couchdb/source/pkg/adapter/adapter_test.go
  couchdb/source/pkg/reconciler/couchdbsource.go
  gitlab/pkg/adapter/receive_adapter.go
  gitlab/pkg/adapter/receive_adapter_test.go
  gitlab/pkg/reconciler/source/gitlabsource.go
  gitlab/pkg/reconciler/source/webhook_client.go
  prometheus/pkg/reconciler/prometheussource.go
Labels: approved, cla: yes, lgtm, size/M

#1271 [RELEASE] Pin eventing branch to 'release-0.15'.
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1272 [POST-RELEASE] Track master branches again.
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/register.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/eventtype.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/listers.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/config/store.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_lifecycle.go
  vendor/knative.dev/test-infra/scripts/update-test-infra.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1268 Fix data race in Gitlab unit tests
  gitlab/pkg/adapter/receive_adapter.go
  gitlab/pkg/adapter/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/M

#1275 Fixed the key type deserializer
  kafka/source/pkg/reconciler/source/kafkasource.go
Labels: approved, cla: yes, lgtm, size/XS

#1276 Fixed the key type deserializer
  kafka/source/pkg/reconciler/source/kafkasource.go
Labels: approved, cla: yes, lgtm, size/XS

#1255 Port Ceph source to adapter/v2.
  ceph/cmd/receive_adapter/main.go
  ceph/pkg/adapter/adapter.go
  ceph/pkg/adapter/adapter_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1277 Replace Ceph samples with latest resources
  ceph/README.md
  ceph/samples/ceph-bucket-notification-svc.yaml
  ceph/samples/ceph-container-source.yaml
  ceph/samples/ceph-display-resources.yaml
  ceph/samples/ceph-source.yaml
  ceph/samples/test-pod.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#1279 use MT Broker for tests
  test/e2e-tests.sh
  test/e2e/broker_channel_flow_test.go
  test/e2e/broker_dls_test.go
  test/e2e/broker_event_transformation_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1281 Rename update-k8s-dep.sh to update-k8s-deps.sh
  hack/update-k8s-deps.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1283 [release-0.15] bump knative.dev/pkg to include webhook fix
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1282 [master] golang format tools
  kafka/channel/pkg/dispatcher/dispatcher_it_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1270 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1237 add ko.yaml to specify non root images
  .ko.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1286 grab the latest eventing without ChannelBroker
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_types.go
  vendor/knative.dev/eventing/pkg/reconciler/namespace/resources/broker.go
  vendor/knative.dev/eventing/pkg/reconciler/namespace/resources/configmappropagation.go
  vendor/knative.dev/eventing/pkg/reconciler/namespace/resources/labels.go
  vendor/knative.dev/eventing/pkg/reconciler/namespace/resources/names.go
  vendor/knative.dev/eventing/pkg/reconciler/namespace/resources/role_binding.go
  vendor/knative.dev/eventing/pkg/reconciler/namespace/resources/secret.go
  vendor/knative.dev/eventing/pkg/reconciler/namespace/resources/service_account.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-tests.sh
  vendor/knative.dev/eventing/test/e2e-upgrade-tests.sh
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_dls_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_with_config_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/eventing/test/e2e_flags.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL
